package mainGUI;

// Importing the other GUI: QuestionGenerating GUI
import accountGUI.*;
import notepadGUI.*;
import questionGeneratingGUI.QuestionGenerator;
import pomodoroGUI.*;
import testUploadGUI.*;
import pastTestGUI.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pamlee
 */
public class MainGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGUI.class.getName());

    
    /**
     * Creates new form MainGUITest
     */
    public MainGUI() 
    {
        initComponents();
        
        if(LoginGUI.adminCheck())
        {
            lblHelloPrompt.setText("Hello, Admin!");
        }
        else // If the user is not an admin, just display the general message for BHSS students: "Hello, Hornet!"
        {
            lblHelloPrompt.setText("Hello, Hornet!");
        }
        
        // Making all the buttons appear as just text (app aesthetic)
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setFocusPainted(false);
        
        btnAccount.setContentAreaFilled(false);
        btnAccount.setFocusPainted(false);
        
        btnCloseMenu.setContentAreaFilled(false);
        btnCloseMenu.setFocusPainted(false);
        
        btnOpenMenu.setContentAreaFilled(false);
        btnOpenMenu.setFocusPainted(false);
        
        btnStudyTools.setContentAreaFilled(false);
        btnStudyTools.setFocusPainted(false);
        
        btnPomoTimer.setContentAreaFilled(false);
        btnPomoTimer.setFocusPainted(false);
        
        btnPastTest.setContentAreaFilled(false);
        btnPastTest.setFocusPainted(false);
        
        btnQuestionGen.setContentAreaFilled(false);
        btnQuestionGen.setFocusPainted(false);
        
        btnUploadTest.setContentAreaFilled(false);
        btnUploadTest.setFocusPainted(false);
        
        btnNotepad.setContentAreaFilled(false);
        btnNotepad.setFocusPainted(false);
        
        btnMyStreak.setContentAreaFilled(false);
        btnMyStreak.setFocusPainted(false);
        
        btnPomoOrange.setContentAreaFilled(false);
        btnPomoOrange.setFocusPainted(false);
        
        btnPastTestOrange.setContentAreaFilled(false);
        btnPastTestOrange.setFocusPainted(false);
        
        btnTestUploadOrange.setContentAreaFilled(false);
        btnTestUploadOrange.setFocusPainted(false);
        
        btnMyStreakOrange.setContentAreaFilled(false);
        btnMyStreakOrange.setFocusPainted(false);
        
        btnQuestionGenOrange.setContentAreaFilled(false);
        btnQuestionGenOrange.setFocusPainted(false);
        
        // Using HTML and br (line-break) to forcefully have 2 lines for the text
        // Natalie: I learnt this in my co-op last year :)
        btnQuestionGenOrange.setText("<html>Question<br>Generator</html>");
        
        // Hide the full-page buttons (open menu, extra button only in full-screen)
        btnOpenMenu.setEnabled(false);
        btnOpenMenu.setVisible(false);
        
        btnQuestionGenOrange.setEnabled(false);
        btnQuestionGenOrange.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHelloPrompt = new javax.swing.JLabel();
        btnMyStreakOrange = new javax.swing.JButton();
        btnTestUploadOrange = new javax.swing.JButton();
        btnPastTestOrange = new javax.swing.JButton();
        btnPomoOrange = new javax.swing.JButton();
        btnMyStreak = new javax.swing.JButton();
        btnNotepad = new javax.swing.JButton();
        btnUploadTest = new javax.swing.JButton();
        btnQuestionGen = new javax.swing.JButton();
        btnPastTest = new javax.swing.JButton();
        btnPomoTimer = new javax.swing.JButton();
        btnStudyTools = new javax.swing.JButton();
        btnAccount = new javax.swing.JButton();
        btnCloseMenu = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();
        btnQuestionGenOrange = new javax.swing.JButton();
        btnOpenMenu = new javax.swing.JButton();
        lblBackgroundWOMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        lblHelloPrompt.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        lblHelloPrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHelloPrompt.setText("HELLO, USERNAME!");
        jPanel1.add(lblHelloPrompt);
        lblHelloPrompt.setBounds(410, 160, 870, 110);

        btnMyStreakOrange.setBackground(new java.awt.Color(255, 204, 51));
        btnMyStreakOrange.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        btnMyStreakOrange.setForeground(new java.awt.Color(255, 255, 255));
        btnMyStreakOrange.setText(" My Streak");
        btnMyStreakOrange.setBorder(null);
        btnMyStreakOrange.setBorderPainted(false);
        btnMyStreakOrange.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnMyStreakOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyStreakOrangeActionPerformed(evt);
            }
        });
        jPanel1.add(btnMyStreakOrange);
        btnMyStreakOrange.setBounds(850, 506, 320, 140);

        btnTestUploadOrange.setBackground(new java.awt.Color(255, 204, 51));
        btnTestUploadOrange.setFont(new java.awt.Font("Verdana", 1, 32)); // NOI18N
        btnTestUploadOrange.setForeground(new java.awt.Color(255, 255, 255));
        btnTestUploadOrange.setText("Test Upload");
        btnTestUploadOrange.setBorder(null);
        btnTestUploadOrange.setBorderPainted(false);
        btnTestUploadOrange.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnTestUploadOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestUploadOrangeActionPerformed(evt);
            }
        });
        jPanel1.add(btnTestUploadOrange);
        btnTestUploadOrange.setBounds(500, 506, 320, 140);

        btnPastTestOrange.setBackground(new java.awt.Color(255, 204, 51));
        btnPastTestOrange.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        btnPastTestOrange.setForeground(new java.awt.Color(255, 255, 255));
        btnPastTestOrange.setText(" Past Tests");
        btnPastTestOrange.setBorder(null);
        btnPastTestOrange.setBorderPainted(false);
        btnPastTestOrange.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnPastTestOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastTestOrangeActionPerformed(evt);
            }
        });
        jPanel1.add(btnPastTestOrange);
        btnPastTestOrange.setBounds(850, 330, 320, 140);

        btnPomoOrange.setBackground(new java.awt.Color(255, 204, 51));
        btnPomoOrange.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        btnPomoOrange.setForeground(new java.awt.Color(255, 255, 255));
        btnPomoOrange.setText("Pomodoro");
        btnPomoOrange.setBorder(null);
        btnPomoOrange.setBorderPainted(false);
        btnPomoOrange.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnPomoOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPomoOrangeActionPerformed(evt);
            }
        });
        jPanel1.add(btnPomoOrange);
        btnPomoOrange.setBounds(500, 330, 320, 140);

        btnMyStreak.setBackground(new java.awt.Color(255, 204, 102));
        btnMyStreak.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnMyStreak.setText("My Streak");
        btnMyStreak.setBorder(null);
        btnMyStreak.setBorderPainted(false);
        btnMyStreak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyStreakActionPerformed(evt);
            }
        });
        jPanel1.add(btnMyStreak);
        btnMyStreak.setBounds(60, 560, 270, 30);

        btnNotepad.setBackground(new java.awt.Color(255, 204, 102));
        btnNotepad.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnNotepad.setText("Notepad");
        btnNotepad.setBorder(null);
        btnNotepad.setBorderPainted(false);
        btnNotepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotepadActionPerformed(evt);
            }
        });
        jPanel1.add(btnNotepad);
        btnNotepad.setBounds(60, 500, 270, 30);

        btnUploadTest.setBackground(new java.awt.Color(255, 204, 102));
        btnUploadTest.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnUploadTest.setText("Upload A Test");
        btnUploadTest.setBorder(null);
        btnUploadTest.setBorderPainted(false);
        btnUploadTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadTestActionPerformed(evt);
            }
        });
        jPanel1.add(btnUploadTest);
        btnUploadTest.setBounds(60, 440, 270, 30);

        btnQuestionGen.setBackground(new java.awt.Color(255, 204, 102));
        btnQuestionGen.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnQuestionGen.setText("Question Generator");
        btnQuestionGen.setBorder(null);
        btnQuestionGen.setBorderPainted(false);
        btnQuestionGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuestionGenActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuestionGen);
        btnQuestionGen.setBounds(60, 380, 270, 30);

        btnPastTest.setBackground(new java.awt.Color(255, 204, 51));
        btnPastTest.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnPastTest.setText("Past Student Tests");
        btnPastTest.setBorder(null);
        btnPastTest.setBorderPainted(false);
        btnPastTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastTestActionPerformed(evt);
            }
        });
        jPanel1.add(btnPastTest);
        btnPastTest.setBounds(60, 320, 270, 30);

        btnPomoTimer.setBackground(new java.awt.Color(255, 204, 51));
        btnPomoTimer.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnPomoTimer.setText("Pomodoro Timer");
        btnPomoTimer.setBorder(null);
        btnPomoTimer.setBorderPainted(false);
        btnPomoTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPomoTimerActionPerformed(evt);
            }
        });
        jPanel1.add(btnPomoTimer);
        btnPomoTimer.setBounds(60, 260, 270, 30);

        btnStudyTools.setBackground(new java.awt.Color(255, 153, 0));
        btnStudyTools.setFont(new java.awt.Font("Verdana", 1, 40)); // NOI18N
        btnStudyTools.setForeground(new java.awt.Color(255, 255, 255));
        btnStudyTools.setText("STUDY TOOLS");
        btnStudyTools.setBorder(null);
        btnStudyTools.setBorderPainted(false);
        btnStudyTools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudyToolsActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudyTools);
        btnStudyTools.setBounds(10, 170, 360, 60);

        btnAccount.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnAccount.setForeground(new java.awt.Color(255, 117, 31));
        btnAccount.setText("MANAGE ACCOUNT");
        btnAccount.setBorder(null);
        btnAccount.setBorderPainted(false);
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccount);
        btnAccount.setBounds(970, 20, 280, 50);

        btnCloseMenu.setBackground(new java.awt.Color(255, 117, 31));
        btnCloseMenu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnCloseMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseMenu.setText("CLOSE MENU");
        btnCloseMenu.setBorder(null);
        btnCloseMenu.setBorderPainted(false);
        btnCloseMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnCloseMenu);
        btnCloseMenu.setBounds(130, 110, 140, 30);

        btnLogOut.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 51, 51));
        btnLogOut.setText("LOG OUT");
        btnLogOut.setBorder(null);
        btnLogOut.setBorderPainted(false);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut);
        btnLogOut.setBounds(100, 616, 180, 40);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Base Interface (Logged-in).png"))); // NOI18N
        lblBackground.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblBackground);
        lblBackground.setBounds(0, 0, 1280, 720);

        btnQuestionGenOrange.setBackground(new java.awt.Color(255, 204, 51));
        btnQuestionGenOrange.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        btnQuestionGenOrange.setForeground(new java.awt.Color(255, 255, 255));
        btnQuestionGenOrange.setText("Question");
        btnQuestionGenOrange.setBorder(null);
        btnQuestionGenOrange.setBorderPainted(false);
        btnQuestionGenOrange.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnQuestionGenOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuestionGenOrangeActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuestionGenOrange);
        btnQuestionGenOrange.setBounds(857, 317, 357, 156);

        btnOpenMenu.setBackground(new java.awt.Color(255, 117, 31));
        btnOpenMenu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnOpenMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnOpenMenu.setText("OPEN MENU");
        btnOpenMenu.setBorder(null);
        btnOpenMenu.setBorderPainted(false);
        btnOpenMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpenMenu);
        btnOpenMenu.setBounds(40, 118, 140, 30);

        lblBackgroundWOMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Base Interface (Logged-in, WITHOUT side menu).png"))); // NOI18N
        lblBackgroundWOMenu.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblBackgroundWOMenu);
        lblBackgroundWOMenu.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1292, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudyToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudyToolsActionPerformed
        // Opens a new version of main menu GUI; "resets" current one
        MainGUI mainGUI = new MainGUI();
        
        mainGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnStudyToolsActionPerformed

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        accountSettingsGUI accountGUI = new accountSettingsGUI();
        
        accountGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnCloseMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseMenuActionPerformed
        // disables buttons to show buttons for the open-menu and remove closed-menu buttons; (app aesthetic)
        lblBackground.setEnabled(false);
        lblBackground.setVisible(false);
        
        btnCloseMenu.setEnabled(false);
        btnCloseMenu.setVisible(false);
        
        btnStudyTools.setEnabled(false);
        btnStudyTools.setVisible(false);
        
        btnPomoTimer.setEnabled(false);
        btnPomoTimer.setVisible(false);
        
        btnPastTest.setEnabled(false);
        btnPastTest.setVisible(false);
        
        btnQuestionGen.setEnabled(false);
        btnQuestionGen.setVisible(false);
        
        btnUploadTest.setEnabled(false);
        btnUploadTest.setVisible(false);
        
        btnNotepad.setEnabled(false);
        btnNotepad.setVisible(false);
        
        btnMyStreak.setEnabled(false);
        btnMyStreak.setVisible(false);
        
        btnOpenMenu.setEnabled(true);
        btnOpenMenu.setVisible(true);
        
        // Move some buttons back in place
        btnLogOut.setLocation(753, 18);
        btnLogOut.setSize(190, 54);
        
        btnPomoOrange.setLocation(70, 317);
        btnPomoOrange.setSize(353, 156);
        
        btnPastTestOrange.setLocation(460, 317);
        btnPastTestOrange.setSize(320, 156);
        
        btnTestUploadOrange.setLocation(266, 514);
        btnTestUploadOrange.setSize(355, 157);
        
        btnMyStreakOrange.setLocation(659, 514);
        btnMyStreakOrange.setSize(356, 157);
        
        btnQuestionGenOrange.setEnabled(true);
        btnQuestionGenOrange.setVisible(true);
        
        lblHelloPrompt.setLocation(230, 140);
    }//GEN-LAST:event_btnCloseMenuActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        LoggedOutMainGUI logOut = new LoggedOutMainGUI();
        
        logOut.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnPomoOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPomoOrangeActionPerformed
        pomodoroGUI pomoGUI = new pomodoroGUI();
        
        pomoGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPomoOrangeActionPerformed

    private void btnPastTestOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastTestOrangeActionPerformed
        pastTestGUI pastTestGUI = new pastTestGUI();
        
        pastTestGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPastTestOrangeActionPerformed

    private void btnTestUploadOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestUploadOrangeActionPerformed
        testUploadGUI testUploadGUI = new testUploadGUI();
        
        testUploadGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTestUploadOrangeActionPerformed

    private void btnMyStreakOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyStreakOrangeActionPerformed
        streakAccountGUI accountGUI = new streakAccountGUI();
        
        accountGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMyStreakOrangeActionPerformed

    private void btnOpenMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenMenuActionPerformed
        // Re-enables buttons to show buttons for the closed-menu; (app aesthetic)s
        
        lblBackground.setEnabled(true);
        lblBackground.setVisible(true);

        // Hide open menu button again
        btnOpenMenu.setEnabled(false);
        btnOpenMenu.setVisible(false);

        // Show the rest of the buttons again
        btnCloseMenu.setEnabled(true);
        btnCloseMenu.setVisible(true);

        btnStudyTools.setEnabled(true);
        btnStudyTools.setVisible(true);

        btnPomoTimer.setEnabled(true);
        btnPomoTimer.setVisible(true);

        btnPastTest.setEnabled(true);
        btnPastTest.setVisible(true);

        btnQuestionGen.setEnabled(true);
        btnQuestionGen.setVisible(true);
        
        btnNotepad.setEnabled(true);
        btnNotepad.setVisible(true);

        btnUploadTest.setEnabled(true);
        btnUploadTest.setVisible(true);

        btnMyStreak.setEnabled(true);
        btnMyStreak.setVisible(true);
        
        // Move some buttons back in place
        btnLogOut.setLocation(100, 616);
        btnLogOut.setSize(180, 40);
        
        btnPomoOrange.setLocation(500, 330);
        btnPomoOrange.setSize(320, 140);
        
        btnPastTestOrange.setLocation(850, 330);
        btnPastTestOrange.setSize(320, 140);
        
        btnTestUploadOrange.setLocation(500, 506);
        btnTestUploadOrange.setSize(320, 140);
        
        btnMyStreakOrange.setLocation(850, 506);
        btnMyStreakOrange.setSize(320, 140);
        
        btnQuestionGenOrange.setEnabled(false);
        btnQuestionGenOrange.setVisible(false);
        
        lblHelloPrompt.setLocation(410, 160);
    }//GEN-LAST:event_btnOpenMenuActionPerformed

    private void btnQuestionGenOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuestionGenOrangeActionPerformed
        // Opens the question generating GUI
        QuestionGenerator questionGUI = new QuestionGenerator();
        
        questionGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuestionGenOrangeActionPerformed

    private void btnMyStreakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyStreakActionPerformed
        streakAccountGUI accountGUI = new streakAccountGUI();

        accountGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMyStreakActionPerformed

    private void btnNotepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotepadActionPerformed
        noteGetterGUI notePad = new noteGetterGUI();
        
        notePad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNotepadActionPerformed

    private void btnUploadTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadTestActionPerformed
        testUploadGUI testUploadNew = new testUploadGUI();

        testUploadNew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUploadTestActionPerformed

    private void btnQuestionGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuestionGenActionPerformed
        QuestionGenerator qGen = new QuestionGenerator();

        qGen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuestionGenActionPerformed

    private void btnPastTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastTestActionPerformed
        pastTestGUI pastTestGUI = new pastTestGUI();

        pastTestGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPastTestActionPerformed

    private void btnPomoTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPomoTimerActionPerformed
        pomodoroGUI pomoGUI = new pomodoroGUI();

        pomoGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPomoTimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnCloseMenu;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMyStreak;
    private javax.swing.JButton btnMyStreakOrange;
    private javax.swing.JButton btnNotepad;
    private javax.swing.JButton btnOpenMenu;
    private javax.swing.JButton btnPastTest;
    private javax.swing.JButton btnPastTestOrange;
    private javax.swing.JButton btnPomoOrange;
    private javax.swing.JButton btnPomoTimer;
    private javax.swing.JButton btnQuestionGen;
    private javax.swing.JButton btnQuestionGenOrange;
    private javax.swing.JButton btnStudyTools;
    private javax.swing.JButton btnTestUploadOrange;
    private javax.swing.JButton btnUploadTest;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBackgroundWOMenu;
    private javax.swing.JLabel lblHelloPrompt;
    // End of variables declaration//GEN-END:variables
}
