/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pastTestGUI;
import accountGUI.LoggedOutMainGUI;
import accountGUI.streakAccountGUI;
import accountGUI.accountSettingsGUI;
import java.util.ArrayList;
import pomodoroGUI.*;
import mainGUI.*;
import questionGeneratingGUI.*;
import testUploadGUI.*;
import notepadGUI.*;

// Imports java.io classes used for reading and writing files
import java.io.*;
// Imports awt which is used for photos and icons
import java.awt.*;
import javax.swing.ImageIcon;


/**
 *
 * @author pamlee
 */
public class pastTestGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(pastTestGUI.class.getName());

    public ArrayList<String[]> arrayTestsFound = new ArrayList<>();
    // Creates a integer varible that represents the page number
    public int intPageNum = 1;
    
    /**
     * Creates new form pastTestGUI
     */
    public pastTestGUI() {
        initComponents();
        
        pnlTestResult1.setVisible(false);
        pnlTestResult2.setVisible(false);
        pnlTestResult3.setVisible(false);
        lblPages.setVisible(false);
        btnNextPage.setVisible(false);
        btnPreviousPage.setVisible(false);
        btnUpload.setVisible(false);
        
        // Making all the buttons appear as just text (app aesthetic)
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setFocusPainted(false);
        
        btnAccount.setContentAreaFilled(false);
        btnAccount.setFocusPainted(false);
        
        btnCloseMenu.setContentAreaFilled(false);
        btnCloseMenu.setFocusPainted(false);
        
        btnOpenMenu.setContentAreaFilled(false);
        btnOpenMenu.setFocusPainted(false);
        
        btnStudyTools.setContentAreaFilled(false);
        btnStudyTools.setFocusPainted(false);
        
        btnPomoTimer.setContentAreaFilled(false);
        btnPomoTimer.setFocusPainted(false);
        
        btnPastTest.setContentAreaFilled(false);
        btnPastTest.setFocusPainted(false);
        
        btnQuestionGen.setContentAreaFilled(false);
        btnQuestionGen.setFocusPainted(false);
        
        btnUploadTest.setContentAreaFilled(false);
        btnUploadTest.setFocusPainted(false);
        
        btnNotepad.setContentAreaFilled(false);
        btnNotepad.setFocusPainted(false);
        
        btnMyStreak.setContentAreaFilled(false);
        btnMyStreak.setFocusPainted(false);
        
        btnSearchTeacher.setContentAreaFilled(false);
        btnSearchTeacher.setFocusPainted(false);
        
        btnPreviousPage.setContentAreaFilled(false);
        btnPreviousPage.setFocusPainted(false);
        
        btnNextPage.setContentAreaFilled(false);
        btnNextPage.setFocusPainted(false);
        
        btnSearchTest.setContentAreaFilled(false);
        btnSearchTest.setFocusPainted(false);
        
        // Hide the full-page buttons (open menu, extra button only in full-screen)
        btnOpenMenu.setEnabled(false);
        btnOpenMenu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlTestResult1 = new javax.swing.JPanel();
        btnTest1 = new javax.swing.JButton();
        lblTestUnit1 = new javax.swing.JLabel();
        lblTestResult1 = new javax.swing.JLabel();
        lblTestName1 = new javax.swing.JLabel();
        lblTeacherName1 = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        pnlTestResult2 = new javax.swing.JPanel();
        btnTest2 = new javax.swing.JButton();
        lblTestUnit2 = new javax.swing.JLabel();
        lblTestResult2 = new javax.swing.JLabel();
        lblTestName2 = new javax.swing.JLabel();
        lblTeacherName2 = new javax.swing.JLabel();
        pnlTestResult3 = new javax.swing.JPanel();
        btnTest3 = new javax.swing.JButton();
        lblTestUnit3 = new javax.swing.JLabel();
        lblTestResult3 = new javax.swing.JLabel();
        lblTestName3 = new javax.swing.JLabel();
        lblTeacherName3 = new javax.swing.JLabel();
        txtSearchInput = new javax.swing.JTextField();
        btnNextPage = new javax.swing.JButton();
        btnPreviousPage = new javax.swing.JButton();
        btnSearchTest = new javax.swing.JButton();
        btnSearchTeacher = new javax.swing.JButton();
        lblResults = new javax.swing.JLabel();
        lblPages = new javax.swing.JLabel();
        btnAccount = new javax.swing.JButton();
        btnCloseMenu = new javax.swing.JButton();
        btnMyStreak = new javax.swing.JButton();
        btnNotepad = new javax.swing.JButton();
        btnUploadTest = new javax.swing.JButton();
        btnQuestionGen = new javax.swing.JButton();
        btnPastTest = new javax.swing.JButton();
        btnPomoTimer = new javax.swing.JButton();
        btnStudyTools = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();
        btnOpenMenu = new javax.swing.JButton();
        lblBackgroundWOMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        pnlTestResult1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlTestResult1.setEnabled(false);
        pnlTestResult1.setMaximumSize(new java.awt.Dimension(318, 100));
        pnlTestResult1.setMinimumSize(new java.awt.Dimension(318, 100));
        pnlTestResult1.setLayout(null);

        btnTest1.setText("Open");
        btnTest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTest1ActionPerformed(evt);
            }
        });
        pnlTestResult1.add(btnTest1);
        btnTest1.setBounds(160, 160, 72, 23);

        lblTestUnit1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblTestUnit1.setText("Test Unit");
        pnlTestResult1.add(lblTestUnit1);
        lblTestUnit1.setBounds(7, 7, 710, 30);

        lblTestResult1.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lblTestResult1.setText("Result:");
        pnlTestResult1.add(lblTestResult1);
        lblTestResult1.setBounds(120, 72, 120, 13);

        lblTestName1.setText("Test Title");
        lblTestName1.setMaximumSize(new java.awt.Dimension(220, 20));
        pnlTestResult1.add(lblTestName1);
        lblTestName1.setBounds(7, 49, 215, 17);

        lblTeacherName1.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lblTeacherName1.setText("Teacher: ");
        pnlTestResult1.add(lblTeacherName1);
        lblTeacherName1.setBounds(10, 70, 100, 13);

        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        pnlTestResult1.add(btnUpload);
        btnUpload.setBounds(80, 160, 72, 23);

        jPanel2.add(pnlTestResult1);

        pnlTestResult2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlTestResult2.setEnabled(false);
        pnlTestResult2.setMaximumSize(new java.awt.Dimension(318, 100));
        pnlTestResult2.setMinimumSize(new java.awt.Dimension(318, 100));
        pnlTestResult2.setLayout(null);

        btnTest2.setText("Open");
        btnTest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTest2ActionPerformed(evt);
            }
        });
        pnlTestResult2.add(btnTest2);
        btnTest2.setBounds(160, 160, 72, 23);

        lblTestUnit2.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblTestUnit2.setText("Test Unit");
        pnlTestResult2.add(lblTestUnit2);
        lblTestUnit2.setBounds(7, 7, 710, 30);

        lblTestResult2.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lblTestResult2.setText("Result");
        pnlTestResult2.add(lblTestResult2);
        lblTestResult2.setBounds(120, 70, 120, 13);

        lblTestName2.setText("Test Title");
        lblTestName2.setMaximumSize(new java.awt.Dimension(215, 20));
        lblTestName2.setPreferredSize(new java.awt.Dimension(215, 20));
        pnlTestResult2.add(lblTestName2);
        lblTestName2.setBounds(7, 49, 215, 20);

        lblTeacherName2.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lblTeacherName2.setText("Teacher: ");
        pnlTestResult2.add(lblTeacherName2);
        lblTeacherName2.setBounds(10, 70, 100, 13);

        jPanel2.add(pnlTestResult2);

        pnlTestResult3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlTestResult3.setEnabled(false);
        pnlTestResult3.setMaximumSize(new java.awt.Dimension(318, 100));
        pnlTestResult3.setMinimumSize(new java.awt.Dimension(318, 100));
        pnlTestResult3.setLayout(null);

        btnTest3.setText("Open");
        btnTest3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTest3ActionPerformed(evt);
            }
        });
        pnlTestResult3.add(btnTest3);
        btnTest3.setBounds(160, 160, 72, 23);

        lblTestUnit3.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblTestUnit3.setText("Test Unit");
        pnlTestResult3.add(lblTestUnit3);
        lblTestUnit3.setBounds(7, 7, 710, 30);

        lblTestResult3.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lblTestResult3.setText("Result:");
        pnlTestResult3.add(lblTestResult3);
        lblTestResult3.setBounds(120, 70, 120, 13);

        lblTestName3.setText("Test Title");
        lblTestName3.setMaximumSize(new java.awt.Dimension(215, 20));
        lblTestName3.setPreferredSize(new java.awt.Dimension(215, 20));
        pnlTestResult3.add(lblTestName3);
        lblTestName3.setBounds(7, 49, 215, 20);

        lblTeacherName3.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lblTeacherName3.setText("Teacher: ");
        pnlTestResult3.add(lblTeacherName3);
        lblTeacherName3.setBounds(7, 70, 100, 13);

        jPanel2.add(pnlTestResult3);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(468, 425, 738, 193);
        jPanel2.getAccessibleContext().setAccessibleName("");

        jPanel1.add(txtSearchInput);
        txtSearchInput.setBounds(466, 252, 740, 61);

        btnNextPage.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        btnNextPage.setForeground(new java.awt.Color(255, 117, 31));
        btnNextPage.setText("Next Page");
        btnNextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextPageActionPerformed(evt);
            }
        });
        jPanel1.add(btnNextPage);
        btnNextPage.setBounds(971, 628, 235, 50);

        btnPreviousPage.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btnPreviousPage.setForeground(new java.awt.Color(255, 117, 31));
        btnPreviousPage.setText("Previous Page");
        btnPreviousPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousPageActionPerformed(evt);
            }
        });
        jPanel1.add(btnPreviousPage);
        btnPreviousPage.setBounds(470, 630, 230, 50);

        btnSearchTest.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btnSearchTest.setForeground(new java.awt.Color(255, 117, 31));
        btnSearchTest.setText("Search Test");
        btnSearchTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTestActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearchTest);
        btnSearchTest.setBounds(468, 322, 190, 50);

        btnSearchTeacher.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btnSearchTeacher.setForeground(new java.awt.Color(255, 117, 31));
        btnSearchTeacher.setText("Search Teacher");
        btnSearchTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTeacherActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearchTeacher);
        btnSearchTeacher.setBounds(687, 322, 236, 50);

        lblResults.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jPanel1.add(lblResults);
        lblResults.setBounds(560, 397, 490, 20);

        lblPages.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblPages.setText("Pages: ");
        jPanel1.add(lblPages);
        lblPages.setBounds(1070, 390, 140, 30);

        btnAccount.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnAccount.setForeground(new java.awt.Color(255, 117, 31));
        btnAccount.setText("MANAGE ACCOUNT");
        btnAccount.setBorder(null);
        btnAccount.setBorderPainted(false);
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccount);
        btnAccount.setBounds(970, 20, 280, 50);

        btnCloseMenu.setBackground(new java.awt.Color(255, 117, 31));
        btnCloseMenu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnCloseMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseMenu.setText("CLOSE MENU");
        btnCloseMenu.setBorder(null);
        btnCloseMenu.setBorderPainted(false);
        btnCloseMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnCloseMenu);
        btnCloseMenu.setBounds(130, 110, 140, 30);

        btnMyStreak.setBackground(new java.awt.Color(255, 204, 102));
        btnMyStreak.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnMyStreak.setText("My Streak");
        btnMyStreak.setBorder(null);
        btnMyStreak.setBorderPainted(false);
        btnMyStreak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyStreakActionPerformed(evt);
            }
        });
        jPanel1.add(btnMyStreak);
        btnMyStreak.setBounds(60, 560, 270, 30);

        btnNotepad.setBackground(new java.awt.Color(255, 204, 102));
        btnNotepad.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnNotepad.setText("Notepad");
        btnNotepad.setBorder(null);
        btnNotepad.setBorderPainted(false);
        btnNotepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotepadActionPerformed(evt);
            }
        });
        jPanel1.add(btnNotepad);
        btnNotepad.setBounds(60, 500, 270, 30);

        btnUploadTest.setBackground(new java.awt.Color(255, 204, 102));
        btnUploadTest.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnUploadTest.setText("Upload A Test");
        btnUploadTest.setBorder(null);
        btnUploadTest.setBorderPainted(false);
        btnUploadTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadTestActionPerformed(evt);
            }
        });
        jPanel1.add(btnUploadTest);
        btnUploadTest.setBounds(60, 440, 270, 30);

        btnQuestionGen.setBackground(new java.awt.Color(255, 204, 102));
        btnQuestionGen.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnQuestionGen.setText("Question Generator");
        btnQuestionGen.setBorder(null);
        btnQuestionGen.setBorderPainted(false);
        btnQuestionGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuestionGenActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuestionGen);
        btnQuestionGen.setBounds(60, 380, 270, 30);

        btnPastTest.setBackground(new java.awt.Color(255, 204, 51));
        btnPastTest.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnPastTest.setForeground(new java.awt.Color(255, 0, 0));
        btnPastTest.setText("Past Student Tests");
        btnPastTest.setBorder(null);
        btnPastTest.setBorderPainted(false);
        btnPastTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastTestActionPerformed(evt);
            }
        });
        jPanel1.add(btnPastTest);
        btnPastTest.setBounds(60, 320, 270, 30);

        btnPomoTimer.setBackground(new java.awt.Color(255, 204, 51));
        btnPomoTimer.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnPomoTimer.setText("Pomodoro Timer");
        btnPomoTimer.setBorder(null);
        btnPomoTimer.setBorderPainted(false);
        btnPomoTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPomoTimerActionPerformed(evt);
            }
        });
        jPanel1.add(btnPomoTimer);
        btnPomoTimer.setBounds(60, 260, 270, 30);

        btnStudyTools.setBackground(new java.awt.Color(255, 153, 0));
        btnStudyTools.setFont(new java.awt.Font("Verdana", 1, 40)); // NOI18N
        btnStudyTools.setForeground(new java.awt.Color(255, 255, 255));
        btnStudyTools.setText("STUDY TOOLS");
        btnStudyTools.setBorder(null);
        btnStudyTools.setBorderPainted(false);
        btnStudyTools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudyToolsActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudyTools);
        btnStudyTools.setBounds(10, 170, 360, 60);

        btnLogOut.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 51, 51));
        btnLogOut.setText("LOG OUT");
        btnLogOut.setBorder(null);
        btnLogOut.setBorderPainted(false);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut);
        btnLogOut.setBounds(100, 620, 180, 30);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Past Student Tests (WITH menu).png"))); // NOI18N
        lblBackground.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblBackground);
        lblBackground.setBounds(0, 0, 1280, 720);

        btnOpenMenu.setBackground(new java.awt.Color(255, 117, 31));
        btnOpenMenu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnOpenMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnOpenMenu.setText("OPEN MENU");
        btnOpenMenu.setBorder(null);
        btnOpenMenu.setBorderPainted(false);
        btnOpenMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpenMenu);
        btnOpenMenu.setBounds(40, 118, 140, 30);

        lblBackgroundWOMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Past Student Tests (WITHOUT menu).png"))); // NOI18N
        lblBackgroundWOMenu.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblBackgroundWOMenu);
        lblBackgroundWOMenu.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        accountSettingsGUI accountGUI = new accountSettingsGUI();
        
        accountGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnCloseMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseMenuActionPerformed
        // disables buttons to show buttons for the open-menu and remove closed-menu buttons; (app aesthetic)
        lblBackground.setEnabled(false);
        lblBackground.setVisible(false);

        btnCloseMenu.setEnabled(false);
        btnCloseMenu.setVisible(false);

        btnStudyTools.setEnabled(false);
        btnStudyTools.setVisible(false);

        btnPomoTimer.setEnabled(false);
        btnPomoTimer.setVisible(false);

        btnPastTest.setEnabled(false);
        btnPastTest.setVisible(false);

        btnQuestionGen.setEnabled(false);
        btnQuestionGen.setVisible(false);
        
        btnNotepad.setEnabled(false);
        btnNotepad.setVisible(false);

        btnUploadTest.setEnabled(false);
        btnUploadTest.setVisible(false);

        btnMyStreak.setEnabled(false);
        btnMyStreak.setVisible(false);

        btnOpenMenu.setEnabled(true);
        btnOpenMenu.setVisible(true);

        btnLogOut.setLocation(753, 18);
        btnLogOut.setSize(190, 54);
        
        jPanel2.setLocation(271, 413);
        
        txtSearchInput.setLocation(270, 239);
        
        lblResults.setLocation(360, 385);
        
        lblPages.setLocation(870, 380);
        
        btnSearchTest.setLocation(270, 310);
        
        btnSearchTeacher.setLocation(490, 310);
        
        btnPreviousPage.setLocation(273, 625);
        
        btnNextPage.setLocation(774, 622);
        
    }//GEN-LAST:event_btnCloseMenuActionPerformed

    private void btnStudyToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudyToolsActionPerformed
        // Opens the main menu GUI
        MainGUI mainGUI = new MainGUI();

        mainGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStudyToolsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        LoggedOutMainGUI logOut = new LoggedOutMainGUI();

        logOut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnOpenMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenMenuActionPerformed
        // Re-enables buttons to show buttons for the closed-menu; (app aesthetic)
        lblBackground.setEnabled(true);
        lblBackground.setVisible(true);

        // Hide open menu button again
        btnOpenMenu.setEnabled(false);
        btnOpenMenu.setVisible(false);

        // Show the rest of the buttons again
        btnCloseMenu.setEnabled(true);
        btnCloseMenu.setVisible(true);

        btnStudyTools.setEnabled(true);
        btnStudyTools.setVisible(true);

        btnPomoTimer.setEnabled(true);
        btnPomoTimer.setVisible(true);

        btnPastTest.setEnabled(true);
        btnPastTest.setVisible(true);

        btnQuestionGen.setEnabled(true);
        btnQuestionGen.setVisible(true);
        
        btnNotepad.setEnabled(true);
        btnNotepad.setVisible(true);

        btnUploadTest.setEnabled(true);
        btnUploadTest.setVisible(true);

        btnMyStreak.setEnabled(true);
        btnMyStreak.setVisible(true);

        btnLogOut.setLocation(100, 620);
        btnLogOut.setSize(180, 30);
        
        btnSearchTest.setLocation(468, 322);
        btnSearchTeacher.setLocation(687, 252);
        btnPreviousPage.setLocation(470, 630);
        btnNextPage.setLocation(971, 628);
        
        jPanel2.setLocation(468, 425);
        
        txtSearchInput.setLocation(466, 252);
        
        lblResults.setLocation(590, 327);
        lblPages.setLocation(1070, 390);
    }//GEN-LAST:event_btnOpenMenuActionPerformed

    private void btnTest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTest1ActionPerformed
        // Gets the result number and uses it as an index to get the photo path, then opens a new jframe to display the photo
        String strResultNum = lblTestResult1.getText();
        String[] strIndex = strResultNum.split(" ");
        int intIndex = Integer.parseInt(strIndex[1]) - 1;
        new pastTestDisplayGUI(((arrayTestsFound.get(intIndex))[4])).setVisible(true);
    }//GEN-LAST:event_btnTest1ActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // Closes this GUI and opens the upload GUI
        testUploadGUI testUploadNew = new testUploadGUI();

        testUploadNew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnNextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextPageActionPerformed
        // Adds 1 to the current page
        intPageNum += 1;
        // Displays page
        pageDisplay();
    }//GEN-LAST:event_btnNextPageActionPerformed

    private void btnSearchTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTestActionPerformed
        // Sets btnUpload to not visible
        btnUpload.setVisible(false);
        // Clears arrayTestsFound
        arrayTestsFound.clear();
        // Sets intPageNum equal to 1
        intPageNum = 1;
        // Gets user input
        String strUserSearch = txtSearchInput.getText();
        // Tries code and catches error
        try{
            // Instantiates buffered reader to read Tests.
            BufferedReader reader = new BufferedReader(new FileReader("src/pastTestGUI/Tests.txt"));
            String line;
            // While loop that goes through every line in the txt file until there is an empty line
            while((line = reader.readLine()) != null){
                // Splits the line whenever there is a colon found
                String[] arrayParts = line.split(":");
                // Checks if the user inputted anything simular to arrayParts[1]
                if((arrayParts[1].toLowerCase()).contains(strUserSearch.toLowerCase())){
                    // Adds it to the arrayTestsFound
                    arrayTestsFound.add(arrayParts);
                }
            }
            // Checks if the user found tests
            if(!arrayTestsFound.isEmpty()){
                // Displays results
                lblResults.setVisible(true);
                lblPages.setVisible(true);
                pageDisplay();
                lblResults.setText(Integer.toString(arrayTestsFound.size()));
            }else {
                // Prompts user to upload their own test
                pnlTestResult1.setVisible(true);
                pnlTestResult2.setVisible(false);
                pnlTestResult3.setVisible(false);
                lblTestUnit1.setText("Test not found");
                lblTestName1.setText("Upload your own test?");
                lblTeacherName1.setText("");
                lblTestResult1.setText("");
                btnUpload.setVisible(true);
            }
            // Catches errors when reading the file
        }catch(IOException e){
            // Displays that there was an error
            lblResults.setText("Results: An error has occured while accessing the file");
        }
    }//GEN-LAST:event_btnSearchTestActionPerformed

    private void btnSearchTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTeacherActionPerformed
        // Sets btnUpload to not visible
        btnUpload.setVisible(false);
        // Clears arrayTestsFound
        arrayTestsFound.clear();
        // Sets intPageNum equal to 1
        intPageNum = 1;
        // Gets user input
        String strUserSearch = txtSearchInput.getText();
        try{
            // Instantiates BufferedReader allowing it to read from tests.txt
            BufferedReader reader = new BufferedReader(new FileReader("src/pastTestGUI/Tests.txt"));
            String line;
            // While loop that goes through every line in the txt file until there is an empty line
            while((line = reader.readLine()) != null){
                // Splits the line each time there is a colon
                String[] arrayParts = line.split(":");
                // Checks if arrayParts[3] contains the user input
                if((arrayParts[3].toLowerCase()).contains(strUserSearch.toLowerCase())){
                    // adds that test to the tests found
                    arrayTestsFound.add(arrayParts);
                }
            }
            // Checks if the user found tests
            if(!arrayTestsFound.isEmpty()){
                // Displays results
                pnlTestResult2.setVisible(true);
                pnlTestResult3.setVisible(true);
                lblResults.setVisible(true);
                lblPages.setVisible(true);
                pageDisplay();
                lblResults.setText(Integer.toString(arrayTestsFound.size()));
            }else {
                // Prompts user to upload their own test
                pnlTestResult1.setVisible(true);
                pnlTestResult2.setVisible(false);
                pnlTestResult3.setVisible(false);
                lblTestUnit1.setText("Test not found");
                lblTestName1.setText("Upload your own test?");
                lblTeacherName1.setText("");
                lblTestResult1.setText("");
                btnUpload.setVisible(true);
            }
            // Catches errors when reading the file
        }catch(IOException e){
            // Displays that there was an error
            lblResults.setText("Results: An error has occured while accessing the file");
        }
    }//GEN-LAST:event_btnSearchTeacherActionPerformed

    private void btnTest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTest2ActionPerformed
        // Gets the result number and uses it as an index to get the photo path, then opens a new jframe to display the photo
        String strResultNum = lblTestResult2.getText();
        String[] strIndex = strResultNum.split(" ");
        int intIndex = Integer.parseInt(strIndex[1]) - 1;
        new pastTestDisplayGUI(((arrayTestsFound.get(intIndex))[4])).setVisible(true);
    }//GEN-LAST:event_btnTest2ActionPerformed

    private void btnTest3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTest3ActionPerformed
        // Gets the result number and uses it as an index to get the photo path, then opens a new jframe to display the photo
        String strResultNum = lblTestResult3.getText();
        String[] strIndex = strResultNum.split(" ");
        int intIndex = Integer.parseInt(strIndex[1]) - 1;
        new pastTestDisplayGUI(((arrayTestsFound.get(intIndex))[4])).setVisible(true);
    }//GEN-LAST:event_btnTest3ActionPerformed

    private void btnPreviousPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousPageActionPerformed
        // Subtracts 1 from the current pages
        intPageNum -= 1;
        // Displays page
        pageDisplay();
    }//GEN-LAST:event_btnPreviousPageActionPerformed

    private void btnMyStreakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyStreakActionPerformed
        streakAccountGUI accountGUI = new streakAccountGUI();

        accountGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMyStreakActionPerformed

    private void btnNotepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotepadActionPerformed
        noteGetterGUI notePad = new noteGetterGUI();
        
        notePad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNotepadActionPerformed

    private void btnUploadTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadTestActionPerformed
        testUploadGUI testUploadNew = new testUploadGUI();

        testUploadNew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUploadTestActionPerformed

    private void btnQuestionGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuestionGenActionPerformed
        QuestionGenerator qGen = new QuestionGenerator();

        qGen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuestionGenActionPerformed

    private void btnPastTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastTestActionPerformed
        pastTestGUI pastTestGUI = new pastTestGUI();

        pastTestGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPastTestActionPerformed

    private void btnPomoTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPomoTimerActionPerformed
        pomodoroGUI pomoGUI = new pomodoroGUI();

        pomoGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPomoTimerActionPerformed

    
    // Method that displays the search results
    public void pageDisplay(){
        // Sets the visibility of all the panels to false
        pnlTestResult1.setVisible(false);
        pnlTestResult2.setVisible(false);
        pnlTestResult3.setVisible(false);
        btnNextPage.setVisible(false);
        btnPreviousPage.setVisible(false);
        int intPagesDisplay;
        // Since each page can display up to 3 pages, the amount of pages is the results found/3 + 1 if there is a remainder
        int intPageAmount = arrayTestsFound.size()/3;
        if (arrayTestsFound.size()%3 != 0){
            intPageAmount += 1;
        }
        // Checks if the page amount is greater than 1, and that the page amount is not the last page
        if (intPageAmount > 1 && intPageAmount != intPageNum){
            // Displays button
            btnNextPage.setVisible(true);
        }
        // Checks if the current page is not the first page
        if (intPageNum != 1){
            // Displays previous page button
            btnPreviousPage.setVisible(true);
        }
        // Displays number of pages
        lblPages.setText("Pages: " + intPageAmount);
        // Checks how many panels need to be displayed if it is the final page
        if (intPageAmount == intPageNum){
            intPagesDisplay = (arrayTestsFound.size() - intPageAmount*3) + 3;
        }else{
            intPagesDisplay = 3;
        }
        // Displays first panel and sets the values
        if (intPagesDisplay >= 1){
            pnlTestResult1.setVisible(true);
            lblTestUnit1.setText((arrayTestsFound.get((intPageNum - 1)*3))[0]);
            lblTestName1.setText((arrayTestsFound.get((intPageNum - 1)*3))[2]);
            lblTeacherName1.setText("Teacher: " + (arrayTestsFound.get((intPageNum - 1)*3))[3]);
            lblTestResult1.setText("Result: " + (1 + (intPageNum - 1)*3));
        }
        // Displays second panel and sets the values
        if (intPagesDisplay >= 2){
            pnlTestResult2.setVisible(true);
            lblTestUnit2.setText((arrayTestsFound.get(1 + (intPageNum - 1)*3))[0]);
            lblTestName2.setText((arrayTestsFound.get(1 + (intPageNum - 1)*3))[2]);
            lblTeacherName2.setText("Teacher: " + (arrayTestsFound.get(1 + (intPageNum - 1)*3))[3]);
            lblTestResult2.setText("Result: " + ((2 + (intPageNum - 1)*3)));
        }
        // Displays third panel and sets the values
        if (intPagesDisplay == 3){
            pnlTestResult3.setVisible(true);
            lblTestUnit3.setText((arrayTestsFound.get(2 + (intPageNum - 1)*3))[0]);
            lblTestName3.setText((arrayTestsFound.get(2 + (intPageNum - 1)*3))[2]);
            lblTeacherName3.setText("Teacher: " + (arrayTestsFound.get(2 + (intPageNum - 1)*3))[3]);
            lblTestResult3.setText("Result: " + ((3 + (intPageNum - 1)*3)));
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new pastTestGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnCloseMenu;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMyStreak;
    private javax.swing.JButton btnNextPage;
    private javax.swing.JButton btnNotepad;
    private javax.swing.JButton btnOpenMenu;
    private javax.swing.JButton btnPastTest;
    private javax.swing.JButton btnPomoTimer;
    private javax.swing.JButton btnPreviousPage;
    private javax.swing.JButton btnQuestionGen;
    private javax.swing.JButton btnSearchTeacher;
    private javax.swing.JButton btnSearchTest;
    private javax.swing.JButton btnStudyTools;
    private javax.swing.JButton btnTest1;
    private javax.swing.JButton btnTest2;
    private javax.swing.JButton btnTest3;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton btnUploadTest;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBackgroundWOMenu;
    private javax.swing.JLabel lblPages;
    private javax.swing.JLabel lblResults;
    private javax.swing.JLabel lblTeacherName1;
    private javax.swing.JLabel lblTeacherName2;
    private javax.swing.JLabel lblTeacherName3;
    private javax.swing.JLabel lblTestName1;
    private javax.swing.JLabel lblTestName2;
    private javax.swing.JLabel lblTestName3;
    private javax.swing.JLabel lblTestResult1;
    private javax.swing.JLabel lblTestResult2;
    private javax.swing.JLabel lblTestResult3;
    private javax.swing.JLabel lblTestUnit1;
    private javax.swing.JLabel lblTestUnit2;
    private javax.swing.JLabel lblTestUnit3;
    private javax.swing.JPanel pnlTestResult1;
    private javax.swing.JPanel pnlTestResult2;
    private javax.swing.JPanel pnlTestResult3;
    private javax.swing.JTextField txtSearchInput;
    // End of variables declaration//GEN-END:variables
}
