/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testUploadGUI;

import accountGUI.LoggedOutMainGUI;
import accountGUI.streakAccountGUI;
import accountGUI.accountSettingsGUI;
import pomodoroGUI.*;
import mainGUI.*;
import questionGeneratingGUI.*;
import pastTestGUI.*;

// Imports classes that are used to read and write and create arraylists
import java.io.*;
import java.util.ArrayList;
import notepadGUI.notepadGUI;

/**
 *
 * @author pamlee
 */
public class adminApprovalGUI extends javax.swing.JFrame {
    
    // Creates class varaibles
    public String strCourse;
    public String strUnitNum;
    public String strTeacher;
    public String strUnitName;
    public String strAssessment;
    public String strPhotoLocations;
    public int intPending = 0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adminApprovalGUI.class.getName());

    /**
     * Creates new form adminApprovalGUI
     */
    public adminApprovalGUI() {
        initComponents();
        
        // Calls checkInfo method to see how many pending tests there are
        checkInfo();
        // Hides panels and disables buttons
        pnlInfoChecklist.setVisible(false);
        btnValidate.setEnabled(false);
        btnReject.setEnabled(false);
        btnChange.setEnabled(false);
        btnViewPhotos.setEnabled(false);
        
        // Making all the buttons appear as just text (app aesthetic)
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setFocusPainted(false);
        
        btnAccount.setContentAreaFilled(false);
        btnAccount.setFocusPainted(false);
        
        btnCloseMenu.setContentAreaFilled(false);
        btnCloseMenu.setFocusPainted(false);
        
        btnOpenMenu.setContentAreaFilled(false);
        btnOpenMenu.setFocusPainted(false);
        
        btnStudyTools.setContentAreaFilled(false);
        btnStudyTools.setFocusPainted(false);
        
        btnPomoTimer.setContentAreaFilled(false);
        btnPomoTimer.setFocusPainted(false);
        
        btnPastTest.setContentAreaFilled(false);
        btnPastTest.setFocusPainted(false);
        
        btnQuestionGen.setContentAreaFilled(false);
        btnQuestionGen.setFocusPainted(false);
        
        btnUploadTest.setContentAreaFilled(false);
        btnUploadTest.setFocusPainted(false);
        
        btnNotepad.setContentAreaFilled(false);
        btnNotepad.setFocusPainted(false);
        
        btnMyStreak.setContentAreaFilled(false);
        btnMyStreak.setFocusPainted(false);
        
        btnViewPhotos.setContentAreaFilled(false);
        btnViewPhotos.setFocusPainted(false);
        
        btnReview.setContentAreaFilled(false);
        btnReview.setFocusPainted(false);
        
        btnRefresh.setContentAreaFilled(false);
        btnRefresh.setFocusPainted(false);
        
        btnValidate.setContentAreaFilled(false);
        btnValidate.setFocusPainted(false);
        
        btnReject.setContentAreaFilled(false);
        btnReject.setFocusPainted(false);
        
        btnChange.setContentAreaFilled(false);
        btnChange.setFocusPainted(false);
        
        // Hide the full-page buttons (open menu, extra button only in full-screen)
        btnOpenMenu.setEnabled(false);
        btnOpenMenu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnViewPhotos = new javax.swing.JButton();
        pnlInfoChecklist = new javax.swing.JPanel();
        lblCourse = new javax.swing.JLabel();
        lblUnitNumber = new javax.swing.JLabel();
        lblTeacher = new javax.swing.JLabel();
        lblUnitName = new javax.swing.JLabel();
        lblAssessment = new javax.swing.JLabel();
        ckbxCourse = new javax.swing.JCheckBox();
        ckbxUnitNum = new javax.swing.JCheckBox();
        ckbxTeacher = new javax.swing.JCheckBox();
        ckbxUnitName = new javax.swing.JCheckBox();
        ckbxAssessment = new javax.swing.JCheckBox();
        txtAssessmentChange = new javax.swing.JTextField();
        txtUnitNameChange = new javax.swing.JTextField();
        txtTeacherChange = new javax.swing.JTextField();
        txtUnitNumChange = new javax.swing.JTextField();
        txtCourseChange = new javax.swing.JTextField();
        btnValidate = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        lblPending = new javax.swing.JLabel();
        btnReview = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnAccount = new javax.swing.JButton();
        btnCloseMenu = new javax.swing.JButton();
        btnMyStreak = new javax.swing.JButton();
        btnNotepad = new javax.swing.JButton();
        btnUploadTest = new javax.swing.JButton();
        btnQuestionGen = new javax.swing.JButton();
        btnPastTest = new javax.swing.JButton();
        btnPomoTimer = new javax.swing.JButton();
        btnStudyTools = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();
        btnOpenMenu = new javax.swing.JButton();
        lblBackgroundWOMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        btnViewPhotos.setBackground(new java.awt.Color(255, 117, 31));
        btnViewPhotos.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnViewPhotos.setForeground(new java.awt.Color(255, 255, 255));
        btnViewPhotos.setText("View Photos");
        btnViewPhotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPhotosActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewPhotos);
        btnViewPhotos.setBounds(431, 202, 172, 50);

        pnlInfoChecklist.setOpaque(false);
        pnlInfoChecklist.setLayout(null);

        lblCourse.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblCourse.setText("Course: ");
        pnlInfoChecklist.add(lblCourse);
        lblCourse.setBounds(10, 10, 400, 60);

        lblUnitNumber.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblUnitNumber.setText("Unit Number:");
        pnlInfoChecklist.add(lblUnitNumber);
        lblUnitNumber.setBounds(10, 70, 400, 60);

        lblTeacher.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblTeacher.setText("Teacher:");
        pnlInfoChecklist.add(lblTeacher);
        lblTeacher.setBounds(10, 130, 400, 60);

        lblUnitName.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblUnitName.setText("Unit Name:");
        pnlInfoChecklist.add(lblUnitName);
        lblUnitName.setBounds(10, 190, 400, 60);

        lblAssessment.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblAssessment.setText("Assessment Name:");
        pnlInfoChecklist.add(lblAssessment);
        lblAssessment.setBounds(10, 250, 400, 60);

        ckbxCourse.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        ckbxCourse.setText("Valid");
        pnlInfoChecklist.add(ckbxCourse);
        ckbxCourse.setBounds(400, 10, 100, 60);

        ckbxUnitNum.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        ckbxUnitNum.setText("Valid");
        pnlInfoChecklist.add(ckbxUnitNum);
        ckbxUnitNum.setBounds(400, 70, 100, 60);

        ckbxTeacher.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        ckbxTeacher.setText("Valid");
        pnlInfoChecklist.add(ckbxTeacher);
        ckbxTeacher.setBounds(400, 130, 100, 60);

        ckbxUnitName.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        ckbxUnitName.setText("Valid");
        pnlInfoChecklist.add(ckbxUnitName);
        ckbxUnitName.setBounds(400, 190, 100, 60);

        ckbxAssessment.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        ckbxAssessment.setText("Valid");
        pnlInfoChecklist.add(ckbxAssessment);
        ckbxAssessment.setBounds(400, 250, 100, 60);

        txtAssessmentChange.setMinimumSize(new java.awt.Dimension(160, 28));
        txtAssessmentChange.setPreferredSize(new java.awt.Dimension(160, 28));
        pnlInfoChecklist.add(txtAssessmentChange);
        txtAssessmentChange.setBounds(510, 250, 270, 55);

        txtUnitNameChange.setMinimumSize(new java.awt.Dimension(160, 28));
        txtUnitNameChange.setPreferredSize(new java.awt.Dimension(160, 28));
        pnlInfoChecklist.add(txtUnitNameChange);
        txtUnitNameChange.setBounds(510, 190, 270, 55);

        txtTeacherChange.setMinimumSize(new java.awt.Dimension(160, 28));
        txtTeacherChange.setPreferredSize(new java.awt.Dimension(160, 28));
        pnlInfoChecklist.add(txtTeacherChange);
        txtTeacherChange.setBounds(510, 130, 270, 55);

        txtUnitNumChange.setMinimumSize(new java.awt.Dimension(160, 28));
        txtUnitNumChange.setPreferredSize(new java.awt.Dimension(160, 28));
        txtUnitNumChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitNumChangeActionPerformed(evt);
            }
        });
        pnlInfoChecklist.add(txtUnitNumChange);
        txtUnitNumChange.setBounds(510, 70, 270, 55);

        txtCourseChange.setMinimumSize(new java.awt.Dimension(160, 28));
        txtCourseChange.setPreferredSize(new java.awt.Dimension(160, 28));
        pnlInfoChecklist.add(txtCourseChange);
        txtCourseChange.setBounds(510, 10, 270, 55);

        btnValidate.setBackground(new java.awt.Color(255, 117, 31));
        btnValidate.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        btnValidate.setForeground(new java.awt.Color(255, 255, 255));
        btnValidate.setText("VALIDATE");
        btnValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateActionPerformed(evt);
            }
        });
        pnlInfoChecklist.add(btnValidate);
        btnValidate.setBounds(10, 335, 180, 70);

        btnReject.setBackground(new java.awt.Color(255, 0, 0));
        btnReject.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        btnReject.setForeground(new java.awt.Color(255, 255, 255));
        btnReject.setText("REJECT");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });
        pnlInfoChecklist.add(btnReject);
        btnReject.setBounds(203, 335, 180, 70);

        btnChange.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        btnChange.setForeground(new java.awt.Color(255, 117, 31));
        btnChange.setText("Make Changes");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        pnlInfoChecklist.add(btnChange);
        btnChange.setBounds(569, 337, 206, 65);

        jPanel1.add(pnlInfoChecklist);
        pnlInfoChecklist.setBounds(430, 270, 790, 420);

        lblPending.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblPending.setText("Pending Tests: ");
        jPanel1.add(lblPending);
        lblPending.setBounds(610, 200, 280, 50);

        btnReview.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnReview.setForeground(new java.awt.Color(255, 117, 31));
        btnReview.setText("Begin Review");
        btnReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewActionPerformed(evt);
            }
        });
        jPanel1.add(btnReview);
        btnReview.setBounds(1036, 201, 190, 50);

        btnRefresh.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 117, 31));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh);
        btnRefresh.setBounds(900, 202, 123, 50);

        btnAccount.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnAccount.setForeground(new java.awt.Color(255, 117, 31));
        btnAccount.setText("MANAGE ACCOUNT");
        btnAccount.setBorder(null);
        btnAccount.setBorderPainted(false);
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccount);
        btnAccount.setBounds(970, 20, 280, 50);

        btnCloseMenu.setBackground(new java.awt.Color(255, 117, 31));
        btnCloseMenu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnCloseMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseMenu.setText("CLOSE MENU");
        btnCloseMenu.setBorder(null);
        btnCloseMenu.setBorderPainted(false);
        btnCloseMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnCloseMenu);
        btnCloseMenu.setBounds(130, 110, 140, 30);

        btnMyStreak.setBackground(new java.awt.Color(255, 204, 102));
        btnMyStreak.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnMyStreak.setText("My Streak");
        btnMyStreak.setBorder(null);
        btnMyStreak.setBorderPainted(false);
        btnMyStreak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyStreakActionPerformed(evt);
            }
        });
        jPanel1.add(btnMyStreak);
        btnMyStreak.setBounds(60, 560, 270, 30);

        btnNotepad.setBackground(new java.awt.Color(255, 204, 102));
        btnNotepad.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnNotepad.setText("Notepad");
        btnNotepad.setBorder(null);
        btnNotepad.setBorderPainted(false);
        btnNotepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotepadActionPerformed(evt);
            }
        });
        jPanel1.add(btnNotepad);
        btnNotepad.setBounds(60, 500, 270, 30);

        btnUploadTest.setBackground(new java.awt.Color(255, 204, 102));
        btnUploadTest.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnUploadTest.setForeground(new java.awt.Color(255, 0, 0));
        btnUploadTest.setText("Upload A Test");
        btnUploadTest.setBorder(null);
        btnUploadTest.setBorderPainted(false);
        btnUploadTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadTestActionPerformed(evt);
            }
        });
        jPanel1.add(btnUploadTest);
        btnUploadTest.setBounds(60, 440, 270, 30);

        btnQuestionGen.setBackground(new java.awt.Color(255, 204, 102));
        btnQuestionGen.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnQuestionGen.setText("Question Generator");
        btnQuestionGen.setBorder(null);
        btnQuestionGen.setBorderPainted(false);
        btnQuestionGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuestionGenActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuestionGen);
        btnQuestionGen.setBounds(60, 380, 270, 30);

        btnPastTest.setBackground(new java.awt.Color(255, 204, 51));
        btnPastTest.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnPastTest.setText("Past Student Tests");
        btnPastTest.setBorder(null);
        btnPastTest.setBorderPainted(false);
        btnPastTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastTestActionPerformed(evt);
            }
        });
        jPanel1.add(btnPastTest);
        btnPastTest.setBounds(60, 320, 270, 30);

        btnPomoTimer.setBackground(new java.awt.Color(255, 204, 51));
        btnPomoTimer.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnPomoTimer.setText("Pomodoro Timer");
        btnPomoTimer.setBorder(null);
        btnPomoTimer.setBorderPainted(false);
        btnPomoTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPomoTimerActionPerformed(evt);
            }
        });
        jPanel1.add(btnPomoTimer);
        btnPomoTimer.setBounds(60, 260, 270, 30);

        btnStudyTools.setBackground(new java.awt.Color(255, 153, 0));
        btnStudyTools.setFont(new java.awt.Font("Verdana", 1, 40)); // NOI18N
        btnStudyTools.setForeground(new java.awt.Color(255, 255, 255));
        btnStudyTools.setText("STUDY TOOLS");
        btnStudyTools.setBorder(null);
        btnStudyTools.setBorderPainted(false);
        btnStudyTools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudyToolsActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudyTools);
        btnStudyTools.setBounds(10, 170, 360, 60);

        btnLogOut.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 51, 51));
        btnLogOut.setText("LOG OUT");
        btnLogOut.setBorder(null);
        btnLogOut.setBorderPainted(false);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut);
        btnLogOut.setBounds(100, 620, 180, 30);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Admin Approval (WITH menu).png"))); // NOI18N
        lblBackground.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblBackground);
        lblBackground.setBounds(0, 0, 1280, 720);

        btnOpenMenu.setBackground(new java.awt.Color(255, 117, 31));
        btnOpenMenu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnOpenMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnOpenMenu.setText("OPEN MENU");
        btnOpenMenu.setBorder(null);
        btnOpenMenu.setBorderPainted(false);
        btnOpenMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpenMenu);
        btnOpenMenu.setBounds(40, 118, 140, 30);

        lblBackgroundWOMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Admin Approval (WITHOUT menu).png"))); // NOI18N
        lblBackgroundWOMenu.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblBackgroundWOMenu);
        lblBackgroundWOMenu.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        accountSettingsGUI accountGUI = new accountSettingsGUI();
        
        accountGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnCloseMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseMenuActionPerformed
        // disables buttons to show buttons for the open-menu and remove closed-menu buttons; (app aesthetic)
        lblBackground.setEnabled(false);
        lblBackground.setVisible(false);

        btnCloseMenu.setEnabled(false);
        btnCloseMenu.setVisible(false);

        btnStudyTools.setEnabled(false);
        btnStudyTools.setVisible(false);

        btnPomoTimer.setEnabled(false);
        btnPomoTimer.setVisible(false);

        btnPastTest.setEnabled(false);
        btnPastTest.setVisible(false);

        btnQuestionGen.setEnabled(false);
        btnQuestionGen.setVisible(false);

        btnUploadTest.setEnabled(false);
        btnUploadTest.setVisible(false);
        
        btnNotepad.setEnabled(false);
        btnNotepad.setVisible(false);

        btnMyStreak.setEnabled(false);
        btnMyStreak.setVisible(false);

        btnOpenMenu.setEnabled(true);
        btnOpenMenu.setVisible(true);

        btnLogOut.setLocation(753, 18);
        btnLogOut.setSize(190, 54);
        
        pnlInfoChecklist.setLocation(90, 250);
        pnlInfoChecklist.setSize(1100, 420);
        
        // Moving buttons back in place
        btnViewPhotos.setLocation(91, 187);
        
        btnRefresh.setLocation(820, 185);
        btnRefresh.setSize(180, 50);
        
        btnReview.setLocation(1015, 185);
        btnReview.setSize(176, 50);
        
        btnValidate.setLocation(20, 337);
        btnValidate.setSize(240, 70);
        
        btnReject.setLocation(280, 338);
        btnReject.setSize(250, 70);
        
        btnChange.setLocation(829, 340);
        btnChange.setSize(240, 65);
        
        // Moving the text back to closed-menu position
        lblCourse.setLocation(10, 10);
        lblUnitNumber.setLocation(10, 70);
        lblTeacher.setLocation(10, 130);
        lblUnitName.setLocation(10, 190);
        lblAssessment.setLocation(10, 250);
        lblPending.setLocation(380, 180);
        
        // Moving the validation boxes
        ckbxCourse.setLocation(490, 10);
        ckbxUnitNum.setLocation(490, 70);
        ckbxTeacher.setLocation(490, 130);
        ckbxUnitName.setLocation(490, 190);
        ckbxAssessment.setLocation(490, 250);
        
        // Moving the textboxes back to closed-menu position
        txtCourseChange.setLocation(600, 10);
        txtCourseChange.setSize(470, 55);
        
        txtUnitNumChange.setLocation(600, 70);
        txtUnitNumChange.setSize(470, 55);
        
        txtTeacherChange.setLocation(600, 130);
        txtTeacherChange.setSize(470, 55);
        
        txtUnitNameChange.setLocation(600, 190);
        txtUnitNameChange.setSize(470, 55);
        
        txtAssessmentChange.setLocation(600, 250);
        txtAssessmentChange.setSize(470, 55);
        

    }//GEN-LAST:event_btnCloseMenuActionPerformed

    private void btnStudyToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudyToolsActionPerformed
        // Opens the main menu GUI
        MainGUI mainGUI = new MainGUI();

        mainGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStudyToolsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        LoggedOutMainGUI logOut = new LoggedOutMainGUI();

        logOut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnOpenMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenMenuActionPerformed
        // Re-enables buttons to show buttons for the closed-menu; (app aesthetic)
        lblBackground.setEnabled(true);
        lblBackground.setVisible(true);

        // Hide open menu button again
        btnOpenMenu.setEnabled(false);
        btnOpenMenu.setVisible(false);

        // Show the rest of the buttons again
        btnCloseMenu.setEnabled(true);
        btnCloseMenu.setVisible(true);

        btnStudyTools.setEnabled(true);
        btnStudyTools.setVisible(true);

        btnPomoTimer.setEnabled(true);
        btnPomoTimer.setVisible(true);

        btnPastTest.setEnabled(true);
        btnPastTest.setVisible(true);

        btnQuestionGen.setEnabled(true);
        btnQuestionGen.setVisible(true);

        btnUploadTest.setEnabled(true);
        btnUploadTest.setVisible(true);
        
        btnNotepad.setEnabled(true);
        btnNotepad.setVisible(true);

        btnMyStreak.setEnabled(true);
        btnMyStreak.setVisible(true);

        btnLogOut.setLocation(100, 620);
        btnLogOut.setSize(180, 30);
        
        // Moving buttons back in place
        btnViewPhotos.setLocation(431, 202);
        btnViewPhotos.setSize(172, 50);
        
        btnRefresh.setLocation(900, 202);
        btnRefresh.setSize(123, 50);
        
        btnReview.setLocation(1036, 201);
        btnReview.setSize(190, 50);
        
        btnValidate.setLocation(10, 335);
        btnValidate.setSize(180, 70);
        
        btnReject.setLocation(203, 335);
        btnReject.setSize(180, 70);
        
        btnChange.setLocation(569, 337);
        btnChange.setSize(206, 65);
        
        pnlInfoChecklist.setLocation(430, 270);
        pnlInfoChecklist.setSize(790, 420);
        
        // Moving the text back to the opened-menu position
        lblCourse.setLocation(10, 10);
        lblUnitNumber.setLocation(10, 70);
        lblTeacher.setLocation(10, 130);
        lblUnitName.setLocation(10, 190);
        lblAssessment.setLocation(10, 250);
        lblPending.setLocation(610, 200);
        
        // Moving the validation boxes
        ckbxCourse.setLocation(400, 10);
        ckbxUnitNum.setLocation(400, 70);
        ckbxTeacher.setLocation(400, 130);
        ckbxUnitName.setLocation(400, 190);
        ckbxAssessment.setLocation(400, 250);
        
        // Moving the textboxes back to the opened-menu position
        txtCourseChange.setLocation(510, 10);
        txtCourseChange.setSize(270, 55);
        
        txtUnitNumChange.setLocation(510, 70);
        txtUnitNumChange.setSize(270, 55);
        
        txtTeacherChange.setLocation(510, 130);
        txtTeacherChange.setSize(270, 55);
        
        txtUnitNameChange.setLocation(510, 190);
        txtUnitNameChange.setSize(270, 55);
        
        txtAssessmentChange.setLocation(510, 250);
        txtAssessmentChange.setSize(270, 55);
        
    }//GEN-LAST:event_btnOpenMenuActionPerformed

    private void btnViewPhotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPhotosActionPerformed
        // Opens testDisplay and sends in strPhotoLocations
        new pastTestDisplayGUI(strPhotoLocations).setVisible(true);
    }//GEN-LAST:event_btnViewPhotosActionPerformed

    private void btnReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewActionPerformed
        // Checks that all the class variables are not null
        if (strCourse != null && strUnitNum != null && strTeacher != null && strUnitName != null && strAssessment != null){
            // Calls checkInfo which assigns values to all class variables
            checkInfo();
            // Displays panels and buttons
            pnlInfoChecklist.setVisible(true);
            btnValidate.setVisible(true);
            btnValidate.setEnabled(true);
            btnReject.setVisible(true);
            btnReject.setEnabled(true);
            btnChange.setVisible(true);
            btnChange.setEnabled(true);
            btnViewPhotos.setVisible(true);
            btnViewPhotos.setEnabled(true);
            // Displays all the class varaibles on the screen
            lblCourse.setText("Course: " + strCourse);
            lblUnitNumber.setText("Unit Number: " + strUnitNum);
            lblTeacher.setText("Teacher: " + strTeacher);
            lblUnitName.setText("Unit Name: " + strUnitName);
            lblAssessment.setText("Assessment Name: " + strAssessment);
        }
    }//GEN-LAST:event_btnReviewActionPerformed

    private void btnValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateActionPerformed
        // Checks if all checkboxes are selected
        if (ckbxAssessment.isSelected() && ckbxCourse.isSelected() && ckbxTeacher.isSelected() && ckbxUnitName.isSelected() && ckbxUnitNum.isSelected()){
            // Tries code and catches error
            try{
                // Instantiates BufferedReader and allows it to read PendingTests
                BufferedReader pendingReader = new BufferedReader(new FileReader("src/testUploadGUI/PendingTests.txt"));
                // Creates 2 array lists that hold the lines in txt files
                ArrayList<String> testList = new ArrayList<>();
                ArrayList<String> pendingTestList = new ArrayList<>();
                String pendLine;
                // Goes through each line in PendingTests and adds it to the pendingTestList
                while((pendLine = pendingReader.readLine()) != null){
                    pendingTestList.add(pendLine);
                }
                // Removes the first value from the pendingTestList
                pendingTestList.remove(0);
                // Closes pendingReader
                pendingReader.close();

                // Instantiates BufferedWriter and lets it write to PendingTests
                BufferedWriter pendingWriter = new BufferedWriter(new FileWriter("src/testUploadGUI/PendingTests.txt"));

                // Writes every row from pendingTestList into the PendingTests
                for (String row: pendingTestList){
                    pendingWriter.write(row + "\n");
                }
                // Closes writer
                pendingWriter.close();

                // Instantiates Buffered Reader than reads Tests.txt
                BufferedReader reader = new BufferedReader(new FileReader("src/pastTestGUI/Tests.txt"));
                String line;
                // Goes through all lines and adds it to the array list
                while((line = reader.readLine()) != null){
                    testList.add(line);
                }
                // Closes reader
                reader.close();

                // Instantiates Buffered Writer
                BufferedWriter writer = new BufferedWriter(new FileWriter("src/pastTestGUI/Tests.txt"));
                // Adds the informations to the testList
                testList.add((strCourse + ": " + strCourse + " Unit " + strUnitNum + " Test " + strUnitName + " " + strAssessment + ":" + strAssessment + ":" + strTeacher + ":" + strPhotoLocations));
                // Uses bubbleSort method to sort testList
                testList = bubbleSort(testList);
                // Writes the sorted arraylist into the txt file
                for (String row: testList){
                    writer.write(row + "\n");
                }
                // Closes Writer
                writer.close();
                // Hides validation screen
                hideValidationScreen();
                // Checks info and updates pendingTests amount
                checkInfo();
                // Catchs IO Exception
            }catch(IOException e){
                e.printStackTrace();
                System.out.println("An error has occured while accessing the file");
            }
        }

    }//GEN-LAST:event_btnValidateActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // Checks if any of the change txt's are filled in, if they are it changes the value of the corresponding varible
        if (!(txtCourseChange.getText().equals(""))){
            strCourse = txtCourseChange.getText();
        }
        if (!(txtUnitNumChange.getText().equals(""))){
            strUnitNum = txtUnitNumChange.getText();
        }
        if (!(txtTeacherChange.getText().equals(""))){
            strTeacher = txtTeacherChange.getText();
        }
        if (!(txtUnitNameChange.getText().equals(""))){
            strUnitName = txtUnitNameChange.getText();
        }
        if (!(txtAssessmentChange.getText().equals(""))){
            strAssessment = txtAssessmentChange.getText();
        }
        // Displays all changes
        lblCourse.setText("Course: " + strCourse);
        lblUnitNumber.setText("Unit Number: " + strUnitNum);
        lblTeacher.setText("Teacher: " + strTeacher);
        lblUnitName.setText("Unit Name: " + strUnitName);
        lblAssessment.setText("Assessment Name: " + strAssessment);
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // Tries code and catches errors
        try{
            // Instantiates BuffereReader
            BufferedReader pendingReader = new BufferedReader(new FileReader("src/testUploadGUI/PendingTests.txt"));

            // Creates arraylists
            ArrayList<String> pendingTestList = new ArrayList<>();
            String pendLine;
            // Goes through the txt file and adds each line to the arraylist
            while((pendLine = pendingReader.readLine()) != null){
                pendingTestList.add(pendLine);
            }
            // Removes first line
            pendingTestList.remove(0);
            // Closes reader
            pendingReader.close();

            // Instantiates writer and writes to PendingTests.txt
            BufferedWriter pendingWriter = new BufferedWriter(new FileWriter("src/testUploadGUI/PendingTests.txt"));
            // Writes each line to the txt file
            for (String row: pendingTestList){
                pendingWriter.write(row + "\n");
            }
            // Closes writer
            pendingWriter.close();
            // Hides validation screen
            hideValidationScreen();
            // Gathers info from next line and displays number of tests pending
            checkInfo();
            // Catchs errors
        }catch(IOException e){
            System.out.println("An error has occured while accessing the file");
        }
    }//GEN-LAST:event_btnRejectActionPerformed

    private void txtUnitNumChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitNumChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitNumChangeActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // Tries code and catches errors
        try{
            // Creates bufferedreader that reads PendingTests
            BufferedReader reader = new BufferedReader(new FileReader("src/testUploadGUI/PendingTests.txt"));
            // Creates string variable line
            String line;
            // Initalizes intPending and sets value to 0
            intPending = 0;
            // Goes through each line and adds 1 to intPending for each line in the txtFile
            while((line = reader.readLine()) != null){
                intPending += 1;
            }
            // Displays the number of lines on the screen
            lblPending.setText("Pending Tests: " + intPending);
            // Closes reader
            reader.close();
            // Catches IOException errors
        }catch(IOException e){
            System.out.println("An error has occured while accessing the file");
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnMyStreakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyStreakActionPerformed
        streakAccountGUI accountGUI = new streakAccountGUI();

        accountGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMyStreakActionPerformed

    private void btnNotepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotepadActionPerformed
        notepadGUI notePad = new notepadGUI();
        
        notePad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNotepadActionPerformed

    private void btnUploadTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadTestActionPerformed
        testUploadGUI testUploadNew = new testUploadGUI();

        testUploadNew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUploadTestActionPerformed

    private void btnQuestionGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuestionGenActionPerformed
        QuestionGenerator qGen = new QuestionGenerator();

        qGen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuestionGenActionPerformed

    private void btnPastTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastTestActionPerformed
        pastTestGUI pastTestGUI = new pastTestGUI();

        pastTestGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPastTestActionPerformed

    private void btnPomoTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPomoTimerActionPerformed
        pomodoroGUI pomoGUI = new pomodoroGUI();

        pomoGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPomoTimerActionPerformed

    // void method
    public void checkInfo(){
        // Tries code and catches errors
        try{
            // Instantiates BufferedReader that reads pending tests
            BufferedReader reader = new BufferedReader(new FileReader("src/testUploadGUI/PendingTests.txt"));
            String line;
            intPending = 0;
            // Reads first line and checks if it is not empty
            if ((line = reader.readLine()) != null){
                String[] arrayParts = line.split(":");
                // Sets each value to the class variables
                strCourse = arrayParts[0];
                strUnitNum = arrayParts[1];
                strTeacher = arrayParts[4];
                strUnitName = arrayParts[2];
                strAssessment = arrayParts[3];
                strPhotoLocations = arrayParts[5];
                // Adds 1 to represent the number of lines
                intPending += 1;
            }
            
            // Reads the rest of the txt file
            while((line = reader.readLine()) != null){
                // Adds 1 to intPending for each line
                intPending += 1;
            }
            // If there are no lines in the pending tests, it sets all class variables to null
            if (intPending == 0){
                strCourse = null;
                strUnitNum = null;
                strTeacher = null;
                strUnitName = null;
                strAssessment = null;
                strPhotoLocations = null;
            }
            // Displays number of tests
            lblPending.setText("Pending Tests: " + intPending);
            // Closes reader
            reader.close();
        // Catches errors
        }catch(IOException e){
            System.out.println("An error has occured while accessing the file");
        }
    }
    
    // BubbleSort method that returns a arraylist
    public ArrayList bubbleSort(ArrayList tests){
        // Sets intLength to the size of the arraylist
        int intLength = tests.size();
        // Initializes boolHasSwapped
        boolean boolHasSwapped;
        
        // For loop that goes through the length of the arraylist
        for(int i = 0; i < intLength - 1; i++){
            // Sets boolHasSwapped to false
            boolHasSwapped = false;
            // For loop that goes the length of the array list
            for(int m = 0; m < intLength - 1; m++){
                // Compares the current index to the next index and swaps them if the current is larger than the next
                if(String.valueOf(tests.get(m+1)).compareTo(String.valueOf(tests.get(m))) < 0){
                    String strTemporary = String.valueOf(tests.get(m+1));
                    tests.set(m+1, tests.get(m));
                    tests.set(m, strTemporary);
                    // Sets has swapped to true
                    boolHasSwapped = true;
                }
            }
            // Breaks the for loops if no swaps are made
            if(!boolHasSwapped){
                break;
            }
        }
        return tests;
    }
    // Hide Validation Screen method that resets GUI elements
    public void hideValidationScreen(){
        ckbxAssessment.setSelected(false);
        ckbxCourse.setSelected(false);
        ckbxUnitNum.setSelected(false);
        ckbxUnitName.setSelected(false);
        ckbxTeacher.setSelected(false);
        pnlInfoChecklist.setVisible(false);
        btnValidate.setVisible(false);
        btnReject.setVisible(false);
        btnChange.setVisible(false);
        txtCourseChange.setText("");
        txtAssessmentChange.setText("");
        txtTeacherChange.setText("");
        txtUnitNameChange.setText("");
        txtUnitNumChange.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new adminApprovalGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnCloseMenu;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMyStreak;
    private javax.swing.JButton btnNotepad;
    private javax.swing.JButton btnOpenMenu;
    private javax.swing.JButton btnPastTest;
    private javax.swing.JButton btnPomoTimer;
    private javax.swing.JButton btnQuestionGen;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnReview;
    private javax.swing.JButton btnStudyTools;
    private javax.swing.JButton btnUploadTest;
    private javax.swing.JButton btnValidate;
    private javax.swing.JButton btnViewPhotos;
    private javax.swing.JCheckBox ckbxAssessment;
    private javax.swing.JCheckBox ckbxCourse;
    private javax.swing.JCheckBox ckbxTeacher;
    private javax.swing.JCheckBox ckbxUnitName;
    private javax.swing.JCheckBox ckbxUnitNum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAssessment;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBackgroundWOMenu;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblPending;
    private javax.swing.JLabel lblTeacher;
    private javax.swing.JLabel lblUnitName;
    private javax.swing.JLabel lblUnitNumber;
    private javax.swing.JPanel pnlInfoChecklist;
    private javax.swing.JTextField txtAssessmentChange;
    private javax.swing.JTextField txtCourseChange;
    private javax.swing.JTextField txtTeacherChange;
    private javax.swing.JTextField txtUnitNameChange;
    private javax.swing.JTextField txtUnitNumChange;
    // End of variables declaration//GEN-END:variables
}
