/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testUploadGUI;
// Imports classes that are used to allow the user to select and choose files
import accountGUI.LoggedOutMainGUI;
import accountGUI.LoginGUI;
import accountGUI.streakAccountGUI;
import accountGUI.accountSettingsGUI;
import javax.swing.JFileChooser;
import java.nio.file.Files;
import java.awt.Image;
import java.nio.file.FileAlreadyExistsException;
// Imports IO used for reading and writing files
import java.io.*;
// Imports arrayList used for storing data
import java.util.ArrayList;
import java.util.Locale;
// Imports image icon used for displaying images on the screen
import javax.swing.ImageIcon;

import pomodoroGUI.*;
import mainGUI.*;
import notepadGUI.*;
import questionGeneratingGUI.*;
import pastTestGUI.*;

/**
 *
 * @author pamlee
 */
public class testUploadGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(testUploadGUI.class.getName());

    public ArrayList<String> photoLocationList = new ArrayList<>();
    /**
     * Creates new form testUploadGUI
     */
    public testUploadGUI() {
        initComponents();
        
        // Displays admin button if the user is an admin
        if(LoginGUI.adminCheck() == true)
        {
            btnAdmin.setEnabled(true);
            btnAdmin.setVisible(true);
        }
        else
        {
            btnAdmin.setEnabled(false);
            btnAdmin.setVisible(false);
        }
        
        // Making all the buttons appear as just text (app aesthetic)
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setFocusPainted(false);
        
        btnAccount.setContentAreaFilled(false);
        btnAccount.setFocusPainted(false);
        
        btnCloseMenu.setContentAreaFilled(false);
        btnCloseMenu.setFocusPainted(false);
        
        btnOpenMenu.setContentAreaFilled(false);
        btnOpenMenu.setFocusPainted(false);
        
        btnStudyTools.setContentAreaFilled(false);
        btnStudyTools.setFocusPainted(false);
        
        btnPomoTimer.setContentAreaFilled(false);
        btnPomoTimer.setFocusPainted(false);
        
        btnPastTest.setContentAreaFilled(false);
        btnPastTest.setFocusPainted(false);
        
        btnQuestionGen.setContentAreaFilled(false);
        btnQuestionGen.setFocusPainted(false);
        
        btnUploadTest.setContentAreaFilled(false);
        btnUploadTest.setFocusPainted(false);
        
        btnNotepad.setContentAreaFilled(false);
        btnNotepad.setFocusPainted(false);
        
        btnMyStreak.setContentAreaFilled(false);
        btnMyStreak.setFocusPainted(false);
        
        btnSubmit.setContentAreaFilled(false);
        btnSubmit.setFocusPainted(false);
        
        btnUploadFile.setContentAreaFilled(false);
        btnUploadFile.setFocusPainted(false);
        
        // Hide the full-page buttons (open menu, extra button only in full-screen)
        btnOpenMenu.setEnabled(false);
        btnOpenMenu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAdmin = new javax.swing.JButton();
        btnUploadFile = new javax.swing.JButton();
        txtAssessmentInput = new javax.swing.JTextField();
        txtTeacherInput = new javax.swing.JTextField();
        txtUnitNameInput = new javax.swing.JTextField();
        txtUnitInput = new javax.swing.JTextField();
        txtCourseInput = new javax.swing.JTextField();
        lblNumPhoto = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblPrompt = new javax.swing.JLabel();
        btnAccount = new javax.swing.JButton();
        btnCloseMenu = new javax.swing.JButton();
        btnMyStreak = new javax.swing.JButton();
        btnNotepad = new javax.swing.JButton();
        btnUploadTest = new javax.swing.JButton();
        btnQuestionGen = new javax.swing.JButton();
        btnPastTest = new javax.swing.JButton();
        btnPomoTimer = new javax.swing.JButton();
        btnStudyTools = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();
        btnOpenMenu = new javax.swing.JButton();
        lblImageDisplay = new javax.swing.JLabel();
        lblBackgroundWOMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        btnAdmin.setBackground(new java.awt.Color(255, 0, 0));
        btnAdmin.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmin.setText("ADMIN HERE");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmin);
        btnAdmin.setBounds(400, 603, 150, 40);

        btnUploadFile.setBackground(new java.awt.Color(255, 117, 31));
        btnUploadFile.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btnUploadFile.setForeground(new java.awt.Color(255, 255, 255));
        btnUploadFile.setText("Upload File");
        btnUploadFile.setBorder(null);
        btnUploadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadFileActionPerformed(evt);
            }
        });
        jPanel1.add(btnUploadFile);
        btnUploadFile.setBounds(490, 195, 230, 50);

        txtAssessmentInput.setMinimumSize(new java.awt.Dimension(160, 22));
        txtAssessmentInput.setPreferredSize(new java.awt.Dimension(160, 22));
        jPanel1.add(txtAssessmentInput);
        txtAssessmentInput.setBounds(840, 580, 360, 50);

        txtTeacherInput.setMinimumSize(new java.awt.Dimension(160, 22));
        txtTeacherInput.setPreferredSize(new java.awt.Dimension(160, 22));
        jPanel1.add(txtTeacherInput);
        txtTeacherInput.setBounds(840, 500, 360, 50);

        txtUnitNameInput.setMinimumSize(new java.awt.Dimension(160, 22));
        txtUnitNameInput.setPreferredSize(new java.awt.Dimension(160, 22));
        jPanel1.add(txtUnitNameInput);
        txtUnitNameInput.setBounds(840, 430, 360, 50);

        txtUnitInput.setMinimumSize(new java.awt.Dimension(160, 22));
        txtUnitInput.setPreferredSize(new java.awt.Dimension(160, 22));
        jPanel1.add(txtUnitInput);
        txtUnitInput.setBounds(840, 350, 360, 50);

        txtCourseInput.setMinimumSize(new java.awt.Dimension(160, 22));
        txtCourseInput.setPreferredSize(new java.awt.Dimension(160, 22));
        jPanel1.add(txtCourseInput);
        txtCourseInput.setBounds(840, 270, 360, 50);

        lblNumPhoto.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        lblNumPhoto.setText("Number Of Photos:");
        jPanel1.add(lblNumPhoto);
        lblNumPhoto.setBounds(490, 250, 230, 15);

        btnSubmit.setBackground(new java.awt.Color(255, 117, 31));
        btnSubmit.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit for Review");
        btnSubmit.setBorder(null);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit);
        btnSubmit.setBounds(740, 653, 170, 40);

        btnClear.setBackground(new java.awt.Color(204, 204, 204));
        btnClear.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setBorder(null);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
        btnClear.setBounds(1140, 650, 60, 40);

        lblPrompt.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        lblPrompt.setForeground(new java.awt.Color(255, 0, 0));
        lblPrompt.setText("<html> Please Upload Each Page, <br> Then Press Submit once <br>  everything is added </html?");
        jPanel1.add(lblPrompt);
        lblPrompt.setBounds(400, 650, 340, 42);

        btnAccount.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnAccount.setForeground(new java.awt.Color(255, 117, 31));
        btnAccount.setText("MANAGE ACCOUNT");
        btnAccount.setBorder(null);
        btnAccount.setBorderPainted(false);
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccount);
        btnAccount.setBounds(970, 20, 280, 50);

        btnCloseMenu.setBackground(new java.awt.Color(255, 117, 31));
        btnCloseMenu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnCloseMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseMenu.setText("CLOSE MENU");
        btnCloseMenu.setBorder(null);
        btnCloseMenu.setBorderPainted(false);
        btnCloseMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnCloseMenu);
        btnCloseMenu.setBounds(130, 110, 140, 30);

        btnMyStreak.setBackground(new java.awt.Color(255, 204, 102));
        btnMyStreak.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnMyStreak.setText("My Streak");
        btnMyStreak.setBorder(null);
        btnMyStreak.setBorderPainted(false);
        btnMyStreak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyStreakActionPerformed(evt);
            }
        });
        jPanel1.add(btnMyStreak);
        btnMyStreak.setBounds(60, 560, 270, 30);

        btnNotepad.setBackground(new java.awt.Color(255, 204, 102));
        btnNotepad.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnNotepad.setText("Notepad");
        btnNotepad.setBorder(null);
        btnNotepad.setBorderPainted(false);
        btnNotepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotepadActionPerformed(evt);
            }
        });
        jPanel1.add(btnNotepad);
        btnNotepad.setBounds(60, 500, 270, 30);

        btnUploadTest.setBackground(new java.awt.Color(255, 204, 102));
        btnUploadTest.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnUploadTest.setForeground(new java.awt.Color(255, 0, 0));
        btnUploadTest.setText("Upload A Test");
        btnUploadTest.setBorder(null);
        btnUploadTest.setBorderPainted(false);
        btnUploadTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadTestActionPerformed(evt);
            }
        });
        jPanel1.add(btnUploadTest);
        btnUploadTest.setBounds(60, 440, 270, 30);

        btnQuestionGen.setBackground(new java.awt.Color(255, 204, 102));
        btnQuestionGen.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnQuestionGen.setText("Question Generator");
        btnQuestionGen.setBorder(null);
        btnQuestionGen.setBorderPainted(false);
        btnQuestionGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuestionGenActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuestionGen);
        btnQuestionGen.setBounds(60, 380, 270, 30);

        btnPastTest.setBackground(new java.awt.Color(255, 204, 51));
        btnPastTest.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnPastTest.setText("Past Student Tests");
        btnPastTest.setBorder(null);
        btnPastTest.setBorderPainted(false);
        btnPastTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastTestActionPerformed(evt);
            }
        });
        jPanel1.add(btnPastTest);
        btnPastTest.setBounds(60, 320, 270, 30);

        btnPomoTimer.setBackground(new java.awt.Color(255, 204, 51));
        btnPomoTimer.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnPomoTimer.setText("Pomodoro Timer");
        btnPomoTimer.setBorder(null);
        btnPomoTimer.setBorderPainted(false);
        btnPomoTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPomoTimerActionPerformed(evt);
            }
        });
        jPanel1.add(btnPomoTimer);
        btnPomoTimer.setBounds(60, 260, 270, 30);

        btnStudyTools.setBackground(new java.awt.Color(255, 153, 0));
        btnStudyTools.setFont(new java.awt.Font("Verdana", 1, 40)); // NOI18N
        btnStudyTools.setForeground(new java.awt.Color(255, 255, 255));
        btnStudyTools.setText("STUDY TOOLS");
        btnStudyTools.setBorder(null);
        btnStudyTools.setBorderPainted(false);
        btnStudyTools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudyToolsActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudyTools);
        btnStudyTools.setBounds(10, 170, 360, 60);

        btnLogOut.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 51, 51));
        btnLogOut.setText("LOG OUT");
        btnLogOut.setBorder(null);
        btnLogOut.setBorderPainted(false);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut);
        btnLogOut.setBounds(100, 620, 180, 30);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Upload test (WITH side menu).png"))); // NOI18N
        lblBackground.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblBackground);
        lblBackground.setBounds(0, 0, 1280, 720);

        btnOpenMenu.setBackground(new java.awt.Color(255, 117, 31));
        btnOpenMenu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnOpenMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnOpenMenu.setText("OPEN MENU");
        btnOpenMenu.setBorder(null);
        btnOpenMenu.setBorderPainted(false);
        btnOpenMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpenMenu);
        btnOpenMenu.setBounds(40, 118, 140, 30);

        lblImageDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblImageDisplay);
        lblImageDisplay.setBounds(850, 272, 290, 350);

        lblBackgroundWOMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Upload test (WITHOUT side menu).png"))); // NOI18N
        lblBackgroundWOMenu.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblBackgroundWOMenu);
        lblBackgroundWOMenu.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        accountSettingsGUI accountGUI = new accountSettingsGUI();
        
        accountGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnCloseMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseMenuActionPerformed
        // disables buttons to show buttons for the open-menu and remove closed-menu buttons; (app aesthetic)
        lblBackground.setEnabled(false);
        lblBackground.setVisible(false);

        btnCloseMenu.setEnabled(false);
        btnCloseMenu.setVisible(false);

        btnStudyTools.setEnabled(false);
        btnStudyTools.setVisible(false);

        btnPomoTimer.setEnabled(false);
        btnPomoTimer.setVisible(false);

        btnPastTest.setEnabled(false);
        btnPastTest.setVisible(false);

        btnQuestionGen.setEnabled(false);
        btnQuestionGen.setVisible(false);

        btnUploadTest.setEnabled(false);
        btnUploadTest.setVisible(false);
        
        btnNotepad.setEnabled(false);
        btnNotepad.setVisible(false);

        btnMyStreak.setEnabled(false);
        btnMyStreak.setVisible(false);

        btnOpenMenu.setEnabled(true);
        btnOpenMenu.setVisible(true);

        // Moving buttons for the open screen menu
        btnLogOut.setLocation(753, 18);
        btnLogOut.setSize(190, 54);
        
        btnUploadFile.setLocation(120, 192);
        btnSubmit.setLocation(540, 653);
        btnAdmin.setLocation(40, 607);
        
        // Moving text fields back in place
        txtCourseInput.setLocation(420, 270);
        txtUnitInput.setLocation(420, 350);
        txtUnitNameInput.setLocation(420, 430);
        txtTeacherInput.setLocation(420, 500);
        txtAssessmentInput.setLocation(420, 580);
        
        lblNumPhoto.setLocation(120, 250);
        lblPrompt.setLocation(40, 650);
        
        // Displaying the image for full screen
        lblImageDisplay.setEnabled(true);
        lblImageDisplay.setVisible(true);
        
    }//GEN-LAST:event_btnCloseMenuActionPerformed

    private void btnStudyToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudyToolsActionPerformed
        // Opens the main menu GUI
        MainGUI mainGUI = new MainGUI();

        mainGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStudyToolsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        LoggedOutMainGUI logOut = new LoggedOutMainGUI();

        logOut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnOpenMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenMenuActionPerformed
        // Re-enables buttons to show buttons for the closed-menu; (app aesthetic)
        lblBackground.setEnabled(true);
        lblBackground.setVisible(true);

        // Hide open menu button again
        btnOpenMenu.setEnabled(false);
        btnOpenMenu.setVisible(false);

        // Show the rest of the buttons again
        btnCloseMenu.setEnabled(true);
        btnCloseMenu.setVisible(true);

        btnStudyTools.setEnabled(true);
        btnStudyTools.setVisible(true);

        btnPomoTimer.setEnabled(true);
        btnPomoTimer.setVisible(true);

        btnPastTest.setEnabled(true);
        btnPastTest.setVisible(true);

        btnQuestionGen.setEnabled(true);
        btnQuestionGen.setVisible(true);

        btnUploadTest.setEnabled(true);
        btnUploadTest.setVisible(true);
        
        btnNotepad.setEnabled(true);
        btnNotepad.setVisible(true);

        btnMyStreak.setEnabled(true);
        btnMyStreak.setVisible(true);

        // Moving buttons back in place
        btnLogOut.setLocation(100, 620);
        btnLogOut.setSize(180, 30);
        
        btnUploadFile.setLocation(490, 195);
        btnSubmit.setLocation(740, 653);
        btnAdmin.setLocation(400, 603);
        
        // Moving text fields back in place
        txtCourseInput.setLocation(840, 270);
        txtUnitInput.setLocation(840, 350);
        txtUnitNameInput.setLocation(840, 430);
        txtTeacherInput.setLocation(840, 500);
        txtAssessmentInput.setLocation(840, 580);
        
        lblNumPhoto.setLocation(490, 250);
        lblPrompt.setLocation(400, 650);
        
        // Disabling the image display for the smaller menu screen
        lblImageDisplay.setEnabled(false);
        lblImageDisplay.setVisible(false);
    }//GEN-LAST:event_btnOpenMenuActionPerformed

    private void btnUploadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadFileActionPerformed
        // Instantiates filechooser
        JFileChooser fileChooser = new JFileChooser();
        // Allows filechooser to access image files, jpg, jpeg, and png
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image files", "jpg","jpeg","png"));
        // Checks if the file the user chose was a valid option
        int intPhoto = fileChooser.showOpenDialog(this);
        if (intPhoto == JFileChooser.APPROVE_OPTION){
            // Tries Code and catches errors
            try{
                // Creates a file varible and sets it to the user selected file
                File file = fileChooser.getSelectedFile();
                // Creates a blank file in the PendingImages folder, and uses the filename of the userinputted photo
                File copyFile = new File("src/PendingImages", file.getName());
                // Adds the path to the blank file to the arraylist
                photoLocationList.add(copyFile.getPath());
                // Copies the user inputted file to the blank file
                Files.copy(file.toPath(), copyFile.toPath());
                // Uses the copied file to create an image icon
                ImageIcon testPhoto = new ImageIcon(copyFile.getPath());
                // Resizes image
                Image resized = testPhoto.getImage().getScaledInstance(290, 350, Image.SCALE_SMOOTH);
                // Sets resized image to the image icon
                testPhoto = new ImageIcon(resized);
                // Displays the user uploaded photo
                lblImageDisplay.setIcon(testPhoto);
                // Tells the user their photo was added and to add all photos before submiting
                lblPrompt.setText("<html>Photo added, keep adding all photos <br> then submit when all pages are added</html>");
                // Displays number of attachments
                lblNumPhoto.setText("Number of Photos: " + photoLocationList.size());
                // Catchs file already exists exception when a file with the same name already exists
            }catch(FileAlreadyExistsException e){
                // Tells user to change their file name
                lblPrompt.setText("<html>A file already exists with the same name, <br>please change your file name</html>");
                // Catchs IO exceptions
            }catch(IOException a){
                // Displays that there was an error
                lblPrompt.setText("Error occured accessing the file");
                a.printStackTrace();
            }
        }else{
            // Displays it was an invalid file type
            lblPrompt.setText("Invalid file type");
        }
    }//GEN-LAST:event_btnUploadFileActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // Tries code and catches errors
        try{
            // Instantiates reader and allows it to read PendingTests.txt
            BufferedReader reader = new BufferedReader(new FileReader("src/testUploadGUI/PendingTests.txt"));
            // Gets user inputs and assigns to variables
            String strCourseName = txtCourseInput.getText();
            String strUnitNumber = txtUnitInput.getText();
            String strTeacher = txtTeacherInput.getText();
            String strUnitName = txtUnitNameInput.getText();
            String strAssessment = txtAssessmentInput.getText();
            // Checks if any of the fields are not filled out
            if (strCourseName.equals("") || strUnitNumber.equals("") || strTeacher.equals("") || strUnitName.equals("") || strAssessment.equals("")){
                // Prompts user to fill out all fields
                lblPrompt.setText("**Please ensure all fields are filled out");
                reader.close();
            }else{
                // instantiates an arraylist
                ArrayList<String> pendingList = new ArrayList<>();
                String line;
                String strPhotoLocations = "";
                // Goes through each line in the photo locations list
                for (String position: photoLocationList){
                    // Checks if it is not the last one in the list
                    if (!(position.equals(photoLocationList.get(photoLocationList.size() - 1)))){
                        // Adds the position plus a comma to strPhotoLocations
                        strPhotoLocations += position + ",";
                    }else{
                        // Adds just the position
                        strPhotoLocations += position;
                    }
                }
                // Reads each line in the txt file and adds it to the arrayList
                while((line = reader.readLine()) != null){
                    pendingList.add(line);
                }
                // Adds the user inputted information into the arraylist
                pendingList.add((strCourseName + ":" + strUnitNumber + ":" + strUnitName + ":" + strAssessment + ":" + strTeacher + ":" + strPhotoLocations));
                // Closes reader
                reader.close();
                // Instantiates a BufferedWriter
                BufferedWriter writer = new BufferedWriter(new FileWriter("src/testUploadGUI/PendingTests.txt"));
                // Writers each line back into the PendingTests.txt along with the new line
                for (String row: pendingList){
                    writer.write(row + "\n");
                }
                // Closes writer
                writer.close();
                // Tells user their test was successfully added
                lblPrompt.setText("Test was successfully added, Submit another?");
            }
            // Clears array list and resets all GUI elements
            photoLocationList.clear();
            txtCourseInput.setText("");
            txtAssessmentInput.setText("");
            txtTeacherInput.setText("");
            txtUnitInput.setText("");
            txtUnitNameInput.setText("");
            lblImageDisplay.setIcon(null);
            lblNumPhoto.setText("Number of Photos:");
            // Catches IOExceptions
        }catch(IOException e){
            // Displays there was an error
            lblPrompt.setText("** An error has occured while accessing the file");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // Clears array list and all fields
        photoLocationList.clear();
        txtCourseInput.setText("");
        txtAssessmentInput.setText("");
        txtTeacherInput.setText("");
        txtUnitInput.setText("");
        txtUnitNameInput.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnMyStreakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyStreakActionPerformed
        streakAccountGUI accountGUI = new streakAccountGUI();

        accountGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMyStreakActionPerformed

    private void btnNotepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotepadActionPerformed
        noteGetterGUI notePad = new noteGetterGUI();
        
        notePad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNotepadActionPerformed

    private void btnUploadTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadTestActionPerformed
        testUploadGUI testUploadNew = new testUploadGUI();

        testUploadNew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUploadTestActionPerformed

    private void btnQuestionGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuestionGenActionPerformed
        QuestionGenerator qGen = new QuestionGenerator();

        qGen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuestionGenActionPerformed

    private void btnPastTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastTestActionPerformed
        pastTestGUI pastTestGUI = new pastTestGUI();

        pastTestGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPastTestActionPerformed

    private void btnPomoTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPomoTimerActionPerformed
        pomodoroGUI pomoGUI = new pomodoroGUI();

        pomoGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPomoTimerActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        adminApprovalGUI adminTests = new adminApprovalGUI();
        
        adminTests.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new testUploadGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCloseMenu;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMyStreak;
    private javax.swing.JButton btnNotepad;
    private javax.swing.JButton btnOpenMenu;
    private javax.swing.JButton btnPastTest;
    private javax.swing.JButton btnPomoTimer;
    private javax.swing.JButton btnQuestionGen;
    private javax.swing.JButton btnStudyTools;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUploadFile;
    private javax.swing.JButton btnUploadTest;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBackgroundWOMenu;
    private javax.swing.JLabel lblImageDisplay;
    private javax.swing.JLabel lblNumPhoto;
    private javax.swing.JLabel lblPrompt;
    private javax.swing.JTextField txtAssessmentInput;
    private javax.swing.JTextField txtCourseInput;
    private javax.swing.JTextField txtTeacherInput;
    private javax.swing.JTextField txtUnitInput;
    private javax.swing.JTextField txtUnitNameInput;
    // End of variables declaration//GEN-END:variables
}
