package bloveShopGUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pamlee
 */
public class MCR3USummarySheets extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MCR3USummarySheets.class.getName());

    // Starting page number
    int pageNum = 1;
    
    /**
     * Creates new form MCR3USummarySheets
     */
    public MCR3USummarySheets() {
        initComponents();
        
        // Since it starts on page 1, it doesn't need to show the previous page button
        btnPrevious.setEnabled(false);
        btnPrevious.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblMCR3U1A = new javax.swing.JLabel();
        lblMCR3U1B = new javax.swing.JLabel();
        lblMCR3U1C = new javax.swing.JLabel();
        lblMCR3U1D = new javax.swing.JLabel();
        lblMCR3U2A = new javax.swing.JLabel();
        lblMCR3U2B = new javax.swing.JLabel();
        lblMCR3U3ABC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        btnBack.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 117, 31));
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 117, 31), 1, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(10, 20, 110, 30);

        btnPrevious.setBackground(new java.awt.Color(255, 117, 31));
        btnPrevious.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnPrevious.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious.setText("PREVIOUS");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrevious);
        btnPrevious.setBounds(10, 663, 120, 30);

        btnNext.setBackground(new java.awt.Color(255, 117, 31));
        btnNext.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("NEXT");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel1.add(btnNext);
        btnNext.setBounds(1168, 663, 90, 30);

        lblMCR3U1A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/MCR3U 1A.png"))); // NOI18N
        lblMCR3U1A.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblMCR3U1A);
        lblMCR3U1A.setBounds(0, 0, 1280, 720);

        lblMCR3U1B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/MCR3U 1B.png"))); // NOI18N
        lblMCR3U1B.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblMCR3U1B);
        lblMCR3U1B.setBounds(0, 0, 1280, 720);

        lblMCR3U1C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/MCR3U 1C.png"))); // NOI18N
        lblMCR3U1C.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblMCR3U1C);
        lblMCR3U1C.setBounds(0, 0, 1280, 720);

        lblMCR3U1D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/MCR3U 1D.png"))); // NOI18N
        lblMCR3U1D.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblMCR3U1D);
        lblMCR3U1D.setBounds(0, 0, 1280, 720);

        lblMCR3U2A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/MCR3U 2A.png"))); // NOI18N
        lblMCR3U2A.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblMCR3U2A);
        lblMCR3U2A.setBounds(0, 0, 1280, 720);

        lblMCR3U2B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/MCR3U 2B.png"))); // NOI18N
        lblMCR3U2B.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblMCR3U2B);
        lblMCR3U2B.setBounds(0, 0, 1280, 720);

        lblMCR3U3ABC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/MCR3U 3ABC.png"))); // NOI18N
        lblMCR3U3ABC.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblMCR3U3ABC);
        lblMCR3U3ABC.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        if(pageNum == 2)
        {
            pageNum -= 1;
            btnNext.setEnabled(true);
            btnNext.setVisible(true);
            
            btnPrevious.setEnabled(false);
            btnPrevious.setVisible(false);
        }
        else
        {
            pageNum -= 1;
            
            btnPrevious.setEnabled(true);
            btnPrevious.setVisible(true);
            
            btnNext.setEnabled(true);
            btnNext.setVisible(true);
        }
        changeBackground(pageNum);
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if(pageNum >= 6)
        {
            pageNum += 1;
            btnNext.setEnabled(false);
            btnNext.setVisible(false);
            
            btnPrevious.setEnabled(true);
            btnPrevious.setVisible(true);
        }
        else
        {
            pageNum += 1;
            btnPrevious.setEnabled(true);
            btnPrevious.setVisible(true);
            
            btnNext.setEnabled(true);
            btnNext.setVisible(true);
        }
        
        changeBackground(pageNum);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        bloveShopGUI shopGUI = new bloveShopGUI();

        shopGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed


    private void changeBackground(int pageNumber)
    {
        switch(pageNumber)
        {
            case 1:
                lblMCR3U1A.setVisible(true);
                lblMCR3U1B.setVisible(false);
                lblMCR3U1C.setVisible(false);
                lblMCR3U1D.setVisible(false);
                lblMCR3U2A.setVisible(false);
                lblMCR3U2B.setVisible(false);
                lblMCR3U3ABC.setVisible(false);
                break;
            case 2:
                lblMCR3U1A.setVisible(false);
                lblMCR3U1B.setVisible(true);
                lblMCR3U1C.setVisible(false);
                lblMCR3U1D.setVisible(false);
                lblMCR3U2A.setVisible(false);
                lblMCR3U2B.setVisible(false);
                lblMCR3U3ABC.setVisible(false);
                break;
            case 3:
                lblMCR3U1A.setVisible(false);
                lblMCR3U1B.setVisible(false);
                lblMCR3U1C.setVisible(true);
                lblMCR3U1D.setVisible(false);
                lblMCR3U2A.setVisible(false);
                lblMCR3U2B.setVisible(false);
                lblMCR3U3ABC.setVisible(false);
                break;
            case 4:
                lblMCR3U1A.setVisible(false);
                lblMCR3U1B.setVisible(false);
                lblMCR3U1C.setVisible(false);
                lblMCR3U1D.setVisible(true);
                lblMCR3U2A.setVisible(false);
                lblMCR3U2B.setVisible(false);
                lblMCR3U3ABC.setVisible(false);
                break;
            case 5:
                lblMCR3U1A.setVisible(false);
                lblMCR3U1B.setVisible(false);
                lblMCR3U1C.setVisible(false);
                lblMCR3U1D.setVisible(false);
                lblMCR3U2A.setVisible(true);
                lblMCR3U2B.setVisible(false);
                lblMCR3U3ABC.setVisible(false);
                break;
            case 6:
                lblMCR3U1A.setVisible(false);
                lblMCR3U1B.setVisible(false);
                lblMCR3U1C.setVisible(false);
                lblMCR3U1D.setVisible(false);
                lblMCR3U2A.setVisible(false);
                lblMCR3U2B.setVisible(true);
                lblMCR3U3ABC.setVisible(false);
                break;
            case 7:
                lblMCR3U1A.setVisible(false);
                lblMCR3U1B.setVisible(false);
                lblMCR3U1C.setVisible(false);
                lblMCR3U1D.setVisible(false);
                lblMCR3U2A.setVisible(false);
                lblMCR3U2B.setVisible(false);
                lblMCR3U3ABC.setVisible(true);
                break;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MCR3USummarySheets().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMCR3U1A;
    private javax.swing.JLabel lblMCR3U1B;
    private javax.swing.JLabel lblMCR3U1C;
    private javax.swing.JLabel lblMCR3U1D;
    private javax.swing.JLabel lblMCR3U2A;
    private javax.swing.JLabel lblMCR3U2B;
    private javax.swing.JLabel lblMCR3U3ABC;
    // End of variables declaration//GEN-END:variables
}
