/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloveShopGUI;

/**
 *
 * @author pamlee
 */
public class MHF4USummarySheets extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MHF4USummarySheets.class.getName());

    int pageNum = 1;
    /**
     * Creates new form MHF4USummarySheets
     */
    public MHF4USummarySheets() {
        initComponents();
        
        // Since it starts on page 1, it doesn't need to show the previous page button
        btnPrevious.setEnabled(false);
        btnPrevious.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblMHF4U3A = new javax.swing.JLabel();
        lblMHF4UCulm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        btnBack.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 117, 31));
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 117, 31), 1, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(10, 20, 110, 30);

        btnPrevious.setBackground(new java.awt.Color(255, 117, 31));
        btnPrevious.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnPrevious.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious.setText("PREVIOUS");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrevious);
        btnPrevious.setBounds(10, 663, 120, 30);

        btnNext.setBackground(new java.awt.Color(255, 117, 31));
        btnNext.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("NEXT");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel1.add(btnNext);
        btnNext.setBounds(1168, 663, 90, 30);

        lblMHF4U3A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/MHF4U 3A.png"))); // NOI18N
        lblMHF4U3A.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblMHF4U3A);
        lblMHF4U3A.setBounds(0, 0, 1280, 720);

        lblMHF4UCulm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/MHF4U Culm.png"))); // NOI18N
        lblMHF4UCulm.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblMHF4UCulm);
        lblMHF4UCulm.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        bloveShopGUI shopGUI = new bloveShopGUI();

        shopGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        if(pageNum == 2)
        {
            pageNum -= 1;
            btnNext.setEnabled(true);
            btnNext.setVisible(true);

            btnPrevious.setEnabled(false);
            btnPrevious.setVisible(false);
        }
        else
        {
            pageNum -= 1;

            btnPrevious.setEnabled(true);
            btnPrevious.setVisible(true);

            btnNext.setEnabled(true);
            btnNext.setVisible(true);
        }
        changeBackground(pageNum);
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if(pageNum == 1)
        {
            pageNum += 1;
            btnNext.setEnabled(false);
            btnNext.setVisible(false);

            btnPrevious.setEnabled(true);
            btnPrevious.setVisible(true);
        }
        else
        {
            pageNum += 1;
            btnPrevious.setEnabled(true);
            btnPrevious.setVisible(true);

            btnNext.setEnabled(true);
            btnNext.setVisible(true);
        }

        changeBackground(pageNum);
    }//GEN-LAST:event_btnNextActionPerformed

    private void changeBackground(int pageNumber)
    {
        switch(pageNumber)
        {
            case 1:
                lblMHF4U3A.setVisible(true);
                lblMHF4UCulm.setVisible(false);
                break;
            case 2:
                lblMHF4U3A.setVisible(false);
                lblMHF4UCulm.setVisible(true);
                break;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MHF4USummarySheets().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMHF4U3A;
    private javax.swing.JLabel lblMHF4UCulm;
    // End of variables declaration//GEN-END:variables
}
