/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package notepadGUI;
import accountGUI.LoggedOutMainGUI;
import mainGUI.*;
import accountGUI.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author pamlee
 */
public class noteGetterGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(noteGetterGUI.class.getName());

    private String currentUsername; /*Stores username of the currently logged-in user*/
    
    public static String username;

    public void loadNotes(){
        DefaultListModel<String> listModel = new DefaultListModel<>(); /*Creates a list model that will hold the note names*/
        
        for (String note : storeNotes.userNotes.get(currentUsername)){ /*For every note name stored in the specific ArrayList associated with the key (username) of the user*/
            listModel.addElement(note); /*It prints out the name of the notes*/
        }
        
        if(listModel.size() == 0)
        {
            lblWarning.setText("No Notes found! Make a new note by clicking 'New Note'.");
        }
        
        notesList.setModel(listModel); /*Update GUI to display current user's notes*/
    }
    
    /**
     * Creates new form noteGetterGUI
     */
    public noteGetterGUI() {
        initComponents();
        
        // Making all the buttons appear as just text (app aesthetic)
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setFocusPainted(false);
        
        btnAccount.setContentAreaFilled(false);
        btnAccount.setFocusPainted(false);
        
        btnNewNote.setContentAreaFilled(false);
        btnNewNote.setFocusPainted(false);
        
        btnPastNotes.setContentAreaFilled(false);
        btnPastNotes.setFocusPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        notesList = new javax.swing.JList<>();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        btnPastNotes = new javax.swing.JButton();
        btnNewNote = new javax.swing.JButton();
        btnAccount = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        lblWarning = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        btnBack1.setBackground(new java.awt.Color(255, 117, 31));
        btnBack1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(255, 255, 255));
        btnBack1.setText("BACK");
        btnBack1.setBorder(null);
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack1);
        btnBack1.setBounds(40, 118, 140, 40);

        jScrollPane1.setViewportView(notesList);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(692, 300, 500, 390);

        txtPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jPanel1.add(txtPassword);
        txtPassword.setBounds(72, 476, 570, 80);

        txtUsername.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jPanel1.add(txtUsername);
        txtUsername.setBounds(72, 300, 570, 80);

        btnPastNotes.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        btnPastNotes.setForeground(new java.awt.Color(255, 117, 31));
        btnPastNotes.setText("GET PAST NOTES");
        btnPastNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastNotesActionPerformed(evt);
            }
        });
        jPanel1.add(btnPastNotes);
        btnPastNotes.setBounds(386, 590, 279, 79);

        btnNewNote.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        btnNewNote.setForeground(new java.awt.Color(255, 117, 31));
        btnNewNote.setText("NEW NOTE");
        btnNewNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewNoteActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewNote);
        btnNewNote.setBounds(75, 590, 279, 79);

        btnAccount.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnAccount.setForeground(new java.awt.Color(255, 117, 31));
        btnAccount.setText("MANAGE ACCOUNT");
        btnAccount.setBorder(null);
        btnAccount.setBorderPainted(false);
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccount);
        btnAccount.setBounds(970, 20, 280, 50);

        btnLogOut.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 0, 0));
        btnLogOut.setText("LOG OUT");
        btnLogOut.setBorder(null);
        btnLogOut.setBorderPainted(false);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut);
        btnLogOut.setBounds(753, 18, 190, 55);

        lblWarning.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblWarning.setForeground(new java.awt.Color(255, 51, 51));
        lblWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblWarning);
        lblWarning.setBounds(265, 185, 750, 30);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Notepad Access.png"))); // NOI18N
        lblBackground.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblBackground);
        lblBackground.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        accountSettingsGUI accountGUI = new accountSettingsGUI();

        accountGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        LoggedOutMainGUI logOut = new LoggedOutMainGUI();

        logOut.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnNewNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewNoteActionPerformed
        if(LoginGUI.adminCheck())
        {
            notepadGUI newNote = new notepadGUI();

            newNote.setVisible(true);
            this.setVisible(false);
        }
        username = txtUsername.getText();
        String password = String.valueOf(txtPassword.getPassword());
        
        // Clears previous warnings
        lblWarning.setText("");
        
        int verification = LoginGUI.verifyLogin(username, password);
        if(verification == 0)
        {
            lblWarning.setText("Invalid login! Please check again.");
        }
        else
        {
            /*Need something overhere to store the logged in user */
        
            storeNotes.userNotes.putIfAbsent(username, new ArrayList<>());

            notepadGUI newNote = new notepadGUI();

            newNote.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnNewNoteActionPerformed

    private void btnPastNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastNotesActionPerformed
        if(LoginGUI.adminCheck())
        {
            lblWarning.setText("Admin detected; No notes stored with admin access.");
            return;
        }
        
        String username = txtUsername.getText(); /*Get the text from the inputed username*/
        String password = String.valueOf(txtPassword.getPassword()); /*Get the text from the inputed password*/
        
        // Clears previous warnings
        lblWarning.setText("");
        
        int verification = LoginGUI.verifyLogin(username, password);
        if(verification == 0)
        {
            lblWarning.setText("Invalid login! Please check again.");
        }
        else
        {
            currentUsername = username; /*If login succeeds, store the username*/
            storeNotes.userNotes.putIfAbsent(username, new ArrayList<>()); /*putIfAbsent is used to add a key-value pair (notes and isername) if the key (username) is not already present.
            Essentially, if the username doesn't have a list of notes associated with them already, a new ArrayList<>() is created.*/
            loadNotes(); /*Gets the list displayed on screen*/
        }
        
    }//GEN-LAST:event_btnPastNotesActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        MainGUI mainMenu = new MainGUI();

        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new noteGetterGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnNewNote;
    private javax.swing.JButton btnPastNotes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JList<String> notesList;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
