/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package notepadGUI;
// Imports to connect to other pages
import accountGUI.LoggedOutMainGUI;
import pomodoroGUI.*;
import mainGUI.*;
import testUploadGUI.*;
import questionGeneratingGUI.*;
import pastTestGUI.*;
import accountGUI.*;

// Actual app component functionality imports
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.*;

/**
 *
 * @author pamlee
 */
public class notepadGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(notepadGUI.class.getName());

    // Base colour for buttons and text
    Color baseOrange = new Color(255,117,31);
    Color basePink = new Color(255,51,153);
    
    // Boolean to check whether or not the menu is opened
    private boolean menuOpened = true;
    /**
     * Creates new form notepadGUI
     */
    public notepadGUI() {
        initComponents();
        
        lblInstructions.setText("Welcome to Notepad! To save notes, click Save! To open notes previously saved, click Open! Save files as .txt!");

        // Making all the buttons appear as just text (app aesthetic)
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setFocusPainted(false);
        
        btnAccount.setContentAreaFilled(false);
        btnAccount.setFocusPainted(false);
        
        btnCloseMenu.setContentAreaFilled(false);
        btnCloseMenu.setFocusPainted(false);
        
        btnOpenMenu.setContentAreaFilled(false);
        btnOpenMenu.setFocusPainted(false);
        
        btnStudyTools.setContentAreaFilled(false);
        btnStudyTools.setFocusPainted(false);
        
        btnPomoTimer.setContentAreaFilled(false);
        btnPomoTimer.setFocusPainted(false);
        
        btnPastTest.setContentAreaFilled(false);
        btnPastTest.setFocusPainted(false);
        
        btnQuestionGen.setContentAreaFilled(false);
        btnQuestionGen.setFocusPainted(false);
        
        btnUploadTest.setContentAreaFilled(false);
        btnUploadTest.setFocusPainted(false);
        
        btnNotepad.setContentAreaFilled(false);
        btnNotepad.setFocusPainted(false);
        
        btnMyStreak.setContentAreaFilled(false);
        btnMyStreak.setFocusPainted(false);
        
        btnSave.setContentAreaFilled(false);
        btnSave.setFocusPainted(false);
        
        btnOpen.setContentAreaFilled(false);
        btnOpen.setFocusPainted(false);
        
        // Hide the full-page buttons (open menu, extra button only in full-screen)
        btnOpenMenu.setEnabled(false);
        btnOpenMenu.setVisible(false);
        
        lblColouredBG.setVisible(false);
        lblColouredBGWOMenu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack2 = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        cmbBackground = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        noteTaker = new javax.swing.JEditorPane();
        lblWarning = new javax.swing.JLabel();
        lblInstructions = new javax.swing.JLabel();
        btnAccount = new javax.swing.JButton();
        btnCloseMenu = new javax.swing.JButton();
        btnMyStreak = new javax.swing.JButton();
        btnNotepad = new javax.swing.JButton();
        btnUploadTest = new javax.swing.JButton();
        btnQuestionGen = new javax.swing.JButton();
        btnPastTest = new javax.swing.JButton();
        btnPomoTimer = new javax.swing.JButton();
        btnStudyTools = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        lblColouredBG = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        btnOpenMenu = new javax.swing.JButton();
        lblColouredBGWOMenu = new javax.swing.JLabel();
        lblBackgroundWOMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        btnBack2.setBackground(new java.awt.Color(255, 117, 31));
        btnBack2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnBack2.setForeground(new java.awt.Color(255, 255, 255));
        btnBack2.setText("BACK");
        btnBack2.setBorder(null);
        btnBack2.setBorderPainted(false);
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack2);
        btnBack2.setBounds(400, 110, 120, 30);

        btnOpen.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        btnOpen.setForeground(new java.awt.Color(255, 117, 31));
        btnOpen.setText("OPEN");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpen);
        btnOpen.setBounds(1000, 609, 198, 80);

        btnSave.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 117, 31));
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);
        btnSave.setBounds(792, 609, 198, 80);

        cmbBackground.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cmbBackground.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Background 1", "Background 2", "Background 3", "Background 4" }));
        cmbBackground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBackgroundActionPerformed(evt);
            }
        });
        jPanel1.add(cmbBackground);
        cmbBackground.setBounds(450, 610, 300, 80);

        noteTaker.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 102), 3));
        jScrollPane2.setViewportView(noteTaker);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(450, 240, 750, 350);

        lblWarning.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblWarning.setForeground(new java.awt.Color(255, 51, 51));
        lblWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblWarning);
        lblWarning.setBounds(450, 100, 750, 20);

        lblInstructions.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInstructions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions.setText("Welcome to Notepad! To save notes, click Save! To open notes previously saved, click Open! Save files as .txt!");
        jPanel1.add(lblInstructions);
        lblInstructions.setBounds(454, 180, 740, 60);

        btnAccount.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnAccount.setForeground(new java.awt.Color(255, 117, 31));
        btnAccount.setText("MANAGE ACCOUNT");
        btnAccount.setBorder(null);
        btnAccount.setBorderPainted(false);
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccount);
        btnAccount.setBounds(970, 20, 280, 50);

        btnCloseMenu.setBackground(new java.awt.Color(255, 117, 31));
        btnCloseMenu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnCloseMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseMenu.setText("CLOSE MENU");
        btnCloseMenu.setBorder(null);
        btnCloseMenu.setBorderPainted(false);
        btnCloseMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnCloseMenu);
        btnCloseMenu.setBounds(130, 110, 140, 30);

        btnMyStreak.setBackground(new java.awt.Color(255, 204, 102));
        btnMyStreak.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnMyStreak.setText("My Streak");
        btnMyStreak.setBorder(null);
        btnMyStreak.setBorderPainted(false);
        btnMyStreak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyStreakActionPerformed(evt);
            }
        });
        jPanel1.add(btnMyStreak);
        btnMyStreak.setBounds(60, 560, 270, 30);

        btnNotepad.setBackground(new java.awt.Color(255, 204, 102));
        btnNotepad.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnNotepad.setForeground(new java.awt.Color(255, 0, 0));
        btnNotepad.setText("Notepad");
        btnNotepad.setBorder(null);
        btnNotepad.setBorderPainted(false);
        btnNotepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotepadActionPerformed(evt);
            }
        });
        jPanel1.add(btnNotepad);
        btnNotepad.setBounds(60, 500, 270, 30);

        btnUploadTest.setBackground(new java.awt.Color(255, 204, 102));
        btnUploadTest.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnUploadTest.setText("Upload A Test");
        btnUploadTest.setBorder(null);
        btnUploadTest.setBorderPainted(false);
        btnUploadTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadTestActionPerformed(evt);
            }
        });
        jPanel1.add(btnUploadTest);
        btnUploadTest.setBounds(60, 440, 270, 30);

        btnQuestionGen.setBackground(new java.awt.Color(255, 204, 102));
        btnQuestionGen.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnQuestionGen.setText("Question Generator");
        btnQuestionGen.setBorder(null);
        btnQuestionGen.setBorderPainted(false);
        btnQuestionGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuestionGenActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuestionGen);
        btnQuestionGen.setBounds(60, 380, 270, 30);

        btnPastTest.setBackground(new java.awt.Color(255, 204, 51));
        btnPastTest.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnPastTest.setText("Past Student Tests");
        btnPastTest.setBorder(null);
        btnPastTest.setBorderPainted(false);
        btnPastTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastTestActionPerformed(evt);
            }
        });
        jPanel1.add(btnPastTest);
        btnPastTest.setBounds(60, 320, 270, 30);

        btnPomoTimer.setBackground(new java.awt.Color(255, 204, 51));
        btnPomoTimer.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnPomoTimer.setText("Pomodoro Timer");
        btnPomoTimer.setBorder(null);
        btnPomoTimer.setBorderPainted(false);
        btnPomoTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPomoTimerActionPerformed(evt);
            }
        });
        jPanel1.add(btnPomoTimer);
        btnPomoTimer.setBounds(60, 260, 270, 30);

        btnStudyTools.setBackground(new java.awt.Color(255, 153, 0));
        btnStudyTools.setFont(new java.awt.Font("Verdana", 1, 40)); // NOI18N
        btnStudyTools.setForeground(new java.awt.Color(255, 255, 255));
        btnStudyTools.setText("STUDY TOOLS");
        btnStudyTools.setBorder(null);
        btnStudyTools.setBorderPainted(false);
        btnStudyTools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudyToolsActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudyTools);
        btnStudyTools.setBounds(10, 170, 360, 60);

        btnLogOut.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 51, 51));
        btnLogOut.setText("LOG OUT");
        btnLogOut.setBorder(null);
        btnLogOut.setBorderPainted(false);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut);
        btnLogOut.setBounds(100, 620, 180, 30);
        jPanel1.add(lblColouredBG);
        lblColouredBG.setBounds(0, 0, 1280, 720);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Notepad (WITH side menu).png"))); // NOI18N
        lblBackground.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblBackground);
        lblBackground.setBounds(0, 0, 1280, 720);

        btnOpenMenu.setBackground(new java.awt.Color(255, 117, 31));
        btnOpenMenu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnOpenMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnOpenMenu.setText("OPEN MENU");
        btnOpenMenu.setBorder(null);
        btnOpenMenu.setBorderPainted(false);
        btnOpenMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpenMenu);
        btnOpenMenu.setBounds(40, 118, 140, 30);
        jPanel1.add(lblColouredBGWOMenu);
        lblColouredBGWOMenu.setBounds(0, 0, 1280, 720);

        lblBackgroundWOMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Notepad (WITHOUT side menu).png"))); // NOI18N
        lblBackgroundWOMenu.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblBackgroundWOMenu);
        lblBackgroundWOMenu.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        accountSettingsGUI accountGUI = new accountSettingsGUI();

        accountGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnCloseMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseMenuActionPerformed
        menuOpened = false;
        lblColouredBG.setVisible(false);
        
        // disables buttons to show buttons for the open-menu and remove closed-menu buttons; (app aesthetic)
        lblBackground.setEnabled(false);
        lblBackground.setVisible(false);

        btnCloseMenu.setEnabled(false);
        btnCloseMenu.setVisible(false);

        btnStudyTools.setEnabled(false);
        btnStudyTools.setVisible(false);

        btnPomoTimer.setEnabled(false);
        btnPomoTimer.setVisible(false);

        btnPastTest.setEnabled(false);
        btnPastTest.setVisible(false);

        btnQuestionGen.setEnabled(false);
        btnQuestionGen.setVisible(false);

        btnUploadTest.setEnabled(false);
        btnUploadTest.setVisible(false);
        
        btnNotepad.setEnabled(false);
        btnNotepad.setVisible(false);

        btnMyStreak.setEnabled(false);
        btnMyStreak.setVisible(false);

        btnOpenMenu.setEnabled(true);
        btnOpenMenu.setVisible(true);

        btnLogOut.setLocation(753, 18);
        btnLogOut.setSize(190, 54);
        
        // Making Jasmita's buttons "dynamic"
        cmbBackground.setLocation(80, 610);
        cmbBackground.setSize(470, 80);
        
        btnSave.setLocation(641, 610);
        btnSave.setSize(270, 79);
        
        btnOpen.setLocation(927, 610);
        btnOpen.setSize(270, 79);
        
        lblInstructions.setText("Welcome to Notepad! To save notes, click Save! To open notes previously saved, click Open! Save files as .txt!");
        lblInstructions.setLocation(164, 190);
        lblInstructions.setSize(960, 20);
        
        lblWarning.setLocation(250, 215);
        lblWarning.setSize(810, 20);
        
        jScrollPane2.setLocation(80, 240);
        jScrollPane2.setSize(1120, 350);
        
        String selectedBackground = cmbBackground.getSelectedItem().toString(); /*Get selected background from the combo box*/

        // If the menu is closed (false), show the new colour for the fullscreen
        // Otherwise, show a new version of the screen WITH the side menu
        if (selectedBackground.equals("Background 1"))
        {
            lblColouredBGWOMenu.setVisible(false);
            lblColouredBG.setVisible(false);
            
            btnSave.setForeground(baseOrange);
            btnOpen.setForeground(baseOrange);
        } 
        else if (selectedBackground.equals("Background 2"))
        {
            lblColouredBGWOMenu.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Green Notepad (WITHOUT side menu).png"));
            lblColouredBGWOMenu.setVisible(true);
            
            btnSave.setForeground(Color.GREEN);
            btnOpen.setForeground(Color.GREEN);
        } 
        else if (selectedBackground.equals("Background 3"))
        {
            lblColouredBGWOMenu.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Pink Notepad (WITHOUT side menu).png"));
            lblColouredBGWOMenu.setVisible(true);
            
            btnSave.setForeground(basePink);
            btnOpen.setForeground(basePink);
        } 
        else if (selectedBackground.equals("Background 4"))
        {
            /*ImageIcon is used to change the JLabel icon (i.e. background). It is change dependent on what option is choosen*/
            lblColouredBGWOMenu.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Blue Notepad (WITHOUT side menu).png"));
            lblColouredBGWOMenu.setVisible(true);
            
            btnSave.setForeground(Color.BLUE);
            btnOpen.setForeground(Color.BLUE);
        }
        
        btnBack2.setLocation(40, 160);
    }//GEN-LAST:event_btnCloseMenuActionPerformed

    private void btnMyStreakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyStreakActionPerformed
        streakAccountGUI accountGUI = new streakAccountGUI();

        accountGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMyStreakActionPerformed

    private void btnNotepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotepadActionPerformed
        notepadGUI notePad = new notepadGUI();
        
        notePad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNotepadActionPerformed

    private void btnUploadTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadTestActionPerformed
        testUploadGUI testUploadNew = new testUploadGUI();

        testUploadNew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUploadTestActionPerformed

    private void btnQuestionGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuestionGenActionPerformed
        QuestionGenerator qGen = new QuestionGenerator();

        qGen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuestionGenActionPerformed

    private void btnPastTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastTestActionPerformed
        pastTestGUI pastTestGUI = new pastTestGUI();

        pastTestGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPastTestActionPerformed

    private void btnPomoTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPomoTimerActionPerformed
        pomodoroGUI pomoGUI = new pomodoroGUI();

        pomoGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPomoTimerActionPerformed

    private void btnStudyToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudyToolsActionPerformed
        // Opens the main menu GUI
        MainGUI mainGUI = new MainGUI();

        mainGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStudyToolsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        LoggedOutMainGUI logOut = new LoggedOutMainGUI();

        logOut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnOpenMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenMenuActionPerformed
        menuOpened = true;

        // Re-enables buttons to show buttons for the closed-menu; (app aesthetic)
        lblBackground.setEnabled(true);
        lblBackground.setVisible(true);

        // Hide open menu button again
        btnOpenMenu.setEnabled(false);
        btnOpenMenu.setVisible(false);

        // Show the rest of the buttons again
        btnCloseMenu.setEnabled(true);
        btnCloseMenu.setVisible(true);

        btnStudyTools.setEnabled(true);
        btnStudyTools.setVisible(true);

        btnPomoTimer.setEnabled(true);
        btnPomoTimer.setVisible(true);

        btnPastTest.setEnabled(true);
        btnPastTest.setVisible(true);

        btnQuestionGen.setEnabled(true);
        btnQuestionGen.setVisible(true);

        btnUploadTest.setEnabled(true);
        btnUploadTest.setVisible(true);
        
        btnNotepad.setEnabled(true);
        btnNotepad.setVisible(true);

        btnMyStreak.setEnabled(true);
        btnMyStreak.setVisible(true);

        btnLogOut.setLocation(100, 620);
        btnLogOut.setSize(180, 30);
        
        // Making Jasmita's buttons "dynamic"
        cmbBackground.setLocation(450, 610);
        cmbBackground.setSize(300, 80);
        
        btnSave.setLocation(792, 609);
        btnSave.setSize(198, 80);
        
        btnOpen.setLocation(1000, 609);
        btnOpen.setSize(198, 80);
        
        lblInstructions.setText("<html>Welcome to Notepad! To save notes, click Save! To open notes previously saved, <br> click Open! Save files as .txt!</html>");
        lblInstructions.setLocation(454, 180);
        lblInstructions.setSize(740, 60);
        
        lblWarning.setLocation(450, 100);
        lblWarning.setSize(750, 20);
        
        jScrollPane2.setLocation(450, 240);
        jScrollPane2.setSize(750, 350);
        
        String selectedBackground = cmbBackground.getSelectedItem().toString(); /*Get selected background from the combo box*/

        // If the menu is closed (false), show the new colour for the fullscreen
        // Otherwise, show a new version of the screen WITH the side menu
        if (selectedBackground.equals("Background 1"))
        {
            lblColouredBGWOMenu.setVisible(false);
            lblColouredBG.setVisible(false);
            
            btnSave.setForeground(baseOrange);
            btnOpen.setForeground(baseOrange);
        } 
        else if (selectedBackground.equals("Background 2"))
        {
            lblColouredBG.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Green Notepad (WITH side menu).png"));
            lblColouredBG.setVisible(true);
            
            btnSave.setForeground(Color.GREEN);
            btnOpen.setForeground(Color.GREEN);
        } 
        else if (selectedBackground.equals("Background 3"))
        {
            lblColouredBG.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Pink Notepad (WITH side menu).png"));
            lblColouredBG.setVisible(true);
            
            btnSave.setForeground(basePink);
            btnOpen.setForeground(basePink);
        } 
        else if (selectedBackground.equals("Background 4"))
        {
            lblColouredBG.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Blue Notepad (WITH side menu).png"));
            lblColouredBG.setVisible(true);
            
            btnSave.setForeground(Color.BLUE);
            btnOpen.setForeground(Color.BLUE);
        }
        
        btnBack2.setLocation(400, 110);
    }//GEN-LAST:event_btnOpenMenuActionPerformed

    private void cmbBackgroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBackgroundActionPerformed
        String selectedBackground = cmbBackground.getSelectedItem().toString(); /*Get selected background from the combo box*/

        // If the menu is closed (false), show the new colour for the fullscreen
        // Otherwise, show a new version of the screen WITH the side menu
        if (selectedBackground.equals("Background 1"))
        {
            lblColouredBGWOMenu.setVisible(false);
            lblColouredBG.setVisible(false);
            
            // Set the colour back to orange
            btnSave.setForeground(baseOrange);
            btnOpen.setForeground(baseOrange);
        } 
        else if (selectedBackground.equals("Background 2"))
        {
            if(menuOpened == false)
            {
                lblColouredBGWOMenu.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Green Notepad (WITHOUT side menu).png"));
                lblColouredBGWOMenu.setVisible(true);
                lblColouredBG.setVisible(false);
            }
            else
            {
                lblColouredBG.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Green Notepad (WITH side menu).png"));
                lblColouredBG.setVisible(true);
            }
            
            btnSave.setForeground(Color.GREEN);
            btnOpen.setForeground(Color.GREEN);
        } 
        else if (selectedBackground.equals("Background 3"))
        {
            if(menuOpened == false)
            {
                lblColouredBGWOMenu.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Pink Notepad (WITHOUT side menu).png"));
                lblColouredBGWOMenu.setVisible(true);
                lblColouredBG.setVisible(false);
            }
            else
            {
                lblColouredBG.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Pink Notepad (WITH side menu).png"));
                lblColouredBG.setVisible(true);
            }
            
            btnSave.setForeground(basePink);
            btnOpen.setForeground(basePink);
        } 
        // For the base background, turn the coloured components' visibility off
        else if (selectedBackground.equals("Background 4"))
        {
            if(menuOpened == false)
            {
                /*ImageIcon is used to change the JLabel icon (i.e. background). It is change dependent on what option is choosen*/
                lblColouredBGWOMenu.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Blue Notepad (WITHOUT side menu).png"));
                lblColouredBGWOMenu.setVisible(true);
                lblColouredBG.setVisible(false);
            }
            else
            {
                /*ImageIcon is used to change the JLabel icon (i.e. background). It is change dependent on what option is choosen*/
                lblColouredBG.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Blue Notepad (WITH side menu).png"));
                lblColouredBG.setVisible(true);
            }
            
            btnSave.setForeground(Color.BLUE);
            btnOpen.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_cmbBackgroundActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        JFileChooser fileSave = new JFileChooser(); /*Creates file chooser pop-up for saving a file. jFileChooser provides a pop-up allowing users to choose where they want to save a file*/
        fileSave.setDialogTitle("Save your Notes!"); /*This names the pop-up*/
        
        FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("Text Files (.txt)", "txt"); /*File filter ensures that only .txt files can be saved*/
        fileSave.setFileFilter(fileFilter);
        
        int userChoice = fileSave.showSaveDialog(this); /*This shows the save pop-up and stores the users choice*/
        
        if (userChoice == JFileChooser.APPROVE_OPTION){ /*Approve Option means they clicked save*/
            File file = fileSave.getSelectedFile(); /*They get the file the user selected (within the laptop's internal directory)*/
            
            try(BufferedWriter writer = new BufferedWriter(new FileWriter(file)))
            {
                writer.write(noteTaker.getText()); /*Writes the contents of everything written within the window*/
                lblWarning.setText("Saved!"); /*Clears any previous warning messages*/
                
                if(LoginGUI.adminCheck())
                {
                    lblWarning.setText("Admin detected; Notes will only save locally, not connected to a username.");
                    return;
                }
                String noteName = file.getName();
                storeNotes.userNotes.putIfAbsent(noteGetterGUI.username, new ArrayList<>());
                storeNotes.userNotes.get(noteGetterGUI.username).add(noteName);
                
            } catch (IOException e)
            {
                e.printStackTrace();/* Printing the error so we can fix it */
                lblWarning.setText("Error Saving Text!");
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        JFileChooser fileOpen = new JFileChooser(); /*Open the file chooser pop-up*/
          fileOpen.setDialogTitle("Open the Notes!"); /*Name it open the notes!*/
          
          FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("Text Files (.txt)", "txt"); /*Only shows .txt files*/
          fileOpen.setFileFilter(fileFilter);
          
          int userChoice = fileOpen.showOpenDialog(this); /*Shows the pop-up and stores the user's choice*/
          
          if (userChoice == JFileChooser.APPROVE_OPTION){ /*If they click open*/
              File file = fileOpen.getSelectedFile();/*They get the selected file*/
              
              try (BufferedReader reader = new BufferedReader(new FileReader(file))){
                  noteTaker.setText(""); /*Clears the noteTaker text box before anything is added*/
                  String line;
                  
                  while((line = reader.readLine()) != null){ /*Reads the file line by line*/
                      noteTaker.setText(noteTaker.getText() + line + "\n"); /*Appends those line within the text box*/
                  }
                  
                  lblWarning.setText(""); /*Clears previous warning labels*/
                  
              } catch (IOException e){
                  lblWarning.setText("Error Opening File");
              }
          }
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        noteGetterGUI noteGetter = new noteGetterGUI();
        
        noteGetter.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new notepadGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnCloseMenu;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMyStreak;
    private javax.swing.JButton btnNotepad;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnOpenMenu;
    private javax.swing.JButton btnPastTest;
    private javax.swing.JButton btnPomoTimer;
    private javax.swing.JButton btnQuestionGen;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnStudyTools;
    private javax.swing.JButton btnUploadTest;
    private javax.swing.JComboBox<String> cmbBackground;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBackgroundWOMenu;
    private javax.swing.JLabel lblColouredBG;
    private javax.swing.JLabel lblColouredBGWOMenu;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JEditorPane noteTaker;
    // End of variables declaration//GEN-END:variables
}
