/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package questionGeneratingGUI;

// Importing the other GUI: MainGUI, Logged-Out MainGUI
import accountGUI.LoggedOutMainGUI;
import accountGUI.accountSettingsGUI;
import accountGUI.streakAccountGUI;
import pomodoroGUI.*;
import mainGUI.*;
import notepadGUI.*;
import testUploadGUI.*;
import pastTestGUI.*;

/**
 *
 * @author pamlee
 */
public class QuestionGenerator extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuestionGenerator.class.getName());

    // Public static variables; CourseCode and CourseUnit
    // Accessable in the QuestionGeneratorGUI (Using getter method)
    
    public static String courseCode = "";
    public static int courseUnit = 0;
    
    /**
     * Creates new form QuestionGenerator
     */
    public QuestionGenerator() {
        initComponents();
        
        // Making all the buttons appear as just text
        btnStart.setContentAreaFilled(false);
        btnStart.setFocusPainted(false);
        
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setFocusPainted(false);
        
        btnAccount.setContentAreaFilled(false);
        btnAccount.setFocusPainted(false);
        
        btnCloseMenu.setContentAreaFilled(false);
        btnCloseMenu.setFocusPainted(false);
        
        btnOpenMenu.setContentAreaFilled(false);
        btnOpenMenu.setFocusPainted(false);
        
        btnStudyTools.setContentAreaFilled(false);
        btnStudyTools.setFocusPainted(false);
        
        btnPomoTimer.setContentAreaFilled(false);
        btnPomoTimer.setFocusPainted(false);
        
        btnPastTest.setContentAreaFilled(false);
        btnPastTest.setFocusPainted(false);
        
        btnQuestionGen.setContentAreaFilled(false);
        btnQuestionGen.setFocusPainted(false);
        
        btnUploadTest.setContentAreaFilled(false);
        btnUploadTest.setFocusPainted(false);
        
        btnNotepad.setContentAreaFilled(false);
        btnNotepad.setFocusPainted(false);
        
        btnMyStreak.setContentAreaFilled(false);
        btnMyStreak.setFocusPainted(false);
        
        // Hiding the "open menu" button
        btnOpenMenu.setEnabled(false);
        btnOpenMenu.setVisible(false);
        
        // Ensures that button locations start in the right spots
        // Changing the font size back to normal (just in-case)
        var startFont = btnStart.getFont();
        btnStart.setLocation(699, 488);
        btnStart.setFont(startFont.deriveFont(36f));
        btnStart.setSize(299, 75);
        
        jcbCourseCode.setLocation(880, 300);
        jcbCourseCode.setSize(290, 70);
        
        jcbUnit.setLocation(880, 390);
        jcbUnit.setSize(290, 70);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcbUnit = new javax.swing.JComboBox<>();
        jcbCourseCode = new javax.swing.JComboBox<>();
        btnStart = new javax.swing.JButton();
        btnAccount = new javax.swing.JButton();
        btnCloseMenu = new javax.swing.JButton();
        btnMyStreak = new javax.swing.JButton();
        btnNotepad = new javax.swing.JButton();
        btnUploadTest = new javax.swing.JButton();
        btnQuestionGen = new javax.swing.JButton();
        btnPastTest = new javax.swing.JButton();
        btnPomoTimer = new javax.swing.JButton();
        btnStudyTools = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();
        btnOpenMenu = new javax.swing.JButton();
        lblBackgroundWOMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        jcbUnit.setFont(new java.awt.Font("LiHei Pro", 0, 30)); // NOI18N
        jcbUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jPanel1.add(jcbUnit);
        jcbUnit.setBounds(880, 390, 290, 70);

        jcbCourseCode.setFont(new java.awt.Font("LiHei Pro", 0, 24)); // NOI18N
        jcbCourseCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MCR3U", "MHF4U", "SCH3U", "SPH3U", "SPH4U" }));
        jcbCourseCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCourseCodeActionPerformed(evt);
            }
        });
        jPanel1.add(jcbCourseCode);
        jcbCourseCode.setBounds(880, 300, 290, 70);

        btnStart.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 117, 31));
        btnStart.setText("START");
        btnStart.setBorder(null);
        btnStart.setBorderPainted(false);
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel1.add(btnStart);
        btnStart.setBounds(699, 488, 299, 75);

        btnAccount.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnAccount.setForeground(new java.awt.Color(255, 117, 31));
        btnAccount.setText("MANAGE ACCOUNT");
        btnAccount.setBorder(null);
        btnAccount.setBorderPainted(false);
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccount);
        btnAccount.setBounds(970, 20, 280, 50);

        btnCloseMenu.setBackground(new java.awt.Color(255, 117, 31));
        btnCloseMenu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnCloseMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseMenu.setText("CLOSE MENU");
        btnCloseMenu.setBorder(null);
        btnCloseMenu.setBorderPainted(false);
        btnCloseMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnCloseMenu);
        btnCloseMenu.setBounds(130, 110, 140, 30);

        btnMyStreak.setBackground(new java.awt.Color(255, 204, 102));
        btnMyStreak.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnMyStreak.setText("My Streak");
        btnMyStreak.setBorder(null);
        btnMyStreak.setBorderPainted(false);
        btnMyStreak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyStreakActionPerformed(evt);
            }
        });
        jPanel1.add(btnMyStreak);
        btnMyStreak.setBounds(60, 560, 270, 30);

        btnNotepad.setBackground(new java.awt.Color(255, 204, 102));
        btnNotepad.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnNotepad.setText("Notepad");
        btnNotepad.setBorder(null);
        btnNotepad.setBorderPainted(false);
        btnNotepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotepadActionPerformed(evt);
            }
        });
        jPanel1.add(btnNotepad);
        btnNotepad.setBounds(60, 500, 270, 30);

        btnUploadTest.setBackground(new java.awt.Color(255, 204, 102));
        btnUploadTest.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnUploadTest.setText("Upload A Test");
        btnUploadTest.setBorder(null);
        btnUploadTest.setBorderPainted(false);
        btnUploadTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadTestActionPerformed(evt);
            }
        });
        jPanel1.add(btnUploadTest);
        btnUploadTest.setBounds(60, 440, 270, 30);

        btnQuestionGen.setBackground(new java.awt.Color(255, 204, 102));
        btnQuestionGen.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnQuestionGen.setForeground(new java.awt.Color(255, 0, 0));
        btnQuestionGen.setText("Question Generator");
        btnQuestionGen.setBorder(null);
        btnQuestionGen.setBorderPainted(false);
        btnQuestionGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuestionGenActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuestionGen);
        btnQuestionGen.setBounds(60, 380, 270, 30);

        btnPastTest.setBackground(new java.awt.Color(255, 204, 51));
        btnPastTest.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnPastTest.setText("Past Student Tests");
        btnPastTest.setBorder(null);
        btnPastTest.setBorderPainted(false);
        btnPastTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastTestActionPerformed(evt);
            }
        });
        jPanel1.add(btnPastTest);
        btnPastTest.setBounds(60, 320, 270, 30);

        btnPomoTimer.setBackground(new java.awt.Color(255, 204, 51));
        btnPomoTimer.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnPomoTimer.setText("Pomodoro Timer");
        btnPomoTimer.setBorder(null);
        btnPomoTimer.setBorderPainted(false);
        btnPomoTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPomoTimerActionPerformed(evt);
            }
        });
        jPanel1.add(btnPomoTimer);
        btnPomoTimer.setBounds(60, 260, 270, 30);

        btnStudyTools.setBackground(new java.awt.Color(255, 153, 0));
        btnStudyTools.setFont(new java.awt.Font("Verdana", 1, 40)); // NOI18N
        btnStudyTools.setForeground(new java.awt.Color(255, 255, 255));
        btnStudyTools.setText("STUDY TOOLS");
        btnStudyTools.setBorder(null);
        btnStudyTools.setBorderPainted(false);
        btnStudyTools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudyToolsActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudyTools);
        btnStudyTools.setBounds(10, 170, 360, 60);

        btnLogOut.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 51, 51));
        btnLogOut.setText("LOG OUT");
        btnLogOut.setBorder(null);
        btnLogOut.setBorderPainted(false);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut);
        btnLogOut.setBounds(100, 620, 180, 30);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Question Gen w menu.png"))); // NOI18N
        lblBackground.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblBackground);
        lblBackground.setBounds(0, 0, 1280, 720);

        btnOpenMenu.setBackground(new java.awt.Color(255, 117, 31));
        btnOpenMenu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnOpenMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnOpenMenu.setText("OPEN MENU");
        btnOpenMenu.setBorder(null);
        btnOpenMenu.setBorderPainted(false);
        btnOpenMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpenMenu);
        btnOpenMenu.setBounds(40, 118, 140, 30);

        lblBackgroundWOMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Question Gen wo menu.png"))); // NOI18N
        lblBackgroundWOMenu.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblBackgroundWOMenu);
        lblBackgroundWOMenu.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        courseCode = jcbCourseCode.getSelectedItem().toString();
        courseUnit = Integer.parseInt(jcbUnit.getSelectedItem().toString());
        
        QuestionGeneratorGUI questionGUI = new QuestionGeneratorGUI();
        
        questionGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        LoggedOutMainGUI logOut = new LoggedOutMainGUI();
        
        logOut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnCloseMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseMenuActionPerformed
        // disables buttons to show buttons for the open-menu and remove closed-menu buttons; (app aesthetic)
        lblBackground.setEnabled(false);
        lblBackground.setVisible(false);
        
        btnCloseMenu.setEnabled(false);
        btnCloseMenu.setVisible(false);
        
        btnStudyTools.setEnabled(false);
        btnStudyTools.setVisible(false);
        
        btnPomoTimer.setEnabled(false);
        btnPomoTimer.setVisible(false);
        
        btnPastTest.setEnabled(false);
        btnPastTest.setVisible(false);
        
        btnQuestionGen.setEnabled(false);
        btnQuestionGen.setVisible(false);
        
        btnUploadTest.setEnabled(false);
        btnUploadTest.setVisible(false);
        
        btnNotepad.setEnabled(false);
        btnNotepad.setVisible(false);
        
        btnMyStreak.setEnabled(false);
        btnMyStreak.setVisible(false);
        
        btnOpenMenu.setEnabled(true);
        btnOpenMenu.setVisible(true);
        
        // Move some buttons back in place
        var startFont = btnStart.getFont();
        btnStart.setLocation(460, 539);
        btnStart.setFont(startFont.deriveFont(40f));
        btnStart.setSize(360, 90);
        
        btnLogOut.setLocation(753, 18);
        btnLogOut.setSize(190, 54);
        
        jcbCourseCode.setLocation(670, 320);
        jcbCourseCode.setSize(290, 70);
        
        jcbUnit.setLocation(670, 410);
        jcbUnit.setSize(290, 70);
    }//GEN-LAST:event_btnCloseMenuActionPerformed

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        accountSettingsGUI accountGUI = new accountSettingsGUI();
        
        accountGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnStudyToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudyToolsActionPerformed
        // Opens the main menu GUI
        MainGUI mainGUI = new MainGUI();
        
        mainGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStudyToolsActionPerformed

    private void btnOpenMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenMenuActionPerformed
        // Re-enables buttons to show buttons for the closed-menu; (app aesthetic)
        lblBackground.setEnabled(true);
        lblBackground.setVisible(true);
        
        // Hide open menu button again
        btnOpenMenu.setEnabled(false);
        btnOpenMenu.setVisible(false);
        
        // Show the rest of the buttons again
        btnCloseMenu.setEnabled(true);
        btnCloseMenu.setVisible(true);
        
        btnStudyTools.setEnabled(true);
        btnStudyTools.setVisible(true);
        
        btnPomoTimer.setEnabled(true);
        btnPomoTimer.setVisible(true);
        
        btnPastTest.setEnabled(true);
        btnPastTest.setVisible(true);
        
        btnQuestionGen.setEnabled(true);
        btnQuestionGen.setVisible(true);
        
        btnUploadTest.setEnabled(true);
        btnUploadTest.setVisible(true);
        
        btnNotepad.setEnabled(true);
        btnNotepad.setVisible(true);
        
        btnMyStreak.setEnabled(true);
        btnMyStreak.setVisible(true);
        
        // Move some buttons back in place
        var startFont = btnStart.getFont();
        btnStart.setLocation(699, 488);
        btnStart.setFont(startFont.deriveFont(36f));
        btnStart.setSize(299, 75);
        
        btnLogOut.setLocation(100, 620);
        btnLogOut.setSize(180, 30);
        
        jcbCourseCode.setLocation(880, 300);
        jcbCourseCode.setSize(290, 70);
        
        jcbUnit.setLocation(880, 390);
        jcbUnit.setSize(290, 70);
    }//GEN-LAST:event_btnOpenMenuActionPerformed

    private void jcbCourseCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCourseCodeActionPerformed
        // Researched --> Displays certain units based on the course selected
        String units = (String) jcbCourseCode.getSelectedItem();

        jcbUnit.removeAllItems();

        // Add the units based on the course
        switch(units) 
        {
            // Maths only have 3 - 4 units
            case "MCR3U":
                jcbUnit.addItem("1");
                jcbUnit.addItem("2");
                jcbUnit.addItem("3");
                break;
            case "MHF4U":
                jcbUnit.addItem("1");
                jcbUnit.addItem("2");
                jcbUnit.addItem("3");
//                jcbUnit.addItem("4");
                break;
                
            // Sciences have 5
            case "SCH3U":
                jcbUnit.addItem("1");
                jcbUnit.addItem("2");
                jcbUnit.addItem("3");
                jcbUnit.addItem("4");
                jcbUnit.addItem("5");
                break;
            case "SPH3U":
                jcbUnit.addItem("1");
                jcbUnit.addItem("2");
                jcbUnit.addItem("3");
                jcbUnit.addItem("4");
                jcbUnit.addItem("5");
                break;
            case "SPH4U":
                jcbUnit.addItem("1");
                jcbUnit.addItem("2");
                jcbUnit.addItem("3");
                jcbUnit.addItem("4");
//                jcbUnit.addItem("5");
                break;
            default:
                jcbUnit.addItem("Select A Unit");
                break;
        }
    }//GEN-LAST:event_jcbCourseCodeActionPerformed

    private void btnMyStreakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyStreakActionPerformed
        streakAccountGUI accountGUI = new streakAccountGUI();

        accountGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMyStreakActionPerformed

    private void btnNotepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotepadActionPerformed
        noteGetterGUI notePad = new noteGetterGUI();
        
        notePad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNotepadActionPerformed

    private void btnUploadTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadTestActionPerformed
        testUploadGUI testUploadNew = new testUploadGUI();

        testUploadNew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUploadTestActionPerformed

    private void btnQuestionGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuestionGenActionPerformed
        QuestionGenerator qGen = new QuestionGenerator();

        qGen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuestionGenActionPerformed

    private void btnPastTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastTestActionPerformed
        pastTestGUI pastTestGUI = new pastTestGUI();

        pastTestGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPastTestActionPerformed

    private void btnPomoTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPomoTimerActionPerformed
        pomodoroGUI pomoGUI = new pomodoroGUI();

        pomoGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPomoTimerActionPerformed

    // OOP - Encapsulation; Getter methods for courseCode and unit for the generator file
    public static String getCourseCode()
    {
        return courseCode;
    }
    
    public static int getCourseUnit()
    {
        return courseUnit;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QuestionGenerator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnCloseMenu;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMyStreak;
    private javax.swing.JButton btnNotepad;
    private javax.swing.JButton btnOpenMenu;
    private javax.swing.JButton btnPastTest;
    private javax.swing.JButton btnPomoTimer;
    private javax.swing.JButton btnQuestionGen;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStudyTools;
    private javax.swing.JButton btnUploadTest;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbCourseCode;
    private javax.swing.JComboBox<String> jcbUnit;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBackgroundWOMenu;
    // End of variables declaration//GEN-END:variables
}
