/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package accountGUI;
import pomodoroGUI.*;
import mainGUI.*;
import testUploadGUI.*;
import questionGeneratingGUI.*;
import pastTestGUI.*;
import bloveShopGUI.*;

/**
 *
 * @author pamlee
 */
public class accountSettingsGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(accountSettingsGUI.class.getName());

    /**
     * Creates new form accountSettingsGUI
     */
    public accountSettingsGUI() {
        initComponents();
        
        // Making all the buttons appear as just text (app aesthetic)
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setFocusPainted(false);
        
        btnStreak.setContentAreaFilled(false);
        btnStreak.setFocusPainted(false);
        
        btnBack.setContentAreaFilled(false);
        btnBack.setFocusPainted(false);
        
        btnChangeUser.setContentAreaFilled(false);
        btnChangeUser.setFocusPainted(false);
        
        btnChangePassword.setContentAreaFilled(false);
        btnChangePassword.setFocusPainted(false);
        
        // For changing username panel; hiding it when the app just opens
        pnlUsernameChange.setEnabled(false);
        pnlUsernameChange.setVisible(false);
        
        btnLogOut1.setContentAreaFilled(false);
        btnLogOut1.setFocusPainted(false);
        
        btnStreak1.setContentAreaFilled(false);
        btnStreak1.setFocusPainted(false);
        
        btnBack1.setContentAreaFilled(false);
        btnBack1.setFocusPainted(false);
        
        btnChange.setContentAreaFilled(false);
        btnChange.setFocusPainted(false);
        
        // For changing password panel; hiding it when the app just opens
        pnlPasswordChange.setEnabled(false);
        pnlPasswordChange.setVisible(false);
        
        btnLogOut2.setContentAreaFilled(false);
        btnLogOut2.setFocusPainted(false);
        
        btnStreak2.setContentAreaFilled(false);
        btnStreak2.setFocusPainted(false);
        
        btnBack2.setContentAreaFilled(false);
        btnBack2.setFocusPainted(false);
        
        btnChange2.setContentAreaFilled(false);
        btnChange2.setFocusPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWarning = new javax.swing.JLabel();
        pnlPasswordChange = new javax.swing.JPanel();
        btnChange2 = new javax.swing.JButton();
        txtConfirmPassword = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        txtCurrentPassword = new javax.swing.JPasswordField();
        btnBack2 = new javax.swing.JButton();
        btnStreak2 = new javax.swing.JButton();
        btnLogOut2 = new javax.swing.JButton();
        lblBackground2 = new javax.swing.JLabel();
        pnlUsernameChange = new javax.swing.JPanel();
        btnChange = new javax.swing.JButton();
        txtConfirmUsername = new javax.swing.JTextField();
        txtNewUsername = new javax.swing.JTextField();
        txtCurrentUsername = new javax.swing.JTextField();
        btnBack1 = new javax.swing.JButton();
        btnStreak1 = new javax.swing.JButton();
        btnLogOut1 = new javax.swing.JButton();
        lblBackground1 = new javax.swing.JLabel();
        pnlGeneralSettings = new javax.swing.JPanel();
        btnChangePassword = new javax.swing.JButton();
        btnChangeUser = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnStreak = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        lblWarning.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblWarning);
        lblWarning.setBounds(280, 100, 760, 30);

        pnlPasswordChange.setPreferredSize(new java.awt.Dimension(1280, 720));
        pnlPasswordChange.setLayout(null);

        btnChange2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnChange2.setForeground(new java.awt.Color(255, 117, 31));
        btnChange2.setText("CONFIRM CHANGE");
        btnChange2.setBorder(null);
        btnChange2.setBorderPainted(false);
        btnChange2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChange2ActionPerformed(evt);
            }
        });
        pnlPasswordChange.add(btnChange2);
        btnChange2.setBounds(473, 600, 335, 60);

        txtConfirmPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        pnlPasswordChange.add(txtConfirmPassword);
        txtConfirmPassword.setBounds(640, 480, 520, 70);

        txtNewPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        pnlPasswordChange.add(txtNewPassword);
        txtNewPassword.setBounds(640, 390, 520, 70);

        txtCurrentPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        pnlPasswordChange.add(txtCurrentPassword);
        txtCurrentPassword.setBounds(640, 300, 520, 70);

        btnBack2.setBackground(new java.awt.Color(255, 117, 31));
        btnBack2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnBack2.setForeground(new java.awt.Color(255, 255, 255));
        btnBack2.setText("BACK");
        btnBack2.setBorder(null);
        btnBack2.setBorderPainted(false);
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });
        pnlPasswordChange.add(btnBack2);
        btnBack2.setBounds(40, 118, 140, 30);

        btnStreak2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnStreak2.setForeground(new java.awt.Color(255, 117, 31));
        btnStreak2.setText("CHECK STREAK");
        btnStreak2.setBorder(null);
        btnStreak2.setBorderPainted(false);
        btnStreak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStreak2ActionPerformed(evt);
            }
        });
        pnlPasswordChange.add(btnStreak2);
        btnStreak2.setBounds(970, 20, 280, 50);

        btnLogOut2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnLogOut2.setForeground(new java.awt.Color(255, 51, 51));
        btnLogOut2.setText("LOG OUT");
        btnLogOut2.setBorder(null);
        btnLogOut2.setBorderPainted(false);
        btnLogOut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOut2ActionPerformed(evt);
            }
        });
        pnlPasswordChange.add(btnLogOut2);
        btnLogOut2.setBounds(753, 18, 190, 54);

        lblBackground2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Change Password.png"))); // NOI18N
        lblBackground2.setSize(new java.awt.Dimension(1280, 720));
        pnlPasswordChange.add(lblBackground2);
        lblBackground2.setBounds(0, 0, 1280, 720);

        getContentPane().add(pnlPasswordChange);
        pnlPasswordChange.setBounds(0, 0, 1280, 720);

        pnlUsernameChange.setPreferredSize(new java.awt.Dimension(1280, 720));
        pnlUsernameChange.setLayout(null);

        btnChange.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnChange.setForeground(new java.awt.Color(255, 117, 31));
        btnChange.setText("CONFIRM CHANGE");
        btnChange.setBorder(null);
        btnChange.setBorderPainted(false);
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        pnlUsernameChange.add(btnChange);
        btnChange.setBounds(473, 600, 335, 60);

        txtConfirmUsername.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        pnlUsernameChange.add(txtConfirmUsername);
        txtConfirmUsername.setBounds(640, 480, 520, 70);

        txtNewUsername.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        pnlUsernameChange.add(txtNewUsername);
        txtNewUsername.setBounds(640, 390, 520, 70);

        txtCurrentUsername.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        pnlUsernameChange.add(txtCurrentUsername);
        txtCurrentUsername.setBounds(640, 300, 520, 70);

        btnBack1.setBackground(new java.awt.Color(255, 117, 31));
        btnBack1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(255, 255, 255));
        btnBack1.setText("BACK");
        btnBack1.setBorder(null);
        btnBack1.setBorderPainted(false);
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        pnlUsernameChange.add(btnBack1);
        btnBack1.setBounds(40, 118, 140, 30);

        btnStreak1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnStreak1.setForeground(new java.awt.Color(255, 117, 31));
        btnStreak1.setText("CHECK STREAK");
        btnStreak1.setBorder(null);
        btnStreak1.setBorderPainted(false);
        btnStreak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStreak1ActionPerformed(evt);
            }
        });
        pnlUsernameChange.add(btnStreak1);
        btnStreak1.setBounds(970, 20, 280, 50);

        btnLogOut1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnLogOut1.setForeground(new java.awt.Color(255, 51, 51));
        btnLogOut1.setText("LOG OUT");
        btnLogOut1.setBorder(null);
        btnLogOut1.setBorderPainted(false);
        btnLogOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOut1ActionPerformed(evt);
            }
        });
        pnlUsernameChange.add(btnLogOut1);
        btnLogOut1.setBounds(753, 18, 190, 54);

        lblBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Change Username.png"))); // NOI18N
        lblBackground1.setSize(new java.awt.Dimension(1280, 720));
        pnlUsernameChange.add(lblBackground1);
        lblBackground1.setBounds(0, 0, 1280, 720);

        getContentPane().add(pnlUsernameChange);
        pnlUsernameChange.setBounds(0, 0, 1280, 720);

        pnlGeneralSettings.setPreferredSize(new java.awt.Dimension(1280, 720));
        pnlGeneralSettings.setLayout(null);

        btnChangePassword.setBackground(new java.awt.Color(255, 117, 31));
        btnChangePassword.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        btnChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        btnChangePassword.setText("Change Password");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        pnlGeneralSettings.add(btnChangePassword);
        btnChangePassword.setBounds(365, 512, 550, 134);

        btnChangeUser.setBackground(new java.awt.Color(255, 117, 31));
        btnChangeUser.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        btnChangeUser.setForeground(new java.awt.Color(255, 255, 255));
        btnChangeUser.setText("Change Username");
        btnChangeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeUserActionPerformed(evt);
            }
        });
        pnlGeneralSettings.add(btnChangeUser);
        btnChangeUser.setBounds(365, 336, 550, 134);

        btnBack.setBackground(new java.awt.Color(255, 117, 31));
        btnBack.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlGeneralSettings.add(btnBack);
        btnBack.setBounds(40, 118, 140, 30);

        btnStreak.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnStreak.setForeground(new java.awt.Color(255, 117, 31));
        btnStreak.setText("CHECK STREAK");
        btnStreak.setBorder(null);
        btnStreak.setBorderPainted(false);
        btnStreak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStreakActionPerformed(evt);
            }
        });
        pnlGeneralSettings.add(btnStreak);
        btnStreak.setBounds(970, 20, 280, 50);

        btnLogOut.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 51, 51));
        btnLogOut.setText("LOG OUT");
        btnLogOut.setBorder(null);
        btnLogOut.setBorderPainted(false);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        pnlGeneralSettings.add(btnLogOut);
        btnLogOut.setBounds(753, 18, 190, 54);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Account Settings.png"))); // NOI18N
        lblBackground.setSize(new java.awt.Dimension(1280, 720));
        pnlGeneralSettings.add(lblBackground);
        lblBackground.setBounds(0, 0, 1280, 720);

        getContentPane().add(pnlGeneralSettings);
        pnlGeneralSettings.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStreakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStreakActionPerformed
        streakAccountGUI accountGUI = new streakAccountGUI();

        accountGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStreakActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        LoggedOutMainGUI logOut = new LoggedOutMainGUI();

        logOut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MainGUI mainMenu = new MainGUI();
        
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // Closing change panels
        pnlUsernameChange.setEnabled(false);
        pnlUsernameChange.setVisible(false);
        pnlPasswordChange.setEnabled(false);
        pnlPasswordChange.setVisible(false);
        
        pnlGeneralSettings.setEnabled(true);
        pnlGeneralSettings.setVisible(true);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnStreak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStreak1ActionPerformed
        streakAccountGUI accountGUI = new streakAccountGUI();

        accountGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStreak1ActionPerformed

    private void btnLogOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOut1ActionPerformed
        LoggedOutMainGUI logOut = new LoggedOutMainGUI();

        logOut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOut1ActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        lblWarning.setText("");
        
        String currentUsername = txtCurrentUsername.getText();
        String newUsername = txtNewUsername.getText();
        
        if(currentUsername.equals(LoginGUI.user.getUsername()))
        {

            if(newUsername.equals(txtConfirmUsername.getText()))
            {
                LoginGUI.user.setUsername(newUsername);
                
                // Closing change panels
                pnlUsernameChange.setEnabled(false);
                pnlUsernameChange.setVisible(false);
                pnlPasswordChange.setEnabled(false);
                pnlPasswordChange.setVisible(false);

                pnlGeneralSettings.setEnabled(true);
                pnlGeneralSettings.setVisible(true);
                
                lblWarning.setText("Username changed successfully!");
            }
            else
            {
                lblWarning.setText("New Usernames do not match!");
            }
        }
        else
        {
            lblWarning.setText("Incorrect current Username!");
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnChange2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChange2ActionPerformed
        lblWarning.setText("");
        
        String currentPassword = String.valueOf(txtCurrentPassword.getPassword());
        String newPassword = String.valueOf(txtNewPassword.getPassword());
        
        // Checks if the current password is in the system
        if(currentPassword.equals(LoginGUI.user.getPassword()))
        {
            // If yes, continue to change the password with setter method
            if(newPassword.equals(String.valueOf(txtConfirmPassword.getPassword())))
            {
                LoginGUI.user.setPassword(newPassword);
                
                // Closing change panels
                pnlUsernameChange.setEnabled(false);
                pnlUsernameChange.setVisible(false);
                pnlPasswordChange.setEnabled(false);
                pnlPasswordChange.setVisible(false);

                pnlGeneralSettings.setEnabled(true);
                pnlGeneralSettings.setVisible(true);
                
                lblWarning.setText("Password changed successfully!");
            }
            else
            {
                lblWarning.setText("New Passwords do not match!");
            }
        }
        // Give warning if not
        else
        {
            lblWarning.setText("Incorrect current Password!");
        }
    }//GEN-LAST:event_btnChange2ActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // Closing change panels
        pnlUsernameChange.setEnabled(false);
        pnlUsernameChange.setVisible(false);
        pnlPasswordChange.setEnabled(false);
        pnlPasswordChange.setVisible(false);
        
        pnlGeneralSettings.setEnabled(true);
        pnlGeneralSettings.setVisible(true);
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void btnStreak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStreak2ActionPerformed
        streakAccountGUI accountGUI = new streakAccountGUI();

        accountGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStreak2ActionPerformed

    private void btnLogOut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOut2ActionPerformed
        LoggedOutMainGUI logOut = new LoggedOutMainGUI();

        logOut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOut2ActionPerformed

    private void btnChangeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeUserActionPerformed
        // Showing the username change panel
        pnlUsernameChange.setEnabled(true);
        pnlUsernameChange.setVisible(true);
        
        // Ensuring the other 2 panels are closed
        pnlPasswordChange.setEnabled(false);
        pnlPasswordChange.setVisible(false);
        
        pnlGeneralSettings.setEnabled(false);
        pnlGeneralSettings.setVisible(false);
    }//GEN-LAST:event_btnChangeUserActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // Showing the Password change panel
        pnlPasswordChange.setEnabled(true);
        pnlPasswordChange.setVisible(true);
        
        // Ensuring the other 2 panels are closed
        pnlUsernameChange.setEnabled(false);
        pnlUsernameChange.setVisible(false);
        
        pnlGeneralSettings.setEnabled(false);
        pnlGeneralSettings.setVisible(false);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new accountSettingsGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnChange2;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnChangeUser;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnLogOut1;
    private javax.swing.JButton btnLogOut2;
    private javax.swing.JButton btnStreak;
    private javax.swing.JButton btnStreak1;
    private javax.swing.JButton btnStreak2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBackground1;
    private javax.swing.JLabel lblBackground2;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JPanel pnlGeneralSettings;
    private javax.swing.JPanel pnlPasswordChange;
    private javax.swing.JPanel pnlUsernameChange;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtConfirmUsername;
    private javax.swing.JPasswordField txtCurrentPassword;
    private javax.swing.JTextField txtCurrentUsername;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JTextField txtNewUsername;
    // End of variables declaration//GEN-END:variables
}
