/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package accountGUI;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;

/**
 *
 * @author pamlee
 */
public class CreateAccountGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateAccountGUI.class.getName());

    
    /**
     * Creates new form CreateAccountGUI
     */
    public CreateAccountGUI() 
    {
        initComponents();
        
        // Makes the buttons appear as just text (app aesthetics)
        btnCreateAcc.setContentAreaFilled(false);
        btnCreateAcc.setFocusPainted(false);
        
        btnLoginTop.setContentAreaFilled(false);
        btnLoginTop.setFocusPainted(false);
        
        btnCreateAccTop.setContentAreaFilled(false);
        btnCreateAccTop.setFocusPainted(false);
        
        // Making sure the warning is empty when the window is opened
        lblWarning.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtVerifyPassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        lblWarning = new javax.swing.JLabel();
        btnCreateAcc = new javax.swing.JButton();
        btnCreateAccTop = new javax.swing.JButton();
        btnLoginTop = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        txtVerifyPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jPanel1.add(txtVerifyPassword);
        txtVerifyPassword.setBounds(620, 480, 450, 50);

        txtPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jPanel1.add(txtPassword);
        txtPassword.setBounds(620, 380, 450, 50);

        txtUsername.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jPanel1.add(txtUsername);
        txtUsername.setBounds(620, 280, 450, 50);

        lblWarning.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblWarning);
        lblWarning.setBounds(270, 230, 760, 30);

        btnCreateAcc.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnCreateAcc.setForeground(new java.awt.Color(255, 117, 31));
        btnCreateAcc.setText("CREATE AN ACCOUNT");
        btnCreateAcc.setBorder(null);
        btnCreateAcc.setBorderPainted(false);
        btnCreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateAcc);
        btnCreateAcc.setBounds(475, 600, 330, 60);

        btnCreateAccTop.setBackground(new java.awt.Color(255, 255, 102));
        btnCreateAccTop.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnCreateAccTop.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateAccTop.setText("Create An Account");
        btnCreateAccTop.setBorder(null);
        btnCreateAccTop.setBorderPainted(false);
        btnCreateAccTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccTopActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateAccTop);
        btnCreateAccTop.setBounds(1060, 30, 190, 30);

        btnLoginTop.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnLoginTop.setForeground(new java.awt.Color(255, 117, 31));
        btnLoginTop.setText("LOGIN");
        btnLoginTop.setBorder(null);
        btnLoginTop.setBorderPainted(false);
        btnLoginTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginTopActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoginTop);
        btnLoginTop.setBounds(837, 30, 190, 30);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Create an Account.png"))); // NOI18N
        lblBackground.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblBackground);
        lblBackground.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccActionPerformed
        lblWarning.setText("");
        // Creates an account based on the entered information
        // Stores the information in a file
        
        String username = txtUsername.getText();
        
        // Checking if the username already exists
        // opens the file that stores all the current user information
        File file = new File("userinfo.txt");
        // New arraylist to store all of the existing information
        ArrayList<String> lines = new ArrayList<>();

        // Opening the file and reading all the lines and appending it all to the arraylist
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;

            while ((line = reader.readLine()) != null) 
            {
                String[] data = line.split(",");

                if (data[0].equals(username)) 
                {
                    lblWarning.setText("Username taken! Please enter another.");
                    return;
                }
            }
        } 
        catch (java.io.IOException e) {
            e.printStackTrace();
        }
        
        String password = String.valueOf(txtPassword.getPassword());
        
        if(password.equals(String.valueOf(txtVerifyPassword.getPassword())))
        {
            Student.registerNew(username, password); // calls static registeration method
            LoginGUI login = new LoginGUI();
            
            login.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            lblWarning.setText("Passwords do not match!");
        }
    }//GEN-LAST:event_btnCreateAccActionPerformed

    private void btnCreateAccTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccTopActionPerformed
        // Create account button --> opens the create account
        CreateAccountGUI createAcc = new CreateAccountGUI();
        
        createAcc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCreateAccTopActionPerformed

    private void btnLoginTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginTopActionPerformed
        // Login button at the button "Here" --> opens the login GUI
        LoginGUI login = new LoginGUI();
        
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLoginTopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CreateAccountGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAcc;
    private javax.swing.JButton btnCreateAccTop;
    private javax.swing.JButton btnLoginTop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPasswordField txtVerifyPassword;
    // End of variables declaration//GEN-END:variables
}
