/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package accountGUI;

/**
 *
 * @author pamlee
 */
public class LoggedOutMainGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoggedOutMainGUI.class.getName());

    /**
     * Creates new form LoggedOutMainGUI
     */
    public LoggedOutMainGUI() {
        initComponents();
        
        // Makes the buttons appear as just text (app aesthetics)
        btnLogin.setContentAreaFilled(false);
        btnLogin.setFocusPainted(false);
        
        btnLoginSmall.setContentAreaFilled(false);
        btnLoginSmall.setFocusPainted(false);
        
        btnCreateAcc.setContentAreaFilled(false);
        btnCreateAcc.setFocusPainted(false);
        
        btnCreateAccBig.setContentAreaFilled(false);
        btnCreateAccBig.setFocusPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLoginSmall = new javax.swing.JButton();
        btnCreateAccBig = new javax.swing.JButton();
        btnCreateAcc = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        btnLoginSmall.setFont(new java.awt.Font("Gujarati Sangam MN", 1, 18)); // NOI18N
        btnLoginSmall.setForeground(new java.awt.Color(255, 117, 31));
        btnLoginSmall.setText("HERE.");
        btnLoginSmall.setBorder(null);
        btnLoginSmall.setBorderPainted(false);
        btnLoginSmall.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnLoginSmall.setOpaque(true);
        btnLoginSmall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginSmallActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoginSmall);
        btnLoginSmall.setBounds(768, 650, 63, 20);

        btnCreateAccBig.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnCreateAccBig.setForeground(new java.awt.Color(255, 117, 31));
        btnCreateAccBig.setText("Create Account!");
        btnCreateAccBig.setBorder(null);
        btnCreateAccBig.setBorderPainted(false);
        btnCreateAccBig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccBigActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateAccBig);
        btnCreateAccBig.setBounds(530, 450, 220, 60);

        btnCreateAcc.setBackground(new java.awt.Color(255, 255, 102));
        btnCreateAcc.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnCreateAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateAcc.setText("Create An Account");
        btnCreateAcc.setBorder(null);
        btnCreateAcc.setBorderPainted(false);
        btnCreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateAcc);
        btnCreateAcc.setBounds(1060, 30, 190, 30);

        btnLogin.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 117, 31));
        btnLogin.setText("LOGIN");
        btnLogin.setBorder(null);
        btnLogin.setBorderPainted(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin);
        btnLogin.setBounds(837, 30, 190, 30);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Base Interface (Create an Account; No side menu).png"))); // NOI18N
        lblBackground.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblBackground);
        lblBackground.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Login button at the top --> opens the login GUI
        LoginGUI login = new LoginGUI();
        
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccActionPerformed
        // Create account button --> opens the create account
        CreateAccountGUI createAcc = new CreateAccountGUI();
        
        createAcc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCreateAccActionPerformed

    private void btnCreateAccBigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccBigActionPerformed
        // Create account button --> opens the create account
        CreateAccountGUI createAcc = new CreateAccountGUI();
        
        createAcc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCreateAccBigActionPerformed

    private void btnLoginSmallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginSmallActionPerformed
        // Login button at the button "Here" --> opens the login GUI
        LoginGUI login = new LoginGUI();
        
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLoginSmallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoggedOutMainGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAcc;
    private javax.swing.JButton btnCreateAccBig;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLoginSmall;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    // End of variables declaration//GEN-END:variables
}
