/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package accountGUI;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import accountGUI.*;
import mainGUI.MainGUI;

/**
 *
 * @author pamlee
 */
public class LoginGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginGUI.class.getName());

    static String[] adminCodes = {"69375","67672","30295","10102"}; // hard-coded admin codes
    
    public static boolean admin = false;
    
    public static Student user;

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
        
        // Makes the buttons appear as just text (app aesthetics)
        btnLogin.setContentAreaFilled(false);
        btnLogin.setFocusPainted(false);
        
        btnLoginTop.setContentAreaFilled(false);
        btnLoginTop.setFocusPainted(false);
        
        btnCreateAcc.setContentAreaFilled(false);
        btnCreateAcc.setFocusPainted(false);
        
        // Ensures no warnings show when the window first opens
        lblWarning.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWarning = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnCreateAcc = new javax.swing.JButton();
        btnLoginTop = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        lblWarning.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblWarning);
        lblWarning.setBounds(272, 280, 760, 30);

        txtPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jPanel1.add(txtPassword);
        txtPassword.setBounds(520, 440, 510, 50);

        txtUsername.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jPanel1.add(txtUsername);
        txtUsername.setBounds(518, 340, 510, 50);

        btnLogin.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 117, 31));
        btnLogin.setText("LOGIN");
        btnLogin.setBorder(null);
        btnLogin.setBorderPainted(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin);
        btnLogin.setBounds(530, 554, 220, 60);

        btnCreateAcc.setBackground(new java.awt.Color(255, 255, 102));
        btnCreateAcc.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnCreateAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateAcc.setText("Create An Account");
        btnCreateAcc.setBorder(null);
        btnCreateAcc.setBorderPainted(false);
        btnCreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateAcc);
        btnCreateAcc.setBounds(1060, 30, 190, 30);

        btnLoginTop.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnLoginTop.setForeground(new java.awt.Color(255, 117, 31));
        btnLoginTop.setText("LOGIN");
        btnLoginTop.setBorder(null);
        btnLoginTop.setBorderPainted(false);
        btnLoginTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginTopActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoginTop);
        btnLoginTop.setBounds(837, 30, 190, 30);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Login.png"))); // NOI18N
        lblBackground.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblBackground);
        lblBackground.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Clears previous warnings
        lblWarning.setText("");
        int loginTrue = verifyLogin(txtUsername.getText(),String.valueOf(txtPassword.getPassword())); // sends a call to check if it's a valid login
        if (loginTrue == 2) {
            // admin success
            admin = true;
            
            MainGUI home = new MainGUI();
            
            home.setVisible(true);
            this.setVisible(false);
        }
        else if (loginTrue == 1) { // student success
            admin = false;
            try 
            {
                BufferedReader reader = new BufferedReader(new FileReader("userinfo.txt"));
                String line = reader.readLine();
                while (line != null) {
                    String[] parts = line.split(",");
                    user = new Student(parts[0], parts[1], Integer.valueOf(parts[2]), Integer.valueOf(parts[3]), Integer.valueOf(parts[4]), Boolean.valueOf(parts[5]), Boolean.valueOf(parts[6]));
                    line = reader.readLine();
                }
               reader.close();
            } 
            catch (Exception ex) 
            {
                
            }
            
            MainGUI home = new MainGUI();
            
            home.setVisible(true);
            this.setVisible(false);
        }
        else {
            admin = false;
            lblWarning.setText("Invalid Login! Please check your username/password.");
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccActionPerformed
        // Create account button --> opens the create account
        CreateAccountGUI createAcc = new CreateAccountGUI();
        
        createAcc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCreateAccActionPerformed

    private void btnLoginTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginTopActionPerformed
        // Login button --> opens the new login GUI; basically resets the current page
        LoginGUI login = new LoginGUI();
        
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLoginTopActionPerformed

    public static int verifyLogin(String usrInput, String pswdInput) { // verifies login
        for (int i = 0; i < adminCodes.length; i++) { // checks for admin codes
            if (pswdInput.equals(adminCodes[i])) {
                admin = true;
                return 2; // admin success
            }
        }
        try (BufferedReader reader = new BufferedReader(new FileReader("userinfo.txt"))) { // initalizes buffer reader
                String line = reader.readLine();
                while (line != null) { 
                    String[] parts = line.split(","); // split at "," detected
                    if (parts[0].equals(usrInput) && parts[1].equals(pswdInput)) {  // check split parts, if usr and pswd match the entered values
                        return 1;
                    }
                    line = reader.readLine();
                }
            } catch (Exception e) { // catch exceptions if they appear
            }
        return 0; // send failure
    }
    
    public static boolean adminCheck()
    {
        return admin;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAcc;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLoginTop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
