/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pomodoroGUI;
import accountGUI.LoggedOutMainGUI;
import accountGUI.streakAccountGUI;
import accountGUI.accountSettingsGUI;
import questionGeneratingGUI.*;
import mainGUI.*;
import testUploadGUI.*;
import pastTestGUI.*;
import notepadGUI.*;

/*Name: Pomodoro Timer
  Date: 1/12/2026*/
import java.io.File;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Color;
import javax.swing.Timer;
import javax.sound.sampled.*;
import java.net.URL;
import java.net.URI;


/**
 *
 * @author pamlee
 */
public class pomodoroGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(pomodoroGUI.class.getName());

    private Timer timer; /*Countdown timer that triggers action every second*/
    private int remainingSeconds; /*remaining time in seconds for session*/
    private boolean isStudy = true;  /*Keeps track if current session is study or break*/
    private Clip clip; /*Clip object used to play alarm sounds*/
    private Clip backgroundClip; /*Clip object used to play background music*/
    private String currentSong = null; /*Stroes the name of the currently selected background music (helps replay later on)*/
    
    // Base colour for buttons and text
    Color baseOrange = new Color(255,117,31);
    Color basePink = new Color(255,51,153);
    
    // Boolean to check whether or not the menu is opened
    private boolean menuOpened = true;
    
    /**
     * Creates new form pomodoroGUI
     */
    public pomodoroGUI() {
        initComponents();
        
        Volume.addChangeListener(e -> updateBackgroundVolume()); /*This was added in order for the volume to be controlled by the slider*/

        
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setFocusPainted(false);
        
        btnAccount.setContentAreaFilled(false);
        btnAccount.setFocusPainted(false);
        
        btnCloseMenu.setContentAreaFilled(false);
        btnCloseMenu.setFocusPainted(false);
        
        btnOpenMenu.setContentAreaFilled(false);
        btnOpenMenu.setFocusPainted(false);
        
        btnStudyTools.setContentAreaFilled(false);
        btnStudyTools.setFocusPainted(false);
        
        btnPomoTimer.setContentAreaFilled(false);
        btnPomoTimer.setFocusPainted(false);
        
        btnPastTest.setContentAreaFilled(false);
        btnPastTest.setFocusPainted(false);
        
        btnQuestionGen.setContentAreaFilled(false);
        btnQuestionGen.setFocusPainted(false);
        
        btnUploadTest.setContentAreaFilled(false);
        btnUploadTest.setFocusPainted(false);
        
        btnNotepad.setContentAreaFilled(false);
        btnNotepad.setFocusPainted(false);
        
        btnMyStreak.setContentAreaFilled(false);
        btnMyStreak.setFocusPainted(false);
        
        btnStart.setContentAreaFilled(false);
        btnStart.setFocusPainted(false);
        
        // Hiding the "open menu" button
        btnOpenMenu.setEnabled(false);
        btnOpenMenu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtStudyTime = new javax.swing.JTextField();
        txtBreakTime = new javax.swing.JTextField();
        Volume = new javax.swing.JSlider();
        cmbMusic = new javax.swing.JComboBox<>();
        cmbBackground = new javax.swing.JComboBox<>();
        btnStart = new javax.swing.JButton();
        lblPrompt = new javax.swing.JLabel();
        btnAccount = new javax.swing.JButton();
        btnCloseMenu = new javax.swing.JButton();
        btnMyStreak = new javax.swing.JButton();
        btnNotepad = new javax.swing.JButton();
        btnUploadTest = new javax.swing.JButton();
        btnQuestionGen = new javax.swing.JButton();
        btnPastTest = new javax.swing.JButton();
        btnPomoTimer = new javax.swing.JButton();
        btnStudyTools = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        lblColouredBG = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        btnOpenMenu = new javax.swing.JButton();
        lblColouredBGWOMenu = new javax.swing.JLabel();
        lblBackgroundWOMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        txtStudyTime.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jPanel1.add(txtStudyTime);
        txtStudyTime.setBounds(860, 435, 230, 60);

        txtBreakTime.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtBreakTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBreakTimeActionPerformed(evt);
            }
        });
        jPanel1.add(txtBreakTime);
        txtBreakTime.setBounds(860, 510, 230, 60);
        jPanel1.add(Volume);
        Volume.setBounds(404, 230, 280, 20);

        cmbMusic.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cmbMusic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose A Song", "Song 1", "Song 2", "Song 3" }));
        cmbMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMusicActionPerformed(evt);
            }
        });
        jPanel1.add(cmbMusic);
        cmbMusic.setBounds(400, 110, 290, 50);

        cmbBackground.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cmbBackground.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Background 1", "Background 2", "Background 3", "Background 4" }));
        cmbBackground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBackgroundActionPerformed(evt);
            }
        });
        jPanel1.add(cmbBackground);
        cmbBackground.setBounds(400, 170, 290, 50);

        btnStart.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 117, 31));
        btnStart.setText("START");
        btnStart.setBorder(null);
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel1.add(btnStart);
        btnStart.setBounds(714, 600, 282, 76);

        lblPrompt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrompt.setText("Please enter the time in this format - HH:MM:SS");
        jPanel1.add(lblPrompt);
        lblPrompt.setBounds(623, 410, 430, 22);

        btnAccount.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnAccount.setForeground(new java.awt.Color(255, 117, 31));
        btnAccount.setText("MANAGE ACCOUNT");
        btnAccount.setBorder(null);
        btnAccount.setBorderPainted(false);
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccount);
        btnAccount.setBounds(970, 20, 280, 50);

        btnCloseMenu.setBackground(new java.awt.Color(255, 117, 31));
        btnCloseMenu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnCloseMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseMenu.setText("CLOSE MENU");
        btnCloseMenu.setBorder(null);
        btnCloseMenu.setBorderPainted(false);
        btnCloseMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnCloseMenu);
        btnCloseMenu.setBounds(130, 110, 140, 30);

        btnMyStreak.setBackground(new java.awt.Color(255, 204, 102));
        btnMyStreak.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnMyStreak.setText("My Streak");
        btnMyStreak.setBorder(null);
        btnMyStreak.setBorderPainted(false);
        btnMyStreak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyStreakActionPerformed(evt);
            }
        });
        jPanel1.add(btnMyStreak);
        btnMyStreak.setBounds(60, 560, 270, 30);

        btnNotepad.setBackground(new java.awt.Color(255, 204, 102));
        btnNotepad.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnNotepad.setText("Notepad");
        btnNotepad.setBorder(null);
        btnNotepad.setBorderPainted(false);
        btnNotepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotepadActionPerformed(evt);
            }
        });
        jPanel1.add(btnNotepad);
        btnNotepad.setBounds(60, 500, 270, 30);

        btnUploadTest.setBackground(new java.awt.Color(255, 204, 102));
        btnUploadTest.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnUploadTest.setText("Upload A Test");
        btnUploadTest.setBorder(null);
        btnUploadTest.setBorderPainted(false);
        btnUploadTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadTestActionPerformed(evt);
            }
        });
        jPanel1.add(btnUploadTest);
        btnUploadTest.setBounds(60, 440, 270, 30);

        btnQuestionGen.setBackground(new java.awt.Color(255, 204, 102));
        btnQuestionGen.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnQuestionGen.setText("Question Generator");
        btnQuestionGen.setBorder(null);
        btnQuestionGen.setBorderPainted(false);
        btnQuestionGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuestionGenActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuestionGen);
        btnQuestionGen.setBounds(60, 380, 270, 30);

        btnPastTest.setBackground(new java.awt.Color(255, 204, 51));
        btnPastTest.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnPastTest.setText("Past Student Tests");
        btnPastTest.setBorder(null);
        btnPastTest.setBorderPainted(false);
        btnPastTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastTestActionPerformed(evt);
            }
        });
        jPanel1.add(btnPastTest);
        btnPastTest.setBounds(60, 320, 270, 30);

        btnPomoTimer.setBackground(new java.awt.Color(255, 204, 51));
        btnPomoTimer.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnPomoTimer.setForeground(new java.awt.Color(255, 0, 0));
        btnPomoTimer.setText("Pomodoro Timer");
        btnPomoTimer.setBorder(null);
        btnPomoTimer.setBorderPainted(false);
        btnPomoTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPomoTimerActionPerformed(evt);
            }
        });
        jPanel1.add(btnPomoTimer);
        btnPomoTimer.setBounds(60, 260, 270, 30);

        btnStudyTools.setBackground(new java.awt.Color(255, 153, 0));
        btnStudyTools.setFont(new java.awt.Font("Verdana", 1, 40)); // NOI18N
        btnStudyTools.setForeground(new java.awt.Color(255, 255, 255));
        btnStudyTools.setText("STUDY TOOLS");
        btnStudyTools.setBorder(null);
        btnStudyTools.setBorderPainted(false);
        btnStudyTools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudyToolsActionPerformed(evt);
            }
        });
        jPanel1.add(btnStudyTools);
        btnStudyTools.setBounds(10, 170, 360, 60);

        btnLogOut.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 51, 51));
        btnLogOut.setText("LOG OUT");
        btnLogOut.setBorder(null);
        btnLogOut.setBorderPainted(false);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut);
        btnLogOut.setBounds(100, 620, 180, 30);

        lblColouredBG.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblColouredBG);
        lblColouredBG.setBounds(0, 0, 1280, 720);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Pomodoro Timer (WITH side menu).png"))); // NOI18N
        lblBackground.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblBackground);
        lblBackground.setBounds(0, 0, 1280, 720);

        btnOpenMenu.setBackground(new java.awt.Color(255, 117, 31));
        btnOpenMenu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnOpenMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnOpenMenu.setText("OPEN MENU");
        btnOpenMenu.setBorder(null);
        btnOpenMenu.setBorderPainted(false);
        btnOpenMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpenMenu);
        btnOpenMenu.setBounds(40, 118, 140, 30);
        jPanel1.add(lblColouredBGWOMenu);
        lblColouredBGWOMenu.setBounds(0, 0, 1280, 720);

        lblBackgroundWOMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/Pomodoro Timer (WITHOUT side menu).png"))); // NOI18N
        lblBackgroundWOMenu.setSize(new java.awt.Dimension(1280, 720));
        jPanel1.add(lblBackgroundWOMenu);
        lblBackgroundWOMenu.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        accountSettingsGUI accountGUI = new accountSettingsGUI();
        
        accountGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnCloseMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseMenuActionPerformed
        menuOpened = false;

        // disables buttons to show buttons for the open-menu and remove closed-menu buttons; (app aesthetic)
        lblBackground.setEnabled(false);
        lblBackground.setVisible(false);

        btnCloseMenu.setEnabled(false);
        btnCloseMenu.setVisible(false);

        btnStudyTools.setEnabled(false);
        btnStudyTools.setVisible(false);

        btnPomoTimer.setEnabled(false);
        btnPomoTimer.setVisible(false);

        btnPastTest.setEnabled(false);
        btnPastTest.setVisible(false);

        btnQuestionGen.setEnabled(false);
        btnQuestionGen.setVisible(false);

        btnUploadTest.setEnabled(false);
        btnUploadTest.setVisible(false);
        
        btnNotepad.setEnabled(false);
        btnNotepad.setVisible(false);

        btnMyStreak.setEnabled(false);
        btnMyStreak.setVisible(false);

        btnOpenMenu.setEnabled(true);
        btnOpenMenu.setVisible(true);

        btnLogOut.setLocation(753, 18);
        btnLogOut.setSize(190, 54);
        
        
        // Making Jasmita's buttons and text "dynamic" with the open and close menu buttons
        btnStart.setLocation(667, 530);
        btnStart.setSize(430, 120);
        
        txtStudyTime.setLocation(870, 290);
        txtStudyTime.setSize(310, 90);
        
        txtBreakTime.setLocation(870, 400);
        txtBreakTime.setSize(310, 90);
        
        lblPrompt.setLocation(660, 250);
        
        cmbMusic.setLocation(60, 462);
        cmbMusic.setSize(470, 70);
        
        cmbBackground.setLocation(60, 552);
        cmbBackground.setSize(470, 70);
        
        Volume.setLocation(130, 660);
        Volume.setSize(280, 20);
        
        // If the user selected a certain colour, keep that colour even as they open and close the menu
        String selectedBackground = cmbBackground.getSelectedItem().toString(); /*Get selected background from the combo box*/

        if (selectedBackground.equals("Background 1"))
        {
            lblColouredBGWOMenu.setVisible(false);
            lblColouredBG.setVisible(false);
            
            btnStart.setForeground(baseOrange);
        } 
        else if (selectedBackground.equals("Background 2"))
        {
            lblColouredBGWOMenu.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Green Pomodoro Timer (WITHOUT side menu).png"));
            lblColouredBGWOMenu.setVisible(true);
            lblColouredBG.setVisible(false);
            
            btnStart.setForeground(Color.GREEN);
        } 
        else if (selectedBackground.equals("Background 3"))
        {
            lblColouredBGWOMenu.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Pink Pomodoro Timer (WITHOUT side menu).png"));
            lblColouredBGWOMenu.setVisible(true);
            lblColouredBG.setVisible(false);
            
            btnStart.setForeground(basePink);
        } 
        else if (selectedBackground.equals("Background 4"))
        {
            /*ImageIcon is used to change the JLabel icon (i.e. background). It is change dependent on what option is choosen*/
            lblColouredBGWOMenu.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Blue Pomodoro Timer (WITHOUT side menu).png"));
            lblColouredBGWOMenu.setVisible(true);
            lblColouredBG.setVisible(false);
            
            btnStart.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_btnCloseMenuActionPerformed

    private void btnStudyToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudyToolsActionPerformed
        // Opens the main menu GUI
        MainGUI mainGUI = new MainGUI();

        mainGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStudyToolsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        LoggedOutMainGUI logOut = new LoggedOutMainGUI();

        logOut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnOpenMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenMenuActionPerformed
        menuOpened = true;
    
        // Re-enables buttons to show buttons for the closed-menu; (app aesthetic)
        lblBackground.setEnabled(true);
        lblBackground.setVisible(true);

        // Hide open menu button again
        btnOpenMenu.setEnabled(false);
        btnOpenMenu.setVisible(false);

        // Show the rest of the buttons again
        btnCloseMenu.setEnabled(true);
        btnCloseMenu.setVisible(true);

        btnStudyTools.setEnabled(true);
        btnStudyTools.setVisible(true);

        btnPomoTimer.setEnabled(true);
        btnPomoTimer.setVisible(true);

        btnPastTest.setEnabled(true);
        btnPastTest.setVisible(true);

        btnQuestionGen.setEnabled(true);
        btnQuestionGen.setVisible(true);

        btnUploadTest.setEnabled(true);
        btnUploadTest.setVisible(true);
        
        btnNotepad.setEnabled(true);
        btnNotepad.setVisible(true);

        btnMyStreak.setEnabled(true);
        btnMyStreak.setVisible(true);

        btnLogOut.setLocation(100, 620);
        btnLogOut.setSize(180, 30);
        
        // Making Jasmita's buttons and text "dynamic" with the open and close menu buttons
        btnStart.setLocation(714, 600);
        btnStart.setSize(282, 76);
        
        txtStudyTime.setLocation(860, 435);
        txtStudyTime.setSize(230, 60);
        txtBreakTime.setLocation(860, 510);
        txtBreakTime.setSize(230, 60);
        
        lblPrompt.setLocation(623, 410);
        
        cmbMusic.setLocation(400, 110);
        cmbMusic.setSize(290, 50);
        
        cmbBackground.setLocation(400, 170);
        cmbBackground.setSize(290, 50);
        
        Volume.setLocation(404, 230);
        Volume.setSize(280, 20);
        
        // If the user selected a certain colour, keep that colour even as they open and close the menu
        String selectedBackground = cmbBackground.getSelectedItem().toString(); /*Get selected background from the combo box*/

        if (selectedBackground.equals("Background 1"))
        {
            lblColouredBGWOMenu.setVisible(false);
            lblColouredBG.setVisible(false);
            
            btnStart.setForeground(baseOrange);
        } 
        else if (selectedBackground.equals("Background 2"))
        {
            lblColouredBG.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Green Pomodoro Timer (WITH side menu).png"));
            lblColouredBG.setVisible(true);
            
            btnStart.setForeground(Color.GREEN);
        } 
        else if (selectedBackground.equals("Background 3"))
        {
            lblColouredBG.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Pink Pomodoro Timer (WITH side menu).png"));
            lblColouredBG.setVisible(true);
            
            btnStart.setForeground(basePink);
        } 
        else if (selectedBackground.equals("Background 4"))
        {
            /*ImageIcon is used to change the JLabel icon (i.e. background). It is change dependent on what option is choosen*/
            lblColouredBG.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Blue Pomodoro Timer (WITH side menu).png"));
            lblColouredBG.setVisible(true);
            
            btnStart.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_btnOpenMenuActionPerformed

    private void txtBreakTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBreakTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBreakTimeActionPerformed

    private void cmbMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMusicActionPerformed
        String selectedSong = cmbMusic.getSelectedItem().toString(); /*Gets song user selected*/
        currentSong = selectedSong; /*Stores the current song so that it can be restarted later.*/
        switch (selectedSong){ /*Chooses which audio file to play based on selection. Uses method playBackgroundMusic().*/
            case "Song 1":
                playBackgroundMusic("src/pomodoroGUI/lofiBeatOne.wav");
                break;
            case "Song 2":
                playBackgroundMusic("src/pomodoroGUI/lofiBeatTwo.wav");
                break;
            case "Song 3":
                playBackgroundMusic("src/pomodoroGUI/lofiBeatThree.wav");
                break;
            default:
                if (backgroundClip != null) 
                {
                    backgroundClip.stop(); /*If none are selected, it stops any music currently playing.*/
                }
        }
    }//GEN-LAST:event_cmbMusicActionPerformed

    private void cmbBackgroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBackgroundActionPerformed
        String selectedBackground = cmbBackground.getSelectedItem().toString(); /*Get selected background from the combo box*/

        // If the menu is closed (false), show the new colour for the fullscreen
        // Otherwise, show a new version of the screen WITH the side menu
        if (selectedBackground.equals("Background 1"))
        {
            lblColouredBGWOMenu.setVisible(false);
            lblColouredBG.setVisible(false);
            
            btnStart.setForeground(baseOrange);
        } 
        else if (selectedBackground.equals("Background 2"))
        {
            if(menuOpened == false)
            {
                lblColouredBGWOMenu.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Green Pomodoro Timer (WITHOUT side menu).png"));
                lblColouredBGWOMenu.setVisible(true);
                lblColouredBG.setVisible(false);
            }
            else
            {
                lblColouredBG.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Green Pomodoro Timer (WITH side menu).png"));
                lblColouredBG.setVisible(true);
            }
            
            btnStart.setForeground(Color.GREEN);
        } 
        else if (selectedBackground.equals("Background 3"))
        {
            if(menuOpened == false)
            {
                lblColouredBGWOMenu.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Pink Pomodoro Timer (WITHOUT side menu).png"));
                lblColouredBGWOMenu.setVisible(true);
                lblColouredBG.setVisible(false);
            }
            else
            {
                lblColouredBG.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Pink Pomodoro Timer (WITH side menu).png"));
                lblColouredBG.setVisible(true);
            }
            
            btnStart.setForeground(basePink);
        } 
        else if (selectedBackground.equals("Background 4"))
        {
            if(menuOpened == false)
            {
                /*ImageIcon is used to change the JLabel icon (i.e. background). It is change dependent on what option is choosen*/
                lblColouredBGWOMenu.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Blue Pomodoro Timer (WITHOUT side menu).png"));
                lblColouredBGWOMenu.setVisible(true);
                lblColouredBG.setVisible(false);
            }
            else
            {
                /*ImageIcon is used to change the JLabel icon (i.e. background). It is change dependent on what option is choosen*/
                lblColouredBG.setIcon(new javax.swing.ImageIcon("src/Backgrounds/Blue Pomodoro Timer (WITH side menu).png"));
                lblColouredBG.setVisible(true);
            }
            
            btnStart.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_cmbBackgroundActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        if (isStudy == true){ /*If current session is Study mode*/
            remainingSeconds = convertToSeconds(txtStudyTime.getText(), true); /*convert the study time to seconds*/
            txtStudyTime.setText(formatTime(remainingSeconds)); /*Format and display it in the text box*/
        } else { /*Otherwise the session is in Break mode*/
            remainingSeconds = convertToSeconds(txtBreakTime.getText(), false);
            txtBreakTime.setText(formatTime(remainingSeconds));
        }

        if (remainingSeconds <= 0){ /*If time is invalid, do nothing*/
            return;
        }

        if (timer == null) { /*Create timer only once*/
            timer = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    countdown(); /*Calls countdown() every second, which then updates the screen/time*/
                }
            });
        }
        timer.start(); /*Start/re-start the timer*/

    }//GEN-LAST:event_btnStartActionPerformed

    private void btnMyStreakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyStreakActionPerformed
        streakAccountGUI accountGUI = new streakAccountGUI();

        accountGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMyStreakActionPerformed

    private void btnNotepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotepadActionPerformed
        noteGetterGUI notePad = new noteGetterGUI();
        
        notePad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNotepadActionPerformed

    private void btnUploadTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadTestActionPerformed
        testUploadGUI testUploadNew = new testUploadGUI();

        testUploadNew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUploadTestActionPerformed

    private void btnQuestionGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuestionGenActionPerformed
        QuestionGenerator qGen = new QuestionGenerator();

        qGen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuestionGenActionPerformed

    private void btnPastTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastTestActionPerformed
        pastTestGUI pastTestGUI = new pastTestGUI();

        pastTestGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPastTestActionPerformed

    private void btnPomoTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPomoTimerActionPerformed
        pomodoroGUI pomoGUI = new pomodoroGUI();

        pomoGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPomoTimerActionPerformed

    
    public int convertToSeconds(String time, boolean isStudy){
        final int maxStudy = 120 * 60; /*I have set the maximum study time for one session to 2 hours*/
        final int maxBreak = 40 * 60; /*Maximum break time is 40 min*/
        
        int totalSeconds = 0; /*Initalizing total seconds of timer*/
        
        String[] parts = time.split(":"); /*This splits the different sections of input into hour, min, sec*/
        
        if (parts.length == 2){ /*Logic for if they have only entered an input of minutes*/
            int minutes = Integer.parseInt(parts[0]); /*The first part seperated by the colon is minutes*/
            int seconds = Integer.parseInt(parts[1]); /*The second is for seconds*/
            
            if (minutes < 0 || seconds < 0){ /*Ensures no negative numbers are entered*/
                return 0;
            }
            
            totalSeconds = (minutes * 60) + seconds;
        } else if (parts.length == 3){ /*Logic for if they have entered an input for hours, minutes, and seconds*/
            int hours = Integer.parseInt(parts[0]); /*First part represents hours*/
            int minutes = Integer.parseInt(parts[1]); /*Second represents minutes*/
            int seconds = Integer.parseInt(parts[2]); /*Third represent seconds*/
            
            if (hours < 0 || minutes < 0 || seconds < 0){ /*Ensures that no negative numbers are entered*/
                return 0;
            }
            
            totalSeconds = (hours * 3600) + (minutes * 60) + seconds; /*Formula to find the total seconds of the timer*/
        } else {
            return 0; /*Otherwise, there is no amount of total seconds*/
        }
        
        if (isStudy && totalSeconds > maxStudy){ /*If the student tries to input a study time greater than the max amount*/
            totalSeconds = maxStudy; /*The study timer immediately sets to 2 hour*/
        } else if (!isStudy && totalSeconds > maxBreak){ /*Same logic for the break time*/
            totalSeconds = maxBreak; /*Automatically sets to a 45 min break*/
        }
        
        return totalSeconds;
        
    }
    
    public void switchTimer(){ /*This method is responsible for switching the study and break timers*/
        if (isStudy == true) { /*If currently in study mode (or study timer is running)*/
        isStudy = false;/*Swritch to the break timer*/
        remainingSeconds = convertToSeconds(txtBreakTime.getText(), false); /*Convert the break time into seconds*/
        txtBreakTime.setText(formatTime(remainingSeconds)); /*Formats the timer correctly for the display*/
         } else { /*Otherwise switch from break mode back to study*/
            isStudy = true; 
            remainingSeconds = convertToSeconds(txtStudyTime.getText(), true);
            txtStudyTime.setText(formatTime(remainingSeconds));
         }
         timer.start(); /*Restart the timer for the new session*/
         
         if (currentSong != null) { /*If the user selected background music earlier, it restarts the song for the new session.*/
             switch (currentSong) {
                 case "Song 1":
                     playBackgroundMusic("src/pomodoroGUI/lofiBeatOne.wav");
                     break;
                 case "Song 2":
                     playBackgroundMusic("src/pomodoroGUI/lofiBeatTwo.wav");
                     break;
                 case "Song 3":
                     playBackgroundMusic("src/pomodoroGUI/lofiBeatThree.wav");
                     break;
             }
             
         }
    }
    
    public String formatTime (int totalSeconds){ /*This method takes a total # of seconds and formats it in analog time-keeping format*/
        int hours;
        int minutes;
        int seconds;
        
        hours = totalSeconds/3600;  /*Calculates how many full hours fit within the seconds*/
        totalSeconds = totalSeconds % 3600; /*Get the remainder after calculating for hours*/
        minutes = totalSeconds/60; /*Divide that remainder by 60 to find # of full minutes*/
        seconds = totalSeconds % 60;/*The remainder is just the seconds*/
        
        if (hours > 0){
             return String.format("%02d:%02d:%02d", hours, minutes, seconds); /*If there is at least 1hr, displays as HH:MM:SS*/
        } else {
             return String.format("%02d:%02d", minutes, seconds); /*Otherwise MM/SS*/
        }
    }
    
    public void playSound(){ /*Method plays alarm sound when the timer reaches 0, and switches over*/
        try{
            /*Loads the alarm file sound from the resources*/
            AudioInputStream audioInput = AudioSystem.getAudioInputStream(getClass().getResource("/Melodic_Bones.wav"));
            Clip clip = AudioSystem.getClip(); /*Creates a audio clip that will play the sound*/
            clip.open(audioInput); /*Loads the music I saved into the audio clip*/
            clip.addLineListener(new LineListener() { /*The listener tells the program when the alarm sound has stopped*/
            @Override
            public void update(LineEvent event) {
                if (event.getType() == LineEvent.Type.STOP) /*When it reaches STOP, the alarm has finished*/ {
                    clip.close();  /*The audio stops*/
                    switchTimer();   /*Automatically switches from study to break mode*/
                }
            }
        });

            clip.start(); /*This starts playing the alarm sound*/
        }catch (Exception e){
            e.printStackTrace();
            switchTimer(); /*If audio does not play, the timers will stil switch*/
        }
    
    
    }
    
    public void playBackgroundMusic(String songFile)
    {
        try
        {
            if(backgroundClip != null && backgroundClip.isRunning()){ /*If there is already a music clip playing*/
                backgroundClip.stop();
                backgroundClip.close(); /*The current music stops so two clips are not playing at once*/
        }
            
        File musicFile = new File(songFile);
        URL musicURL = musicFile.toURI().toURL();

        /*Loads the selected song file from the resources. */
        AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicURL); /*musicURL represents audio file chosen from the combo box*/
        backgroundClip = AudioSystem.getClip(); /*Create a clip to hold/play the audio*/
        backgroundClip.open(audioInput); /*Attatch chosen song to clip*/

        
        backgroundClip.loop(Clip.LOOP_CONTINUOUSLY); /*Loop clip continuosuly so it plays for entire session*/
        backgroundClip.start(); /*Start the background music*/
        updateBackgroundVolume(); /*Apply the volume slider method to clip*/

        } catch (Exception e){
            e.printStackTrace();
            System.out.println(songFile);
        }
    
    }
    
    public void updateBackgroundVolume(){
        /*Make sure the background music clip exists and is currently running*/
        if (backgroundClip != null && backgroundClip.isOpen()){
            FloatControl increase = (FloatControl) backgroundClip.getControl(FloatControl.Type.MASTER_GAIN); /*MASTER_GAIN allows us to change the loudness of the sound*/
            
            int slider = Volume.getValue(); /*This gets me the current value of slider*/
            float minVol = increase.getMinimum(); 
            float maxVol = increase.getMaximum(); /*This gets us minimum and maximum value of slider in decibels*/
            
            float volume = minVol + (slider/100f) * (maxVol - minVol); /*This formula converts the sliders numerical (0-100) range into a decibal range, allowing for value to adjust*/
            increase.setValue(volume); /*Connect calculated volume to slider*/
        }
    
    
    }
    public void countdown(){
        /*Decrease the remaining time by 1 second. This is called once/second by Timer*/
        remainingSeconds--;
        
        if (isStudy == true){ /*Update text field depnding on if user is in study session or break*/
            txtStudyTime.setText(formatTime(remainingSeconds));
        } else {
            txtBreakTime.setText(formatTime(remainingSeconds));
        }
        
        if(remainingSeconds <= 0){ /*If countdown has finished*/
            timer.stop();
            playSound();    /*The timer stops, and the alarm sound plays. The alarm sound thus triggers the switch.*/
            
            if (backgroundClip != null && backgroundClip.isRunning()){ /*Checks if background music is playing*/
                backgroundClip.stop();
                backgroundClip.close(); /*Stops background music to not interfere with alarm*/
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new pomodoroGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider Volume;
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnCloseMenu;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMyStreak;
    private javax.swing.JButton btnNotepad;
    private javax.swing.JButton btnOpenMenu;
    private javax.swing.JButton btnPastTest;
    private javax.swing.JButton btnPomoTimer;
    private javax.swing.JButton btnQuestionGen;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStudyTools;
    private javax.swing.JButton btnUploadTest;
    private javax.swing.JComboBox<String> cmbBackground;
    private javax.swing.JComboBox<String> cmbMusic;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBackgroundWOMenu;
    private javax.swing.JLabel lblColouredBG;
    private javax.swing.JLabel lblColouredBGWOMenu;
    private javax.swing.JLabel lblPrompt;
    private javax.swing.JTextField txtBreakTime;
    private javax.swing.JTextField txtStudyTime;
    // End of variables declaration//GEN-END:variables
}
